== Preface.

The following work is chiefly compiled from the writings of Francis Howgill,
which were collected after his death, and published in the year 1676 in one volume folio,
containing 736 pages, and entitled The Dawnings of the Gospel day,
and Its Light and Glory Discovered, etc.

The first part, comprising the life of Francis Howgill,
has however received many additions from writings of some others of the Society of Friends,
and from manuscript letters addressed by Francis
Howgill and Edward Burrough to Margaret Fell,
with which the compiler was kindly furnished by one of his friends;
and he hopes it may prove, at least to the members of his own religious Society,
a useful specimen of the labours and exercises into which the faithful labourers,
in the earlier periods of the Society, were introduced,
in bearing their testimony to the Truth as it is in Jesus.

Many of Francis Howgill`'s other writings besides
those from which extracts are here given,
contain much valuable matter; but those presented to the reader in this volume,
appear to comprise the substance of most of the others,
and to set forth the most important of the doctrines
which he believed himself called upon to advocate.
A catalogue of all his writings which have been published,
is given at the end of this work.

In digesting the whole into its present form,
the compiler has endeavoured to keep to the style and expressions of the originals,
as much as the correction of verbal inaccuracies
peculiar to the day in which the essays were written,
and the reduction of great redundancy of expression, would admit.
And he desires that the perusal of the records of the lively zeal,
and patient and faithful labours, of such as were successful advocates of the Truth,
may tend to stir up others to diligence, in the most important object of life,
which is righteousness; that so they may know its work which is peace;
and may prove its effect to be quietness and assurance forever.

