== Chapter II.

[.chapter-synopsis]
* An account of Francis Howgill`'s Convincement, by the Preaching of George Fox
* His Imprisonment with James Nayler

It appears that the great change just alluded to, took place in Francis Howgill`'s mind,
in the year 1652.
He was at a fair, at Sedburgh, in the west of Yorkshire, through which,
George Fox passed, declaring the day of the Lord.
George Fox went afterwards into the steeple-house yard;
and many of the people of the fair went to him, with a number of priests,
and professors of religion.
There he declared the everlasting truth of the Lord,
and the word of life for several hours: showing that the Lord was come,
to teach his people himself; and to bring them off from all the world`'s ways,
and teachers; that these teachers were like those that were of old,
condemned by the prophets, by Christ, and by the apostles.
He exhorted the people to come off from the temples made with hands;
and to wait to receive the Spirit of the Lord,
that they might know themselves to be the temples of God.
Not one of the priests opened his mouth against what he declared; but a captain said:
"`Why will you not go into the Church?
this is not a fit place to preach in?`"
George Fox told him, he denied their church.
Then stood up Francis Howgill, who had not seen George Fox before,
and undertook to answer the captain; and soon put him to silence, and said:
"`this man speaks with authority and not as the scribes.`"

The following account of the remarkable meeting, at which, Francis Howgill, John Audland,
John Camm, Richard Hubberthome, and many others were convinced of the everlasting truth,
is extracted from George Fox`'s journal, page 68.

[quote]
____
The next First-day, I came to Firbank chapel, in Westmoreland,
where Francis Howgill and John Audland, had been preaching in the morning.
The chapel was full of people, so that many could not get in.
Francis said, he thought I looked into the chapel, and his spirit was ready to fail,
the Lord`'s power did so surprise him; but I did not look in.
They made haste, and had quickly done; and they, and some of the people went to dinner;
but abundance stayed till they came again.
John Blaikling and others came to me, and desired me not to reprove them publicly;
for they were not parish teachers, but pretty tender men.
I could not tell them, whether I should or no, though I had not at that time,
any drawings to declare publicly against them;
but I said they must leave me to the Lord`'s movings.

While others were gone to dinner, I went to a brook, got a little water,
and then came and sat down on the top of a rock, hard by the chapel.
In the afternoon the people gathered about me, with several of their preachers.
It was judged there were above a thousand people,
to whom I declared God`'s everlasting truth, and word of life, freely and largely,
for about the space of three hours, directing all to the Spirit of God in themselves;
that they might be turned from darkness to light, and believe in it;
that they might become children of it, and might be led into all truth,
and sensibly understand the words of the prophets, of Christ, and of the apostles:
and might all come to know Christ to be their teacher to instruct them,
their counsellor to direct them, their shepherd to feed them,
their bishop to oversee them, and their prophet to open divine mysteries to them;
and might know their bodies to be prepared, sanctified,
and made fit temples for God and Christ to dwell in.

In the openings of heavenly life, I explained unto them the prophets,
and the figures and shadows, and directed them to Christ the substance.
Then I opened the parables and sayings of Christ, and things that had long been hid;
showing the intent, and scope of the writings of the apostles.
I showed also the state of the apostacy, since the apostles`' days;
that the priests have got the Scriptures,
but are not in the Spirit which gave them forth: but make a trade of holy men`'s words;
and are found in the steps of the false prophets, chief priests, scribes,
and pharisees of old, and are such as the true prophets, Christ,
and his apostles cried out against.
Many old people went into the chapel, and looked out at the windows;
thinking it a strange thing to see a man preach on a hill or mountain,
and not in their church, as they called it; whereupon I was moved to inform the people,
that the steeple-house and ground whereon it stood, were no more holy than that mountain;
and that those temples, which they called the dreadful houses of God,
were not set up by the command of God and Christ; nor their priests called of God,
as Aaron`'s priesthood was; nor their tithes appointed by God,
as those among the Jews were: but that Christ was come,
who ended both the Temple and the worship, and the priests, and their tithes;
and all should now hearken to Him, for he said, "`Learn of Me:`" and God said of Him,
"`This is my beloved Son, in whom I am well pleased, hear ye Him.`"
I declared that the Lord God had sent me, to preach the everlasting gospel,
and word of life amongst them; and to bring them off from all these temples, tithes,
priests, and rudiments of the world, which had got up since the apostles`' days;
and had been set up by such,
as had erred from the spirit and power that the apostles were in.
Very largely was I opened at this meeting;
the Lord`'s convincing power accompanied my ministry,
and reached home to the hearts of the people;
whereby all the teachers of that congregation, who were many,
and also a number of the people, were convinced of God`'s everlasting truth.
____

In a testimony respecting Francis Howgill, by George Fox, he states him to have been,
"`one of the Lord`'s worthies, that preached His everlasting word of life,
from about the year 1652, until the year 1668.
That, he had great acquaintance with the higher sort of priests;
and after he had received the Lord`'s power, and word of life, he was a torment to them.
And he confessed to some of the priests, that the knowledge of God and his truth,
he knew no more of whilst he was amongst them, as to the inward enjoyment of it,
than a child of five years old.`"
"`When John Audland and he, who had received some money for preaching,
at a parish called Colton, in Furnace Fells, in Lancashire,
had received the gospel freely, and the word of life from Christ,
they were commanded of the Lord, to go and return that money back again,
to the parish and people, from whom they had received it; which they did:
and this made the priests, and the professors, the more to rage.`"

"`As the Son of God came to be revealed in him, he began to know his command;
and powerfully and freely to preach Him, and his word of life.
John Audland and he, all the days of their lives, after their convincement,
preached Christ Jesus freely, as they had received Him, and turned many to God.`"
But, "`no sooner was his mouth opened, than the priests, magistrates, and professors,
began to rage against him, and to be offended at the word of God, and the gospel.`"

Francis Howgill was one of the friends alluded to, in [.book-title]#H. Tuke`'s Biographical Notices,#
vol.
2 page 69, who with James Nayler, designed to have held a religious meeting, at Orton,
in Westmoreland, in the year 1652.
"`The priests invited them to hold a meeting in the town field,
and they accepted the offer,
seeing that a private house was not sufficient to accommodate the numbers collected.
Here the priests began to dispute, on the propriety of meeting there,
and collecting so many people together to break the peace.
Much wrangling succeeded; after which, James returned to the house of one of his friends,
where the meeting was held, though with much disturbance from rude people,
who were collected for the purpose of mischief; no material injury was, however,
sustained; and that evening, James left the place, and thus, for the present,
escaped the fury of his enemies.

The priests in this country, appear to have been uncommonly violent and cruel.
Not content with preaching against Nayler, and imputing to him blasphemy,
with many other false accusations, they raised an armed multitude,
who came to the house where he was, threatening to knock out his brains against the wall,
or to pull down the house if he would not come out;
and when they were told that the doors were open, the people informing the priests,
they rushed violently into the house, seized James Nayler by the throat,
dragged him into the field, and afterwards, with a pitch fork, struck off his hat,
commanding him to answer such questions, as the priests should ask him.
They put many questions to him, which he answered so well,
that they could not take any advantage from them to prosecute him.
After much wrangling, one of the priests advised the people,
not to receive James Nayler into their houses, and then departed,
leaving him and his friends to the violence of the rude multitude.
But a justice of the peace who was present,
seeing the dangerous situation in which Friends were placed,
kindly assisted them in returning to the house from whence they came,
which they entered without receiving much harm.

On this occasion, James was publicly engaged to praise the Lord,
for the wonderful deliverance from the power of his enemies, which some of them hearing,
said, "`if we let him go on thus, all people will run after him.`"
He was therefore, again hailed out of the house,
taken by the justice and priests to a neighbouring ale-house,
and thence committed to Appleby jail.

He was taken to Kirby Stephen that night; and a guard placed over him in a chamber.
Several of his friends followed him, and amongst them Francis Howgill,
who took an opportunity of preaching to the people,
who were collected in the street to a great number.
Complaint of his preaching being made, he was sent for before a justice,
who commanded him to put off his hat.
He answered, "`I know no such law.`"
One of the priests, five of whom were present, said,
he will tread both ministry and magistracy under foot.
Francis replied, "`thou art a false accuser, prove wherein.`"
Then one of the bystanders took off his hat, and threw it into the fire.
Then said the justice, "`What is this thou speakest against the ministers?`"
He answered, "`What hast thou to accuse me of?`"
whereupon one affirmed that he said, all ministers that taught for hire,
and in steeple-houses, were enemies, and liars against Jesus Christ,
and no ministers of Jesus Christ.
Upon that the justice said, "`Thou speakest against the law,
for the law gives them their maintenance.`"
He replied, "`I meddle not with the law, but with their practice.`"
Then Francis said to the priest,
"`didst thou ever know a minister of Christ that was a persecutor,
or did labour to imprison any?`"
And after some more discourse, he said to the priest,
"`I have seen a great deal of tyranny and persecution in this day`'s actions.`"
Then said the justice to the people, "`Take notice,
he saith the law I act by is tyranny and persecution:`" to which the people assented.
Then said Francis, "`thou mayst give out to the people what thou wilt,
but I speak not of the law, but of your actions.`"
Upon that they made out a mittimus to send him to prison,
placing over him a guard of eight men, who spent that night in drinking, swearing,
and filthy talking;
and the more they were reproved the more often they repeated their wickedness.
On the morrow he was sent to Appleby jail, along with James Nayler.

Whilst these innocent sufferers were in prison, their enemies were busily employed,
in obtaining all the accusations they could against them;
and at the sessions held at Appleby, in the month called January, 1652,
James Nayler was tried on an indictment for blasphemy.
This charge was occasioned by the doctrine preached, and particularly insisted on,
by our early Friends,
that of the light of Christ universally communicated to the human race.
This they termed, with the apostle of the gentiles,
"`Christ in you the hope of glory;`" and further
illustrated by an exhortation of the same apostle:
"`Prove yourselves; know ye not your own-selves, how that Jesus Christ is in you,
except ye be reprobates.`"

This doctrine, the enemies of the Society,
endeavoured to convert into a blasphemous application of Christ to themselves; but,
notwithstanding the strenuous endeavours of some of the justices,
the charge could not be substantiated; and Anthony Pearson, who then sat on the bench,
was convinced by the examination of James Nayler.
Benson was another of the justices,
and was fully sensible of the insufficiency of the evidence to prove the charge of blasphemy;
but notwithstanding the evident, innocence of the prisoner,
two other justices were so violent as to commit him upon the petition of the priests,
though at the hazard of being fined by the judges at the assizes.
It was therefore ordered that James Nayler and Francis Howgill should remain in prison,
where they were arbitrarily confined about five months and then discharged.`"^
footnote:[For particulars of James Nayler`'s life, see [.book-title]#Sewell`'s History of Friends,#
[.book-title]#Tuke`'s Biographical Notices,# vol. 2. page 67 to 92,
and a refutation of some of the more modern misrepresentations of the Society of Friends,
commonly called Quakers, with [.book-title]#A Life of James Nayler,# by Joseph Gurney Bevan.]

After Francis Howgill was set at liberty,
he grew valiant and bold for the name of the Lord;
and travelled up and down on foot preaching the everlasting Gospel;
and went to many steeple-houses,
to warn both priests and people of the day of the Lord that was coming upon them;
directing them to Christ Jesus, their Teacher and Saviour.
