== Chapter V.

[.chapter-synopsis]
* Francis Howgill and Edward Burrough return to London
* Several meetings established
* Francis visits Oliver Cromwell in company with John Camm; and afterwards writes to him
* He joins Edward Burrough in Suffolk
* They go to James Parnel at Cambridge, and visit the Isle of Ely and Norfolk
* Return to London

On the return of Francis Howgill and Edward Burrough to London,
they saw the fruit of their labour in that city, and rejoiced:
for the mighty power of God had so manifested itself,
that many mouths were opened to bear testimony to the Truth,
and several meetings were established;
and those who continued in their doctrine were more separated from the multitude.
A meeting was held for some time at the house of a widow, named Sarah Matthews,
in White-Cross Street, on first-day forenoons; and one at Simon Dring`'s, in Moorfields,
in the afternoons; and sometimes at Glazier`'s Hall, at the house of Sarah Yates,
a widow, in a Court in Aldersgate-Street.

They continued some weeks in London labouring diligently,
not only amongst those who were thus gathered from such as cried:
"`Lo! here is Christ,`" and "`Lo!
He is there,`" to the knowledge of his clear arising in themselves,
as the lightening coming out of the east, and shining unto the west;
and to the witnessing of his Spirit abiding in them,
and giving them strength to overcome sin; but they had also many public meetings,
at which numbers were convinced.
During their stay in the city, they were joined by George Fox, Richard Hubberthorne,
James Nayler, and some other labourers in the same cause.

About the beginning of the year 1655,
Francis Howgill went with John Camm to visit Oliver Cromwell, in order to warn him,
and to deliver some papers addressed to him by some friends,
expostulating with him respecting several laws,
which were at that time so rigourously put in force against friends,
that many of their ministers and others were suffering imprisonment under them.
In a letter to Margaret Fell on this occasion, Francis says of the Protector:
"`He is full of subtlety and deceit; and will speak fair;
but hardens his heart and acts secretly underneath.`"
Soon after this visit he addressed the following letter to Cromwell:

[.embedded-content-document.letter]
--

[.salutation]
Friend,

I was moved of the Lord to come to thee, to declare the Word of the Lord,
as I was moved of the Lord, and to deal plainly with thee as I was commanded,
and not to petition thee for anything;
but to declare what the Lord had revealed to me concerning thee:
and when I had delivered what I was commanded, thou questionedst it,
whether it was the Word of the Lord or not, and soughtest, by thy reason, to put it off;
and we have waited some days since, but cannot speak to thee; therefore,
I was moved to write to thee and clear my conscience, and to leave thee.
Therefore hear the Word of the Lord: thus saith the Lord,
I chose thee out of all the nation, when thou wast little in thy own eyes,
and threw down the mountains and the powers of the earth before thee,
which had established wickedness by a law; and I cut them down,
and broke the yokes and bonds of the oppressor, and made them stoop before thee,
and made them as a plain before thee, that thou passedst over them,
and trode upon their necks: but, thus saith the Lord,
Now thy heart is not upright before Me, but thou takest counsel and not at Me;
and thou art establishing peace, and not by Me; and my Name is not feared,
and I am not sought after: but thy own wisdom thou establishest.
"`What,`" saith the Lord, "`Have I thrown down all the oppressors, and broken their laws,
and art thou now going to establish them again! and art going to build again,
that which I have destroyed?`"
Wherefore, thus saith the Lord: "`Wilt thou limit Me, and set bounds to Me, when,
and where, and how, and by whom I shall declare myself and publish my Name?
Then will I break thy cord, and remove thy stake, and exalt myself in thy overthrow.

Therefore, this is the Word of the Lord to thee, whether thou wilt hear or forbear:
"`If thou take not away all those laws which are made concerning religion,
whereby the people which are dear in mine eyes are oppressed,
thou shalt not be established; but as thou hast trodden down my enemies by my power,
so shalt thou be trodden down by my power; and thou shalt know that I am the Lord;
for my Gospel shall not be established by thy sword, nor by thy law; but by my might,
and by my power, and by my Spirit.
Unto thee, this is the Word of the Lord; stint not the Eternal Spirit,
by which I will publish my Name, when, and where, and how I will; for if thou dost,
thou shalt be as dust before the wind: the mouth of the Lord hath spoken it,
and He will perform his promise.
For this is what I look for at thy hands, saith the Lord:
that thou shouldest undo the heavy burdens, and let the oppressed go free.
Are not many shut up in prison, and some stocked, some stoned,
and some shamefully entreated?
and some are judged blasphemers, by those who know not the Lord,
and by those laws which have been made by the will of man,
and stand not in the will of God.
And some suffer now, because they cannot hold up the types,
and so deny Christ come in the flesh;
and some have been shut up in prison because they could not swear,
and because they abide in the doctrine of Christ;
and some for declaring against sin openly in markets, have suffered as evil-doers:
and now if thou let them suffer in this nature, and by those laws, and count it just,
I will visit for these things, saith the Lord;
and I will break the yoke from off their necks, and I will bring deliverance another way,
and thou shalt know that I am the Lord.

--

William Sewell, in his [.book-title]#History of the People Called Quakers,#
says in reference to this letter: "`How this was received I am not acquainted;
but this I have understood, that some of Cromwell`'s servants,
and amongst these one Theophilus Green, and also Mary, afterwards wife of Henry Stout,
were so reached by Francis Howgill`'s discourse,
that some time after they entered into the society of the Quakers, so called.`"

In the second month of this year, Edward Burrough went to Edmund`'s Bury,
where Francis Howgill joined him; and they went from thence into the Isle of Ely,
at the time of the assizes, and had a very precious meeting.

The Baptists at Cambridge had challenged James Parnel to a dispute;
these friends therefore returned with him to Cambridge On the day appointed.
The Baptists had fixed on a steeple house to dispute in;
but when they went down they found themselves shut out.
The town and scholars were in an uproar;
and when the Baptists perceived that Francis and Edward were there,
they were unwilling to meddle.
Howgill and Burrough were so thronged,
that they conceived they were in danger from the multitude, who were very rude;
and therefore made their way to the house of justice Blackley.
The Baptists then perceiving the people to be on their part, ran up to the shire-house,
and James Parnel went after them: when the multitude were appeased,
Francis and Edward also went up.
The Baptists then asked James a question,
to which he did not give them such an answer as they wished for;
they therefore went away, and desired the people not to let Friends stay after them.
In a short time, Francis and his companions went to the house of a Friend in the town;
to which they sent for their brethren and a number of others,
and had a meeting that evening with them.
The next day, they went to a place where they had two meetings in a yard,
at which many persons were convinced; amongst whom were some who had been unruly.

On the following first-day, they had another meeting in the Isle of Ely,
at which there were about seven hundred people; to this one Col.
Russel, whose son had married Cromwell`'s daughter, sent two priests,
one of whom was an Independent; but they were both confounded, and returned to Russel,
and told him, that the Quakers were far before them; upon which,
he wrote to desire the friends to go to his house, or send him word where they would be,
and he would come to them.
They readily accepted his invitation, and were kindly received.
All the family came together, and they declared to them the Way of Life.
The colonel`'s wife was much affected, and wept greatly.
The next day the colonel sent to inform them,
that if they would go to the house of the Independent,
he would send him word and acquaint the people;
they gladly received this message and went, as did also the colonel, his wife,
and many of their family, and the Independents, with many other people of the parish,
and their teachers.
Here they spoke powerfully as the Spirit gave utterance;
and the priests being convinced of the truth of their doctrine, hung down their heads,
and shame covered them; but the hearts of the people were drawn to the friends in love.

In the course of this journey, they visited the city of Norwich; in which,
as well as in most of the market-towns of Norfolk and Suffolk, they had meetings.

On their return to London, they were again refreshed amongst their friends,
whom they found prospering and growing in wisdom; and Howgill informs us,
that "`divers of them were moved to go forth in the ministry:`"
two young men and two young women for Barbados-- a young
Scotchman for Scotland--other two young women for Wales,
and two others to Oxford;
and many others to preach the Gospel to the congregations they had formerly belonged to:
and they were yet preserved at liberty.
