== Chapter VII.

[.chapter-synopsis]
* Francis Howgill and Edward Burrough meet at Bristol Fair
* Return to London, where, after going again into the country, Francis is imprisoned with many others, on the false charge of insurrection
* Being liberated, he travels into various parts of the nation. About this time he writes an account of what he foresaw respecting Friends
* And, at Reading, writes a Testimony concerning Edward Burrough

After returning from Ireland, Francis Howgill and Edward Burrough separating for a while,
went through many counties of England, holding numerous meetings,
and met again at Bristol, at the time of the fair,
where they had a meeting with about five thousand people on a first-day.

In a short time they received letters from London, by which they were informed,
that some who had been convinced of the Truth there,
had lent an ear to certain deluded people,
and had been turned from the simplicity of the Gospel of Christ.
On this occasion Edward Burrough went speedily to that city,
to endeavour to prevent the spreading of the delusions
by which these people had been led away.
But Francis Howgill and John Audland still remained in Bristol, and from whence,
after holding a few more meetings, Francis also hastened to London;
where he continued with his companion for some time,
labouring particularly for the restoration of those,
who had fallen into the delusions before alluded to,
until things were again brought into a more settled state.

Few particulars appear to be found, respecting the labours of Francis Howgill,
from the latter part of the year 1656 to 1661.
But he is stated by George Fox, to have gone with him from Robert Widders`'s,
along with Thomas Curtis, to Swarthmore, in 1660.
And George Fox says, in a Testimony concerning him,
that he continued in the labour of the Lord, from the time of his return from Ireland,
till the year 1661; when he was imprisoned in London with many others,
on suspicion of being concerned in the insurrection of the fifth Monarchy people.

Friends, notwithstanding their avowed testimony against all war and bloodshed,
as utterly inconsistent with Christianity,
were often charged by persons evilly disposed towards them,
with being parties in any plots or disturbances which happened to occur; and,
by this means, they were subjected to long and unmerited imprisonments.

Being cleared of this charge, the Friends imprisoned on this account were set at liberty.
Their weapons being spiritual they sought not earthly power;
but patiently endured suffering, in the hope of obtaining,
by submission to the guidance of the Holy Spirit, a better inheritance,
through the mercy of God, and the mediation of Jesus Christ.

After the liberation of Francis Howgill,
he travelled into various parts of the nation in the work of the Lord,
and turned many to God.

This being a time of hot persecution, he was concerned to give forth the following paper,
which,
with many other powerful exhortations of such as stood boldly for the cause of Truth,
and never left the oppressed flock of its professors,
tended greatly to their encouragement; for how furious soever their enemies were, these,
nevertheless, continued faithful in supplications and fervent prayers to God,
that He might be pleased to assist them in their upright zeal,
as they aimed at no selfish end; but acting from a true fear and reverence before Him,
they durst not omit their religious assemblies.
And thus, persevering in faithfulness to what they believed the Lord required of them,
in process of time,
when their enemies had taken such measures as they were persuaded would suppress,
and ultimately extinguish the Quakers,
the Almighty was pleased to overrule and confound the wicked devices of their persecutors:
although in unsearchable wisdom He saw meet before that time,
to permit many of his humble followers to seal their testimony with their lives,
in close prisons, and under severe bodily privations.

[.embedded-content-document.paper]
--

[.blurb]
=== The paper given forth by Francis Howgill.

The cogitations of my heart have been many, deep, and ponderous some months, weeks,
and days,
concerning this people which the Lord hath raised to bear testimony unto his name,
in this the day of his power; and intercession hath been made often for them to the Lord;
and a patient waiting to know his mind concerning them, for the time to come; which,
often, I received satisfaction in as to myself; but yet something,
I was drawn by the Lord to wait for, that I might comfort and strengthen his flock,
by an assured testimony.
And while I was waiting out of all visible things,
and quite out of the world in my spirit, and my heart upon nothing but the Living God,
the Lord opened the springs of the great deep,
and overflowed my whole heart with light and love; and my eyes were as a fountain,
because of tears of joy, because of his heritage, of whom He showed me;
and spake unto me in a full, fresh, living power, and a holy, full testimony,
so that my heart was ravished there with joy unspeakable; and I was out of the body,
with God in his heavenly paradise, where I saw and felt things unutterable,
and beyond all demonstration or speech.
At last the life closed with my understanding, and my spirit listened unto Him;
and the everlasting God said:
'`Shall I hide anything from them that seek my face in righteousness?
Nay, I will manifest it to them that fear me; I will speak, do thou listen,
and publish it among my people, that they may be comforted,
and thou satisfied.`' And thus said the Living God of heaven and earth,
upon the 28th of the third month, 1662: '`The sun shall leave its shining brightness,
and cease to give light to the world--and the moon shall be altogether darkness,
and give no light unto the night--the stars shall cease
to know their office or place--my covenant with day,
night, times, and seasons, shall sooner come to an end,
than the covenant I have made with this people, into which they have entered with me,
shall end or be broken.
Yea, though the powers of darkness and hell combine against them,
and the jaws of death open; yet will I deliver them, and lead them through all.
I will confound their enemies as I did in Jacob,
and scatter them as I did in Israel in the days of old; I will take their enemies,
I will hurl them hither and thither, as stones hurled in a sling;
and the memorial of this nation, which is holy unto Me, shall never be rooted out;
but shall live through ages, as a cloud of witness in generations to come.
I have brought them to the birth, yea, I have brought them forth; I have swaddled them,
and they are mine.
I will nourish them, and carry them as on eagle`'s wings;
and though clouds gather against them, I will make my way through them;
though darkness gather together on a heap, and tempests gender,
I will scatter them as with an east wind; and nations shall know they are my inheritance;
and they shall know I am the Living God,
who will plead their cause with all that rise up in opposition against them!`'

These words are holy, faithful, eternal, good, and true;
blessed are they that hear and believe unto the end: and because of them,
no strength was left in me for a while; but at last my heart was filled with joy,
even as David`'s, when the ark of God was brought from the house of Obed-Edom,
when David danced before it, and Israel shouted for joy.

[.signed-section-signature]
Francis Howgill.

--

In the 12th month, 1662, he was at Reading, in Berkshire,
where he wrote a Testimony concerning the life, death, trials, travels,
and labours of Edward Burrough, who died in Newgate that year, aged twenty-seven years,
a prisoner for the testimony of Jesus.
They had been companions and fellow-labourers in the Gospel for many years.
They were closely united to each other,
having their hearts set upon the propagation of that Truth,
by which liberty from the bondage of sin is obtained,
and salvation received through Jesus Christ, the true Light of the world.

The following pathetic lamentation over Edward Burrough, is extracted from the Testimony.

[.embedded-content-document.testimony]
--

Shall days, or months, or years wear out thy name, as though thou hadst no being?
O nay!
Shall not thy noble valiant acts, and mighty works,
which thou hast wrought through the power of Him who gave thee being,
live in generations to come?
O yes!
The children that are yet unborn, shall have thee in their mouths;
and thy works shall testify of thee, in generations that yet have not a being,
and shall count thee blessed.
Did thy life go out as the snuff of a candle?
O nay!
Thou hast penetrated the hearts of many; and the memorial of the just shall live forever,
and be had in renown among the children of wisdom forever; and they who are in that,
shall see thee there, and enjoy thee there, though thou be gone away hence,
and can no more be seen in mutability;
yet thy life and thy spirit shall run parallel with immortality.

O Edward Burrough!
I cannot but mourn for thee: yet not as one without hope or faith;
knowing and having a perfect testimony of thy well-being, in my heart,
by the Spirit of the Lord; yet thy absence is great,
and years to come shall know the want of thee.
Shall I not lament as David did for a worse man than thou, even for Abner,
when in wrath he perished by the hand of Joab, without any just cause,
though he was a valiant man.
"`David lamented over Abner, and said: "`Died Abner as a fool dieth?`"
O nay! he was betrayed of his life, by the hand of the oppressors,
whose habitations are full of cruelty.
O my soul! come not thou within their secret;
for thy blood shall be required at the hands of them who thirsted after thy life;
and it shall cry as Abel`'s, who was in the faith: even so wert thou.
It shall weigh as a ponderous millstone upon their necks, and shall crush them under;
and be as a worm that gnaweth and shall not die.

When I think upon thee, I am melted into tears of true sorrow,
and because of the want that the inheritance of the Lord hath of thee,
my substance is even as dissolved.
Shall I not say, as David said, of Saul and Jonathan,
when they were slain in Mount Gilboa:
'`The beauty of Israel is slain upon the high places;`'
even so wast thou stifled in nasty holes and prisons,
and many more who were precious in the eyes of the Lord;
and surely precious wast thou to me, O dear,
Edward! '`I am distressed for thee my brother! very pleasant hast thou been to me,
and my love to thee was wonderful, passing the love of women.
O thou! whose bow never turned back, neither sword empty from the blood of the slain,
from the slaughter of the mighty;`' who made nations and
multitudes shake with the Word of Life in thy mouth;
and wast very dreadful to the enemies of the Lord: for thou didst cut like a razor;
and yet to the seed of God brought forth, thy words dropped like oil,
and thy lips as the honey-comb.

Thou shalt be recorded amongst the valiants of Israel, who attained to the first degree,
through the power of the Lord, that wrought mightily in thee in thy day;
and thou wast worthy of double honour, because of thy work`'s sake.
Thou wast export to handle thy weapon; and by thee the mighty have fallen,
and the slain of the Lord have been many.
Many have been pricked to the heart, through the power of the Word of Life;
and coals of fire from thy life, came forth of thy mouth,
that in many a thicket and among many briers and thorns, it came to be kindled;
and did devour much stubble that cumbered the ground, and stained the earth.
O, how certain a sound did thy trumpet give!
And how great an alarm didst thou give in thy day,
which made the host of the uncircumcised greatly distressed!

What man so valiant, though as Goliath of Gath,
would not thy valour have encountered with, while many despised thy youth!
And how have I seen thee, with thy sling and thy stone, despised weapons as to war with,
wound the mighty!
And that which hath been contemptible to the Dragon`'s party, even as the.
jaw-bone of an ass, with it thou hast slain the Philistines, heaps upon heaps, as Sampson.
Thou hast put thy hand to the hammer of the Lord,
and hast often fastened nails in the heads of the Lamb`'s enemies, as Jael did to Sisera;
and many a rough stone hast thou polished and squared,
and made fit for the building of God; and much knotty wood hast thou hewed in thy day,
which was not fit for the building of God`'s house;
O thou prophet of the Lord! and thou shalt forever
be recorded in the Lamb`'s book of life,
among the Lamb`'s worthies, who have followed the Lamb through great tribulations,
as many can witness for thee, from the beginning; and at last hast overcome,
and hast been found worthy to stand with the Lamb upon Mount Zion, the hill of God,
as I have often seen thee; and thy heart well tuned as a harp to praise the Lord,
and to sound forth his great salvation,
which many a time made glad the hearts of them that did believe,
and strengthened their faith and hope.

Well, thou art at rest, and bound up in the bundle of life;
and I know tears were wiped away from thy eyes,
because there was no cause of sorrow in thee;
for I know thou witnessedst the old things done away; and there was no curse,
but blessings were poured upon thy head as rain, and peace as a mighty shower;
and trouble was far from thy dwelling, though in the outward man trouble on every side;
and thou hadst a greater share in that for the Gospel`'s sake, though a youth,
in thy time, than many besides; but now thou art freed from that,
and hast obtained a name, through faith, with the saints in light.

Well, hadst thou more to give up than thy life, for the Name of Jesus, in this world?
Nay, and to seal thy testimony, committed unto thee, with thy blood,
as thou hast often said in thy day;
which shall remain as a crown upon thee forever and ever.
And now thou art freed from the temptations of him who had the power of death;
and art freed from thy outward enemies,
who hated thee because of the life that dwelt in thee,
and remainest at the right hand of God,
where there is joy and pleasure forevermore in the everlasting Light;
which thou didst often testify unto, according to the word of prophecy in thy heart,
which was given unto thee by the Holy Ghost;
and thou art at rest in the perfection thereof, in the beauty of holiness;
yet thy life and thy spirit I feel as present, and have unity with it and in it,
beyond all created and visible things, which are subject to mutation and change.
And thy life shall enter into others, to testify unto the same Truth,
which is from everlasting to everlasting; for God hath raised,
and shall raise up children unto Abraham of them that have been as dead stones,
whose power is almighty, great in his people in the midst of his enemies.^
footnote:[For a further account of Edward Burrough, see [.book-title]#Tuke`'s Biographical Notices,# vol.
8.]

--
