== Chapter XI.

Francis Howgill`'s advice to his daughter.

The Unchangeable Testament, and Will, and Counsel of Francis Howgill,
Left to His Daughter Abigail Howgill.

Daughter Abigail,--This is for thee to observe, and keep,
and take heed unto all the clays of thy life,
for the regulating of thy life and conversation in this world;
that thy life may be happy, and thy end blessed,
and God glorified by thee in thy generation.
These things I bequeath unto thee, and counsel thee ever to observe,
being the chief things alone I have to bestow upon thee;
which I prize more than outward riches.
Do thou so also, and observe and keep my sayings; and I charge thee before God,
and by the coming of our Lord Jesus Christ, that thou observe what I say;
the which I am moved of the Lord to leave behind for thee,
and in tender love and affection unto thee, my daughter,
that the Lord may give his blessing unto thee, and make thy ways prosperous,
and thy latter end peace.

First of all, know this: I was never born to great possessions,
nor did inherit great matters in this world;
but the Lord hath always endowed me with sufficiency and enough,
and hath been as a tender Father unto me; because my heart trusted in Him,
and did love the way of righteousness from a child.
I have no great portion to bestow upon thee, of the things of this world;
yet of that little which I have, and God hath blessed me with,
something I shall give thee, which I shall not mention here;
but thou wilt know at my decease; but thy dear mother I rather commend thee unto, who,
I trust, will provide sufficiently for thee;
unto whom my heart hath been upright before the Lord:
she had a sufficient portion and dowry when I married her,
the which I shall be sorry much to lessen or impair; and whatever was hers,
if it please the Lord I decease before her, I freely leave unto her,
as was ever my intention and purpose, which hath not, neither shall alter,
through the strength of God, as God only knows, and bears me record;
and it shall be manifest unto all in due time, as it is unto the Lord,
who hath been with me in the midst of many troubles, trials, and sufferings,
and hath lifted up my head above my adversaries, because I trusted only in his Name;
which at all times I found as a refuge, and a present help in time of need;
and so it will be unto thee, if thou fear his Name, and trust in Him, forever.

And now, dear child, hearken unto the words of my mouth, and listen unto my counsel;
ponder these things I leave behind me, unto thee to observe,
that thy days may be long upon the earth, and blessed and comfortable unto thee,
and an honour to God in thy generation.
The time when thou wast born and came into the world,
was a time of deep exercise and trouble with me, not from the Lord,
who always spake peace unto me, and did sustain me;
but by reason of the adversary of mankind, who always seeks to devour the good in all,
and is the sower of discord and mischief in the hearts of them who fear not the Lord,
neither abide in his counsel; in whom he enters,
as any place is given unto his temptations, and corrupts the mind:
but though it was a great trial that came upon me,
the Lord kept my heart in uprightness unto Him and gave me much patience;
so that though the earth had been removed into the sea,
and all outward things had run into confusion, and nature had changed its course,
the Lord gave me a resolution and strength not to be troubled, neither offended;
because He did support me.

At that time wast thou born; and therefore I called thy name Abigail; which signifies,
the father`'s joy or delight; for in thee I was comforted;
and my present trouble mitigated.

My counsel unto thee is, that thou remember thy Creator in the days of thy youth,
and fear the Lord in thy youth; and learn to know Him, and serve Him all thy days.
First, seek the kingdom of God, and the righteousness thereof; it is not far from thee;
it is within thee; it consists in life and power; and it stands in righteousness, truth,
equity, justice, mercy, long-suffering, patience, love, light, and holiness:
this is the being and centre thereof.
Therefore seek not lo here or lo there without thee, in this or that outward observation;
for many seek there and never find it; but seek, and thou shalt find; wait,
and thou shall receive.

If thou inquire in what must I seek, and what must I wait in, and how must I seek;
I inform thee, thou must silence all thy own thoughts;
and thou must turn thy mind to that which is pure, holy, and good, within thyself;
and seek and wait in that, in the Light of Jesus Christ, wherewith thou art enlightened;
which shows thee when thou dost evil, and checks and reproves.
Take heed unto that, and it will show the evil motions and thoughts;
and as thou lovest it, it will subdue them, and preserve thee for the time to come,
out of evil: for though thou be born into the world a reasonable creature,
yet thou must be born again, and be made a new creature;
or else thou canst not enter into God`'s kingdom.--Thou
must know the seed of the kingdom in thyself,
of which thou must be born, and formed again into God`'s image.
I have told thee that God hath sown it in thee, a grain of it, a measure of it,
a portion of it, a measure of Light and Truth, of righteousness and holiness.
Keep in thy mind to that, and love it,
and thou wilt feel the Heavenly Father working in thee, and creating thee to life,
through Jesus Christ, who hath enlightened thee;
and thou wilt feel the power of the Lord strengthening thee in thy little,
and making thee to grow in the immortal seed of his kingdom, and to out grow,
and over grow all evil; so that thou wilt daily die to that, and have no pleasure in it;
but in the Lord, and in his goodness and virtue shed abroad in thy heart;
which thou wilt taste and feel within, and have joy and comfort therein.

Love the Lord with thy heart and soul, even Him that made thee,
and gave thee and all things in heaven and earth a being;
still wait for the knowledge of Him in thyself: He is not far from thee;
but near unto thee, and unto all that call upon Him in an upright heart.
And do thou inquire of thy dear mother, she will inform thee; she knows Him,
and the way to life and peace; and hearken unto her instruction.

God is a Spirit, a pure Spirit of light, life, and power.
He it is that searcheth the heart, and shows thee when thou dost evil, or thinkest evil,
or speakest evil; and shows unto men and women their thoughts.
That which shows the evil is good, and that which shows a lie is Truth.
This is within; take heed to it.
This is called God`'s Spirit in the Scriptures; believe in it, love it,
and it will quicken thy heart to good, and it will subject the evil.
Here is thy teacher near thee; love it.
If thou act contrary to it, it will condemn thee;
therefore take heed unto this Spirit of Truth, and it will enlighten and enliven thee;
and it will open thy understanding,`' and give thee to know what God is,
and to do that which is good and acceptable in his sight.
This Spirit never errs, but leads out of all error into all truth.

O Abigail, believe my words! they are the words of God, and Truth.
Be not wanton, but sober-minded in thy youth, and wait on the Lord within:
hearken unto Him.
God is Light immortal, Life immortal, Truth immortal; an everlasting, eternal Spirit.
He speaks spiritually and invisibly within the hearts and consciences of men and women;
hear what He speaks, and obey his voice, and thy soul shall live: fear to offend Him,
or sin against Him; for the wages of sin is death.
Therefore prize his love in thy young and tender years;
and do thou read the Scriptures and Friends`' books,
and take heed unto what thou readest to obey it, as far as thou understandest;
and pray often unto the Lord, that He will give thee his knowledge,
and open thy understanding in the things of his kingdom.
Search thy heart often with the Light of Christ in thee; manifest,
and bring thy deeds to it, that they may be tried;
and examine thyself how the case stands betwixt the Lord and thee;
and if thou seest thyself wrong, humble thyself and be sorry, and turn unto Him,
and He will show thee mercy; and take heed for the time to come,
that thou run not into the same evil again.
Keep thy heart clean; watch against the evil in thyself, in that which shows it;
therein there is power, and thereby thou hast power to overcome all evil.

And dear child, mind not the pleasures of sin which are but for a moment,
and the end is misery; but keep under, and cross thy will and affection;
so thy mind will have no pleasure in the evil, but in good;
and thou wilt feel the immortal Seed springing up in thee,
which God`'s peace and love is to.

O Abigail! these are great and weighty things, not to be slighted!
Accompany thyself always with them that fear the Lord,
and fear and worship Him in spirit and truth,
and lead a holy and a blameless life and conversation; deny not them, but love them,
and suffer with them.
Take heed that thou follow not the hireling teachers, who preach for gain and lucre,
and abide not in Christ`'s doctrine; believe them not, heed them not,
they do people no good; but thou wilt see them thyself:
they have an outside show of Godliness sometimes, but deny the power of God,
and true holiness.
Remember I have told thee,
who have had perfect knowledge of them;. but be sure that
thou let nothing separate thy love from God and his people:
those are his people that keep his law, and obey Christ`'s voice, and lead a holy life;
and they were ever hated, and belied, and persecuted; and evil spoken of,
always by bad and evil loose people: these are God`'s people, and his love, and peace,
and blessing is with them.
Do thou grow as a natural branch, up among them, of the living Vine;
and continue all thy days in obedience unto God`'s will;
and thou wilt feel joy and love in thy heart, which above all things covet after,
and thou shalt attain to and obtain everlasting peace; which the Lord grant unto thee,
according to the riches of his mercy and love; which endure forever and ever, Amen.

And now Abigail, concerning thy well-being in this life,
this is my advice and counsel unto thee: love thy dear mother,
and ever obey her and honour her, and see thou grieve her not;
be not stubborn nor wilful, but submit unto her, and be as an obedient child unto her,
whose love and care hath been too great over thee and thy sisters;
which hath brought too much trouble upon herself.
Learn in thy youth to read and write a little, and sew and knit,
and all points of good labour that belong to a maid;
and flee idleness and sloth that nourish sin.
And as thou growest up in years, labour in the affairs of the country,
and beware of pride, and riotousness, and curiosity;
but be well content with such apparel as thy mother will permit thee,
and as thou mayst be a good example unto others in.
Be not wanton, nor wild, nor light; but temperate, moderate, and chaste,
and not forward in words nor speech; but swift to hear, slow to speak;
and do thou always live with thy mother, and be a help unto her,
and cherish her in her old age, and latter years; that she may be comforted in thee,
and her soul may bless thee: love thy sisters, and be always courteous to them,
and thy brother Thomas; encourage one another in good.

And Abigail, if thou live to be a woman of perfect years, keep thyself unspotted,
and let not thy mind out after sports and pastimes, the end of all these is sorrow;
neither of young men: if thou have a desire to marry, do not thou seek a husband,
but let a husband seek thee; and if thou live in God`'s fear, and an honest life,
and virtuous, they that fear God will seek unto thee;
let not thy affections out unto every one that proffers love, but be considerate;
and above all things choose one, if thou dost marry, that loves and fears the Lord:
whose conversation thou knowest, and manner and course of life well,
before thou givest consent.
Be discreet and wise; hide nothing from thy mother, and she will advise thee, no doubt,
for thy good; and if she be living, marry not without her consent.
And if thou join to a husband, be sure thou love him in thy heart,
and be obedient unto him, and honour him among all; so will his heart be more to thee,
and his love increase: grieve him not; but be gentle, and easily to be entreated,
and mind thy own business.
And if the Lord give thee children, bring them up in God`'s fear, and in good exercise,
and keep them in subjection unto thee,
and be an example of virtue and holiness unto them;
that the Lord`'s blessing thou mayst feel in youth, and in age, and all thy life long.

O Abigail! remember these things;
keep in mind these things! read often this writing over; get it copied over,
and lay up my words in thy heart, and do them; so wilt thou be happy in this life,
and in the life to come.
These things I give thee in charge to observe, as my Mind, and Will, and Counsel,
unalterable unto thee; in witness whereof I have set my hand.

Thy dear father,

Francis Howgill.

26th of the 5th month, 1666.
