== Chapter XII.

[.blurb]
=== An abridgement of an essay entitled "`Some of the Mysteries of God`'s Kingdom Declared.`" etc.

[.centered]
=== To The Reader.

In times past, in the night of ignorance, since the days of the apostles,
many groped in the dark as blind;
and out of thick darkness spoke darkly of the things of God, and of his kingdom;
and wrote about the things of God, and his kingdom,
and have fed the dark minds of many who are unconverted to God.
And seeing how many people are confused in their minds, and err in judgment,
and have lost the key of knowledge,
which should give an entrance into the mysteries of God`'s kingdom,
and open their hearts; therefore in compassion to such as are thirsting after the Lord,
and for the sake of those who have no place to rest in,
these things I have written as they were revealed to me, and in me, by his pure Spirit;
and if thou comest out of the world that lies in wickedness,
and waitest in the manifestation of the Spirit, thou wilt see them to be Truth.

I have not written to please men of corrupt minds,
who glory in words and outward appearances, and natural parts and sounds,
and have erred from the Life; but to the simple-hearted,
and for the strengthening of the weak.

That which thou seest in the following discourse which thou canst not close with,
let it alone, and judge nothing before the time in the wisdom that is earthly.
But by that of God in thee, I desire to be approved, and by nothing else.

I am thy friend in Truth, and wish good to all men.

[.signed-section-signature]
Francis Howgill.

[.old-style]
=== Section I. / Some of the Mysteries of God`'s Kingdom Declared.

The Lord God of the whole earth, who lives forever, even the God of Abraham,
the God of Isaac, and the God of Jacob; whose throne is established in righteousness,
who rides upon the heavens,
and shines forth in his eternal excellency from the firmament of his power,
is manifesting Himself as in the days of old,
and revealing his righteousness as in the years past;
and is pouring forth of his Spirit upon sons and daughters, according to his promise;
and they that believe,
come to be made partakers of the blessing of the everlasting hills.
The Lord, who appeared at Sinai, unto Moses his servant, in the bush;
who rose up from Mount Seir; and shined forth in his brightness from Mount Paran;
and cometh with ten thousands of his saints;
even He from whose right hand went a fiery law,
so that the people could not behold his glory,
hath now appeared in this the day of his power, and is appearing;
whose glory shall dazzle the eyes of the world,
whose brightness shall make dim all the world`'s glory, and stain its wisdom,
and shut it up in utter darkness: and the shadow of death shall flee away;
and all the haughty and lofty princes of this world shall be horribly afraid;
the beasts shall go into their dens when the day appears;
and the lambs of the everlasting fold shall come forth, and be fed in the fat valleys,
where the springs of life compass about all the banks;
and they shall rejoice in their Shepherd, and say:
"`The Lord is my Shepherd;`" which many at this time,
who have seen his wonders as in the days of old,
and his noble acts which the fathers have told of,
who are fallen asleep and are at rest in the Lord, do admire at, and say:
"`What hath God wrought?`"

God is now bringing many to see what those witnessed to be true;
and to have the same fulfilled in themselves: honour and praise unto Him forever,
who is the stay and strength of all His people forever.
The day of the Lord is dawned,
and the light hath appeared that manifesteth all things which are reprovable;
and the Day-star is arisen in the hearts of many.
This day when it appears, discovereth all things,
and maketh all things manifest to those to whom it appears;
as is declared by the Spirit of Truth in the Scriptures of Truth;
"`and every man`'s work shall be tried of what sort it is.`"
And this day hath appeared to many who have waited for it; praises to the Lord!
And now they see everything in its ground and rise:
and every tree and fruit is seen according to its kind, whether good or bad;
and every man`'s work is obvious to every one who is in the day,
and upon whom the morning of righteousness hath appeared,
and the Sun of Righteousness hath shined,
whereby that which is reprovable and condemnable in every one is seen,
and that also which is justifiable and unreprovable.

[.old-style]
=== Section II. / What the Day of the Lord Is, How It Is Seen, and to Whom It Hath Appeared.

God is a spirit, his day is spiritual, and is seen with a spiritual eye:
it is pure light, pure brightness,
the pure shining forth of the Lord in his glorious excellency;
holiness shedding itself abroad in its glory--purity
spreading itself in its immeasurable excellency;
and it can only be seen as it is in itself by the children of light, that are born of it.
The natural day receives its brightness from the sun;
the spiritual day receives its brightness from the Sun of Righteousness,
by whom it is brought forth, who causes it to spring from on high,
who is the Fountain of life, without whom nothing was or is made.
And as the natural day receives its clearness from the natural sun,
and is discerned by the natural eye of the natural man;
and all things natural are seen and discovered by and in the natural day,
and are obvious to him that hath his sight; even so from the Sun of Righteousness,
the Lord of glory, light, and purity, the day of God receives its brightness;
and it is discerned by the spiritual eye of the spiritual man,
who is in the image of the Father, brought forth in life from God the Father of life,
by Christ Jesus the Life of men, the Light of the world.
And this is the birth which is born from above, which is of the nature of the Father,
and of the Son, and of the day: and he only who is of this birth,
comes to behold this day, and discerns all things of the Father`'s kingdom by it,
and likewise the hidden things of dishonesty, and the works of darkness,
which are brought forth by the prince of darkness,
who is shut up in eternal and utter darkness; which is his residence,
and shall be the residence forever, of all the workers of iniquity that bear his image.

Yet some may say, This day has not appeared to any in this age.
But if a man that is naturally blind should say that there is no light in the day,
nor in the sun, because he sees none; is there therefore no light in the day,
nor in the sun?
And what if all things be alike unto him, day and night,
so that he can distinguish nothing,
does this therefore make void their seeing who do see with the natural eye,
both the sun and the day?
And if they who are spiritually blind, and are children of the night,
say they see nothing of the day of the Lord, or of the discovery of the things of God,
or of his glorious appearance, which many do witness,
doth this therefore make their sight void,
who have seen into the things of God`'s kingdom?
The unbelief of some doth not make the faith of them that do believe void: God forbid.

[.old-style]
=== Section III. / What the Day of the Lord Is, and What It Will Be to the Wicked.

Though the day of the Lord is pure light and brightness,
and mixeth not with the night which is of a contrary nature;
yet it is a day of blackness and gloominess, and a notable terrible day unto the wicked,
who hate its appearance, and hate the light, who are children of falsehood and of deceit;
whose deeds are evil: it makes them and their deeds manifest;
as it is written in a certain place: "`The morning is unto them as the shadow of death.`"
The appearance of the Lord affrights them; and they would run from it,
as a thief that diggeth through a wall, and breaketh open a house in the night,
when deep sleep is upon men, is afraid when the day appears that discovers his actions.
And the day of the Lord will steal upon such as live wantonly upon earth;
whose hearts are set to seek after wickedness, as for hid treasure;
and it will come upon them as upon a thief: and they being children of the night,
and bringing forth fruits of darkness, will have their portion in utter darkness;
thus shall the ungodly perish, and have their portion with hypocrites.
Think of this, all you railers, and revilers of the Light, and of the appearance of God,
and repent; for as with the wild ass that snuffs up the wind at her pleasure,
and they that seek her will not weary themselves with her,
yet the time cometh when she may be found and taken; even so all the ungodly,
though they may run as a wild ass, and traverse their way as a swift dromedary,
yet the day will come, when they will be overtaken in the midst of their security;
and they shall not escape.
And though the children, teachers, and professors of this world,
who profess the Scriptures, have prayed for the day of the Lord, yet when it comes,
it will be as a burning and devouring fire, and they will fall as stubble before it;
for whatsoever is reprovable is manifested by the day in which God appears:
and it shall appear, even to the wicked and to the ungodly.
So all you hirelings who preach for hire, and you people who love to have it so,
you shall not be hid; and all gainsayers of the Truth shall be found out,
and shall be convinced of their hard speeches, and ungodly deeds.
That which makes your deeds manifest is the day, and it will convince you;
for even the wicked shall see His appearance, although to condemnation, shame,
and contempt.

"`They shall look on Him whom they have pierced.`"
For even in the wicked God hath a witness which is pure, which checketh often,
though they regard it not, because the god of this world hath blinded their eyes;
but when Christ, the Light shall appear, He will make that to see in the wicked,
which the god of this world hath blinded; and they shall behold Him in dread;
and his pure appearance shall make them horribly afraid.
Although they would not see, they shall be made to see;
and they shall be made to hear that which they would not hear,
when God sounds his trumpet, to give warning to all, that the dead,
both small and great may arise, "`some unto everlasting life,
and some to shame and everlasting contempt.`"

[.old-style]
=== Section IV. / What the Day of the Lord Is to the Righteous, and How It Appears to Them, and Whether Any Are to Look for it Whilst in the Body.

The appearance of God, who is eternal life, in his day, in his immeasurable Light,
is a great joy and rejoicing to the righteous:
for He is unto his people an everlasting light; and in his light they come to see light.

He reveals the secret mysteries of his kingdom in
them who see his day appear in their hearts,
which makes all things manifest, even the secrets of the Lord, and his hidden treasure,
and his durable riches, which never canker nor rust, but are fresh,
and keep their pure image and impression.
By this Light all the righteous who have waited for God`'s appearance, come to see Him;
as it is written: "`Lo! this is our God, we have waited for Him, and He will save us:
this is the Lord; we have waited for him, we will be glad and rejoice in his salvation.`"
Is He indeed come that you have waited for?
Yea, come, "`and his reward is with Him;`" and they that see Him find contentment in Him,
and in his reward: and what is the reward?
joy, gladness, peace of conscience,
assurance of God`'s love sealed in the heart by the pure Spirit of the Lord,
the streams of Life flowing forth continually from the great deep,
which refresh and keep cool in the greatest extremity and heat of temptation;
and this is enjoyed by them that have waited and do wait for it;
even in the body they bear witness of Him and of his coming.
What was the witness of his disciples?
"`The Son of God is come and hath given us an understanding.`"
Of what?
of God, of his day, of his appearance, of his power, of his wisdom, of his kingdom,
of hope, of faith, of assurance, of peace, of joy, of comfort and consolation.
What! in this life?
Yea, a cloud of witnesses I might bring in former ages, and also in this age,
blessed be the Lord; but my witness that giveth me assurance,
is nearer me than all their witnesses, although they be all true.
Abraham, the father of the faithful, and of the righteous,
who believed in God and was accepted, saw Christ`'s day and was glad: that is, by faith;
yea, he and all that ever saw Christ`'s day, or the Father, saw Him by faith:
by faith they saw Him who is invisible:
"`Behold! God is my salvation.`" Isaiah 12:2.
What! dost thou enjoy it already?
Yea, He is become my salvation; and Simeon, who waited for the consolation of Israel,
said: "`Now lettest Thou thy servant depart in peace,
for mine eyes have seen thy salvation.`" Luke 2:30.
And this he said, who knew comfort and consolation:
"`As the sufferings of Christ abound in us, so our consolation aboundeth by Christ.`"
They were made partakers of his Divine nature,
and sat together in heavenly places in Christ Jesus: and they that are in Him,
and enjoy Him, who is the power of God, and the wisdom of God, know rest, and peace,
and salvation, both from guilt and acts of sin.
And the apostle, writing to the Hebrews,
said that "`When the Son of God had purged away our sins,`" (speaking of the atonement,)
"`He sat down on the right hand of the Majesty on high:`" he looked beyond sin,
even to Him who had purged away sin:
and this being purged from sin comes to be made manifest unto and in them that believe,
by the Spirit of Jesus, who is Christ the Lord, the arm that brings salvation,
who is the author of eternal salvation unto all them that believe:
He begins it and perfects it in his day, for He works in the day, as He himself said:
"`My Father worketh hitherto, and I work.`"
He destroys the work of the devil: this is his work in man,
which they that are come to his day feel and see,
even the handy-work of God in themselves: and his own works praise Him,
for they only can.
And they that are not come to the day, know not God`'s work in themselves:
and they who have not yet heeded that in themselves which manifests all things reprovable,
and which reproves,
are not yet come to know the appearance of the glimmering
of light or of the day in themselves,
which the saints witness in themselves, even all them that are sanctified.

[.old-style]
=== Section V. / Where the Day of the Lord Appears, How It Comes, and How It Is to Be Looked For.

They that gaze abroad cannot see the Lord`'s appearance, nor his day.
He that knows not wherein it consists, knows not how to look for it,
any more than the Jews, who were Scripture professors, and learned men,
knew wherein the kingdom of God consisted.
And no more do literal professors, whose faith is founded on the letter,
and upon that which is visible, comprehend what I say.
This day of the Lord, which is eternal brightness, appears in the heart;
and the dawning and breaking forth of it is to be waited for there:
and as it is witnessed it manifests evil, and brings it to light,
and declares against that which is contrary to its own nature.
Christ, the Covenant of light, the Gift of God, who is sent and anointed of God,
to preach and to proclaim the acceptable year of the Lord,
and the day of vengeance of our God, proclaims it in the heart;
for He comes not to bring peace but a sword; and his sword is the sword of the Spirit:
it is that which divides and discerns the thoughts and intents of the heart,
and discovers its desperate wickedness.
In earthly hearts where He finds no faith, He kindles a fire and executes his vengeance;
and his day unto such is a day of great perplexity: their spirits come to be wounded;
their hearts become faint, and sorrow fills them, and trouble is known;
and in this state He finds all who are unconverted; without faith; without hope;
and therefore He takes away peace.
Many have talked of the day of the Lord; but when it appeared they would not abide it;
but would rather run to anything,
than see the Lord of life appear to execute vengeance upon his enemies.

They who have not yet seen this day of the Lord`'s vengeance in themselves,
have never seen the day of salvation.
The prophet cried out: "`Who may abide the day of His coming,
and who shall stand when He appeareth?`"
And many have been eye-witnesses of the dreadful day of the Lord,
which hath appeared in them, wherein all peace hath been hid from their eyes:
and all that ever came to see that day of joy and gladness,
first knew the terror and the terrible day of the Lord in themselves;
therefore said the apostle: "`We, knowing the terror of the Lord, persuade men.`"
Now this day of the Lord cometh not with observation, "`Lo here,
or there;`" thus the Pharisees looked that the kingdom of heaven should come,
when Christ told them it was within them: and I say,
if ever any do behold the bright shining forth of Eternal Life,
they must wait in that which is of God,
through which He will manifest his day and power in them;
and as they keep their attention to that which manifests evil unto them,
and shows them good, they will see how it appears;
even as the lightning shineth from the east unto the west,
so is the coming of the day of the Lord; and the eye which is spiritual sees it.
The power and the glory of the Lord
are seen in the day which is pure and spiritual in the heart;
and the eye which is pure discovers when it comes, where it comes, and how it comes;
whilst it is hid from the vulture`'s eye, and from the eyes which cannot cease from sin.

Now the day of the Lord cometh not where the carnal mind might imagine,
nor when man will; neither according to the carnal desire of the carnal heart;
neither according to the evil eye that looks out, can it be seen.

And as the day of the Lord is a mystery,
the Spirit of the Lord is the only discoverer of it; for none can know the things of God,
but by the Spirit of God.
And the day of the Lord, even his bright shining forth in the heart of man,
is one of the glorious things of God,
which only the Spirit of God doth give the knowledge of to man, and in man.
The further men draw from the Light, the darker their hearts become;
and their understandings being closed up, they cannot behold the Lord, neither his glory,
which is revealed only by God`'s Holy Spirit; which Spirit is near man,
though he see it not.

[.old-style]
=== Section VI. / What the Spirit of the Lord, Which Discovers the Things of God Is, and How It Comes to Be Received.

The Spirit of the Lord is one with the Father, and the Son; (the Father, Word,
and Spirit, are one;) it is life, purity, holiness, power, and strength;
and neither mixes with, nor joins to any thing, but that which is of its own nature.
It is an everlasting, living, active power, which changes not,
but keeps its holiness forever, and is unsearchable, unfathomable, and undeclarable,
except as it makes itself out to them that believe, and opens itself,
and sheds itself abroad in them that wait upon it: it is revealed in its own purity,
manifest in its own power, received in its own light, and felt in its own virtue:
the Living Father himself is manifested by it, and appears in his power, majesty,
and excellency, through it to man, to the righteous and unrighteous:
it is that which searcheth the heart of man, and sees through all things,
and makes manifest all things, even the hidden things of God,
and also the secret works of darkness, and reproves for all iniquity,
and convinces every man; and as the creature joins to it,
it arises and shines forth more clearly, making itself known in its power and operation,
checking, reproving, judging, and condemning actions which are past,
and bringing them to remembrance.
Now as there is a waiting upon the pure appearance of it, the mind being still and quiet,
the creature comes to feel and sensibly to know his own condition;
that he is alive to other things, and not to God, nor the things of his kingdom;
and that he is in the fall and transgression:
and as this operation of the Spirit is loved and obeyed, it draws towards itself,
and converts the heart to the Lord out of unholiness, from under the dark power;
and it brings that under, and so arises in its own strength.
It is the discoverer of the mind of the Lord to the sons of men;
for the Father by it makes known his mind to and in the creature,
and discovers to them the things that are eternal in their true nature and property;
which things are not seen by the natural eye,
neither received by the spirit of the world; which never receives the things of God,
nor the testimony of those who are in the life.
Now all who receive this Spirit of Truth, must wait in that which is pure,
unto which it joins; for it joins not to the corrupt man,
nor to the will of the creature; but though it joins not to these, yet it is near,
even to the natural man, the shining forth of its brightness,
making evil manifest to be evil.
Thus far it hath appeared to all men; but while the heart of man is taken up with sin,
and joined to that which the Light reproves, he has not received the Spirit,
nor become a possessor of it; but it stands as at a distance off him,
showing him his works of darkness, and letting him see to whom he is joined.
Yet so far as a man denies himself,
in acting or joining himself to that which the manifestation
of God`'s Spirit in him reproves,
so he comes, in some measure, to join to the Holy Spirit, and to receive it;
and though working but weakly in him,
it is yet purging out those things which it lets him see to be evil.
Thus, in some measure, he feels in himself what to wait upon, where, and in what to wait;
which is in that which gives every one a feeling of his own condition within,
and opens his understanding.

[.old-style]
=== Section VII. / How the Spirit of Truth Operates in Those Who Are Convinced, and Yet Have Not Obeyed.

Though God, has appeared by the manifestation of his Spirit to all,
yet all have not received his Spirit: the evil-doer has not received it;
"`The morning is to him as the shadow of death:`"
he is still dead in trespasses and sins,
and is that darkness in which the Light shines, which convinces him;
for the Light shines in darkness.
This may convince all who say that everyone is not enlightened,
and that the Spirit of God has not appeared to all.
Good men have it: it is near to bad men, who are in darkness, and are darkness,
as the Ephesians were in their unconverted state, Eph. 5:8, who,
by turning to the Spirit`'s manifestation, came to be made light in the Lord,
who hath not left himself without a witness:
but those who have not God`'s witness for theirs, have no faith in God,
nor assurance of salvation: for that which should bring assurance of salvation,
assures their condemnation, and reveals sorrow to them:
and though for a moment it may not be heard, or, through being disobeyed,
may seem as dead; yet if the mind be still, and a man be sober and calm,
and mind what he is doing, it appears again to him kindling his torment.
And though a man may take up and perform something which is called religious,
and some carnal outward ordinances, and pray in words,
and read and talk of the Scriptures, and therein content himself for a time;
yet the witness of God`'s Holy Spirit shows him his hypocrisy,
and that he seeks a cover to shelter himself under in his disobedience,
in order to be at ease in the flesh; which is all in vain, for there is no peace within;
but the measure of God`'s Spirit still shows him,
that he serves sin and follows his own will,
and in this will brings forth a worship which is but will worship.
Nay, if such a man should practice all those things which
others who were in the Life performed and were accepted;
yet this would not satisfy God any more than if he blessed an idol, or kissed Baal.
And though a man should sin so far against the Light of Christ in his own conscience,
and, in his rebellious will, persist in following the imaginations of his own heart,
as to quench the Spirit and its motions, and become senseless to the things of God,
and hardened in heart;
so that the Light may be unto him as though there were no such thing; nevertheless,
woe will be unto such; for though the Spirit strive long, yet being still disobeyed,
the longsuffering of God comes to an end:
the wrath of God will be kindled against him as a fire,
which shall burn to the lowest hell;
into which all the rebellious and stiff-necked shall be cast,
and have their portion forever; because they have pleasure in unrighteousness,
and have sold themselves to do wickedly, crucifying the appearance of God in themselves;
which appearance, lives in the Fountain of Life;
and though it be crucified by those who are out of the Life,
nevertheless lives forever in itself to be their condemnation eternally.

[.old-style]
=== Section VIII. / How the Spirit of the Father Works in Those Who Are Turned to It, and Have Taken Heed to Its Manifestations, and Are, in Some Measure, Partakers of Its Power.

"`There are diversities of gifts, but the same Spirit;
there are differences of administrations, but the same Lord;
and there are diversities of operations, but the same God who worketh all in all.`"
Now the Spirit of Truth operates not only to convince
and detect him that transgresses against its appearance,
and to manifest evil which has been committed; but also, being turned to and waited in,
it shows man when temptations and motions to sin arise;
and as the creature is still and waits in that which manifests,
and keeps his mind singly to it, it sheds abroad its power,
and subdues those lusts which arise, and condemns the ground from whence they arise,
and draws the mind after itself.
It works secretly,
and breathes forth its pure Life in him that waits in patience and stillness,
not attending to the vain thoughts and imaginations that arise in his heart;
but to the manifestation of the Spirit, which extinguishes vain desires, and creates,
within, a hunger after being made a partaker of its purity, and of its nature; for God,
through the operation of the Eternal Spirit,
sends forth his power which changes the heart,
and divides betwixt a man and those lovers to which he hath joined;
and makes a separation within;
and carries him further from those things which the Spirit reproves,
and leads him nearer unto God.
Thus they that believe in the measure of God`'s Spirit,
come to feel what repentance from dead works is.

There is nothing passes through the mind of him who
quietly waits upon the Spirit in singleness of heart,
but what he discerns; yet after the Spirit of Truth and its living testimony is,
in some things, and in some measure felt,
it may be a long time before there may be a clear discernment in the understanding,
so that one can clearly discern its movings from all false motions,
and high imaginations;
and hence it is that hasty and forward minds follow vain motions which deceive them;
and then they question all that the Spirit had made manifest to them before,
which brings a veil over them;
and the enemy lodges in the darkness which is come upon them:
and as soon as any hearken to his voice, he presents motions for them to obey,
and they are deceived by him.
Therefore, all are to be watchful,
that they may sensibly feel the difference between
the pure motions and drawings of the Spirit,
and the vain thoughts that arise out of the earthly heart;
and when anything arises which the Light does not bear witness to,
it is not to be followed nor heeded; but a quiet, still waiting is to be observed,
that things may be made clear to the understanding.
For want of this many have run out, and have acted forwardly in their own wills,
and have brought forth Satan`'s work;
and so have lost the true sense of that which should have guided their minds:
such have followed the spirit of error,
and have caused the pure Spirit of the Lord to be evil spoken of.

But as there is a keeping back, and quietly waiting,
and a keeping out of willing or running, and haste,
the Spirit arises purely and stilly in the heart,
and gives perfect evidence and full testimony of itself;
so that there need be no doubting nor questioning of its motion;
for it shows forth itself with full assurance of its own will:
and when this is clearly seen and felt, let all reasoning be kept under,
and all questioning kept out, and give not way to temptation;
and that which moves of the Lord of life will carry through,
by its own operation and power, to accomplish the will of God: and so, being obedient,
peace will be received, and strength will be renewed;
for as any are brought to submit to the Will of God, and to obey,
by virtue of his own power, that which is contrary to God`'s Spirit in them,
loses its strength; but by disobedience to the pure motion of God`'s Holy Spirit,
after it is known, the enemy is strengthened, and that which is of the flesh nourished;
and the Spirit which would give strength, if submitted to, is quenched;
yet the Spirit in itself never loseth its purity, but will bear its pure witness.

Thus the diversity of the operation of the Spirit is known; and as it is hearkened unto,
obeyed, loved, and believed in, it puts forth its pure power, and gives strength,
and seals peace to the obedient; but disobeyed and resisted, it judges, reproves,
and seals condemnation to the disobedient.
It causes the good ground to bring forth fruit unto God;
and in the cursed ground it kindles a fire that shall not be quenched; but,
as there is a submission to its pure operation,
it burns up and destroys that which hinders the growth of the seed;
and it purges the hearts of them that have confidence in it, from all filthiness,
both of flesh and spirit; and works the creature into its own frame and nature;
and fashions and moulds all that are in the faith, into the image of the Father;
and so the Father`'s love comes to be shed abroad in their hearts:
and as wrath and condemnation were revealed through the Spirit,
so now the peace of God is enjoyed, and his consolation shed abroad largely by it;
in which there is pure rejoicing forever.

[.old-style]
=== Section IX. / To Whom the Spirit Bears Witness and Seals Assurance of the Father`'s Love; and of Justification with God

None have the witness of God`'s Spirit, bearing witness to them and in them,
who have not believed in Christ "`the true Light,
that lighteth every man that cometh into the world,`" whose words are spirit and life;
and by whom the new creature is formed in them that believe,
and who makes his power manifest unto such:
for all power in heaven and in earth is committed unto him, who is the Light of men;
and nothing was created without Him, neither is any turned from sin but by Him;
without Him is death--in Him is Life.
And none but those that are born of the Light,
can have the Spirit of Christ to bear witness unto them;
for only they that are born of the Spirit, and walk after the Spirit,
are justified by the Spirit of the Lord;
for the assurance of his love is not made manifest to his enemies,
but unto them that are born in his image--in his own likeness and nature;
to the Holy Seed which is heir of the promise,
which knows the living hope that purifies the heart,
and brings the answer of a good conscience;
to them that witness the washing of regeneration,
having known in themselves the clean water poured forth upon them,
which hath taken away the stains and defilements; for where these are not washed out,
and where the heart is not cleansed, and where that is not believed in,
in which God`'s all-sufficiency is felt, and his power made manifest,
there the assurance of the Father`'s love in the heart cannot be;
neither does his Spirit assure the justification of such; but on the contrary,
where sin remains unsubdued,
the Spirit of the Father condemns the sin and the creature which is joined to it,
and becomes one with it.
For no sin is brought forth, but there is an assenting to the instigation of the devil:
for when a temptation arises, either within or without,
and there is a resisting and a striving against it for a time,
yet if the heart be not kept close to the Spirit,
the enemy will enter and captivate the understanding;
then there will be an agreeing with, and a joining to the adversary.
And the Spirit will pronounce sentence of condemnation
upon him who joins to the wicked one.
And he, who has consented to drink his cup,
must drink the cup of the indignation of the Lord, and bear the stroke of Divine justice,
and lie in patience under it, till that be cut down which hath joined in with the deceit;
before there can be remission of transgression,
or the creature justified in the sight of God.
For sin is not blotted out of the book of God`'s remembrance till it be repented of,
and turned from; neither doth the creature stand clear in the sight of God,
when God condemns in righteous judgment,
which the Light in every one`'s conscience shall answer to.

Now, "`whosoever is born of God doth not commit sin;
for his Seed remaineth in him,`" which is Life;
and as the creature joins to that Seed which is heir of the kingdom,
and of the crown immortal, he comes to be made partaker of its virtue and operation;
which Seed is Christ, to whom all power is committed; and who, by his power,
as it is believed in, limits the seed of the serpent,
and weakens his strength in the creature,
and disannuls the covenant which he has made with death.
And as the creature comes to be delivered from corruption, and the new man comes to live,
the new creature, which is born of God,
comes to be framed and fashioned in the image of the Father;
and the Father`'s love is manifested to him and in him,
and he hath the assurance in himself.
He that is begotten of the Father in Christ the Seed, through the Spirit,
he and he alone, comes to feel the Father`'s love made manifest in him,
and is justified in the sight of the Father;
and hath His assurance and evidence near him and in him.
And when the adversary comes to tempt and assault,
and would raise up doubts in the mind of him that hath this evidence,
it is near to assure him that he is in the love of God.

Blessed and happy are all they that have waited for, and have felt these things,
and who are witnesses of them; for flesh and blood hath not revealed them.

Now let every man that reads this prove himself and try himself,
whether he be in the faith or not,
and whether he have the evidence that he is born of the Spirit or not,
and knows a birth that sins not;
because the Seed remains in him who is kept by the Power,
that the evil one toucheth him not;
and so he is kept alive unto Him who hath brought him to life,
and hath given him to drink of the cup of salvation; which nourisheth up,
unto eternal life, all those who continue in the faith.

[.old-style]
=== Section X. / What the Free Grace of God Is; How Far It Is a Sufficient Teacher; to Whom It Has Appeared, and Where All Are to Wait to Receive It.

The Grace of God is his free gift; it is the appearance of Christ;
it is that through which God makes known his will, and by which He teaches us.
He reveals his saving health through it to those who are taught by it:
and those who are taught by it, are built up in the Truth through it,
and become a habitation for God.
No man can do anything to purchase it; none need say, where can I get it,
or how may I know its teachings?
It is near all, it is in all, it has appeared to all;
it shows ungodliness in the heart of man by its brightness; yea,
it shows all men the motions to sin; it draws the hearts of men from them;
it shows the lusts of the heart and mind, the lust of the eye, and the pride of life;
it never joins to sin: nothing can alter its purity or property;
and though some that turned to it, have again turned from it,
and may turn in themselves to wantonness;
yet it still keeps its purity and reproves their wantonness.

Many have been talkers of it in this professing age,
who have neither known of what they spoke,
nor have informed the minds of men where it was to be waited for,
nor how it might be known, nor how, nor what the operation of it was; but have cried up,
in their own imaginations: "`We are justified by His free grace from all sin, past,
present, and to come;`" and, in this conceit,
thousands have been led into the pit of darkness,
imagining that they were justified by the free grace of Christ,
whilst they were out of the fear of God, which it would have taught them;
and whilst they heeded not this grace, but got into conceit, carelessness,
and presumption;
and so pretended justification while they were the
servants of sin and bond-slaves to corruption.
All you that have been preaching free grace in words;
and now when God has given them that have waited upon Him,
an understanding to declare the thing itself, that you have spoken of,
which you now cry is not a sufficient teacher, let me ask you a question:
Is that which teacheth to deny ungodliness not a sufficient Teacher?
If it be not, why did the apostles commend the believers to the word of His grace,
which was able to save their souls? Acts 20:32.
James 1:21. Is not that which is
able to save the soul a sufficient Teacher?

Seeing then that God`'s free grace, which is his pure appearance,
has thus manifested itself; or that God through it shows sin, and leads from it;
and that God hath so loved the world as that He sent his Son into the world,
who was and is the Light of the world,
and hath shed abroad his grace and made it appear to all; and all that wait upon it,
come to be taught by it and feel its assurance, therefore all are without excuse.
Wait therefore in that which has appeared in thee:
for that which shows the lust and thoughts and motions to sin is God`'s gift,
God`'s grace, and is sufficient; and though all men in the world should say it is not,
yet this would not make thy faith void, neither mine who have received it;
because we have the witness of our faith in ourselves,
which gives pure and perfect feeling of the operation of the Spirit of the Lord;
which saves all them that believe in it out of sin, and gives them dominion over it.

[.old-style]
=== Section XI. / Whether There Be a Distinction in Grace or Not--It Is Not Separate From Christ--An Exhortation to Those Who Long For His Appearing, etc.

Peoples`' minds have been confounded by distinctions made
by those whose wisdom is below the wisdom of God;
and who say that there is a twofold grace.
First, that which they call common, which they say has appeared to all.
And Secondly, That which they call special and saving,
which they say has appeared to the saints.

By giving heed to these distinctions, many years ago,
I went from the appearance of the Light in myself,
to hearken to something at a distance from me;
and not heeding that which was at home and near,
because it was called common and insufficient, I lost myself and my guide;
yet after many years profession,
I was made to go back again to that which was called common and insufficient,
before I found favour with the Lord, or felt his living power again.

[.numbered-group]
====

[.numbered]
_The First_ they ground upon the letter where it is said:
"`He causeth the sun to rise on the evil and on the good;
and sendeth rain on the just and on the unjust`" and "`In Him we live and move
and have our being;`" and they say by this we discover gross sins.

[.numbered]
_The Second,_ which they call special, they say,
is that by which the saints are saved and established in righteousness,
and receive remission of sins.

====

Now He who causeth the sun to rise, and the rain to fall;
and giveth health and strength to all things in the outward and visible creation,
who discovers to man his gross sins, is the same who is the Life of the soul,
who sanctifies, purifies and saves those who believe.
The same Power which upholds the natural man, upholds the spiritual man.
The same Power (I do not say the same measure of it) by
which all things visible subsist in their stations,
preserves all that believe and are quickened by Him, who is the Power of God.
The same Power which discovers the dark places of the horrible pit,
leads all that believe in it unto the land of the living.
The same Grace which discovers open sins, discovers also secret and hidden ones;
yet it shines less in those who are in unbelief,
because the veil is thick and the clouds are many upon them:
but in them that believe in this Grace, it rends the veil, and scatters the clouds,
and breaks forth in its brightness.

That this grace has in some measure appeared to all men,
is a truth which shall be witnessed to by the whole
earth in the day of the Lord`'s appearing,
and is now witnessed to by all the children of Light, who believe;
therefore all are left without excuse.
And herein is the wonderful love of God to all mankind made manifest,
and all that turn to his grace will see He hath long waited to be gracious,
that all mankind might be made partakers of his bounty, love, mercy,
favour and free grace.
Therefore, in dear love unto all upon the face of the earth where this may come,
I write this, that they also may be partakers with me of the free love and grace of God,
by which I am saved, and know the walls which are salvation,
and the gates which are praise; which the saints are entered in at,
and are compassed about with.

When I speak of the sufficiency of Grace, and say that it is a sufficient Teacher,
I do not speak of it as distinct from Christ;^
footnote:[Nor as distinct from the Spirit, see Sect.
vi. vii.
_Editor._]
nor as of a thing separate from the Power of God,
but as one with it and with Him from whence it comes: for as He is salvation itself,
so the grace of God by which He manifests Himself, and his salvation,
to them that believe, are of the same nature.
For where the appearance and presence of Christ are manifest,
there is his power manifest, either to condemnation or salvation.
And though his appearance is one in itself,
yet to them that have marred his countenance and pierced Him,
his presence always has been, and will be very dreadful and terrible;
but to them that have longed for Him, and believe in Him, and have continued with Him,
and suffered with Him; his appearance will be sweet and glorious.

O! that all who long after Him, may wait for Him in patience,
in that wherein He will appear; and they shall see Him,
the sight of whom will be a recompence for all their longing, thirsting, desiring,
and waiting; which will be taken away when He appears, who maketh glad the heart;
who lifteth up the Light of his countenance,
and maketh whole those whose hearts have been broken for Him.
Therefore, all wait, and think not the time long; keep your minds to his grace,
which is his appearance, and you will feel and see Him, and be satisfied,
and enabled to say: "`This is our God; we have waited for Him, and He will save us.
This is the Lord; we have waited for Him, we will be glad and rejoice in his salvation.`"

But, though God in his everlasting love to the sons of men, has followed them,
and called to them to return; yet that nature which is in man,
which has transgressed against the Life, always resists the drawing of the Lord;
and is not subject to the law of God,
nor to the grace of God which teacheth to deny all ungodliness and worldly lusts,
that have compassed the creature about as a thick cloud,
till there be a listening to that which showeth ungodliness, which has power in itself;
for none have power, neither dominion, of themselves,
over that which leads into transgression.
Therefore, though God hath appeared in his pure and perfect grace unto all men,
yet all men have not received grace:
for though the Lord offers his gift that the creature may receive it,
and partake of its virtue and operation;
yet while that has preeminence in man which is contrary to grace,
that will never receive it; because grace is contrary to that which opposes,
which it mortifies, and takes its life away, and slays the enmity.
Therefore all must be still and quiet, that they may feel that which receiveth grace,
raised above the corruptible thoughts and desires of the carnal mind.

Many who talk of free grace, put no difference betwixt the precious and the vile;
but set people upon doing and working, who are in the enmity, and curse, and in death;
and thus they have brought forth dead works, notwithstanding all their performances.
They being dead to the life of God, another acts in them;
even he who hath the power of death, which is the devil.
And not knowing that which is precious in themselves,
they cannot minister unto that which is precious in others, but are ministers of death.

Now though all have not received grace, so as to be saved from the committing of sin,
the fault is not in God; neither is the fault in grace,
"`which hath appeared to all men;`" neither is it because of its imbecility and weakness;
but because it is not hearkened unto, and waited on and believed in, received and obeyed.
For this is an eternal truth, which shall stand forever:
The least measure of the grace of God has power in itself,
to save man from committing that evil or sin, which it shows him; and as it is received,
the power is more and more manifested,
wherein all that believe come to be preserved out of evil.

There is no variation or change in the gift of God,
but as it worketh upon different objects: faith and unbelief are two different things,
as light and darkness are different: and therefore,
the word of God`'s grace is the savour of life unto life, to them that believe;
and is the savour of death unto death, to them that are in unbelief;
who indeed are dead while they live.
Here is the same grace but difference of operation.
The Lord killeth and maketh alive; yet it is the same Lord.
The Spirit convinceth of sin, and reproveth for sin; and also consoles and comforts:
here is diversity of operations yet the same Spirit.

And though the careless and those who believe not, say:
"`We feel no power nor sufficiency in grace to save us from sin;`" this makes
not void the confidence of those who have received it and know its power,
which hath given them power to do the will of God.
Though unbelievers, who are in the alienation, say: "`there is no beauty,
neither form nor comeliness, in Christ;`" this makes not his glory void,
who is the express image of the Father, full of grace and truth.
The disciples, who were in the faith saw his glory, and bore record of Him;
and the Pharisees, who were in unbelief, said: "`He hath a devil.`"

Paul, who was a minister of the word of reconciliation,
was buffetted by the messenger of Satan; and he prayed God thrice for this cause;
and this answer was given him: "`My grace is sufficient for thee.`"
So this is evident to all understandings, which are opened by the Lord;
that that which showed him the buffetings of Satan`'s messenger,
was sufficient to preserve him.
And so it is, for all who keep singly to it,
sufficient to show ungodliness by its purity; and to lead from worldly lusts,
and to teach the will of God, and to live godly in this present world by its power.
This testimony I bear to it, and of it; even of what I have felt, tasted,
and handled of its sufficiency and virtue, and of the power of its operation,
for the information of them that thirst after the Lord;
and for the opposition of the gainsayers and opposers of it;
which testimony I commend to that of God in every man;
and that will bear me witness in the day of God, when all hearts shall be opened,
and all falsehood and truth be made manifest.

[.old-style]
=== Section XII. / A Word To The Wise Men Of This World, Who Are Glorying In The Sound Of Words, And Are Worshiping Outward Appearances--And To All Literal Professors Who Think To Search Into The Deep Things Of God--And To Worship God Aright By Their Natural Wisdom, Learning, Parts And Study

God is shedding abroad his power and glory,
and making it to flow forth to his little ones,
by which you are all weighed--all your parts, tongues, languages, interpretations,
significations, and wisdom; which are but natural.
For although there are many languages, and each has an interpretation, and signification,
they are all too short to declare the life, the immeasurable being of eternal life:
your tongues, and the signification of all tongues, cannot know the mind of the Spirit;
neither can you know the origin of eternal salvation by all these.
But not knowing the signification of the living, Eternal Spirit in yourselves,
you invent, study, devise, form, and frame things in your carnal minds;
and have filled the world with your dark, muddy conceptions;
and have led people from seeking after the wisdom of the living God, which is from above;
which was before your tongues and languages were;
and they have sucked in your conceptions, and distinctions, and your devised fables,
and your imagined worship;
so that many have lost the sense of anything of God in themselves to guide them.
It is lamentable to see how people are gone out of the pure simplicity which is in Christ,
into subtlety and deceit; and have become full of that,
which must be all poured out as water,
before they come to the least measure of God`'s true and saving knowledge.
O! a dreadful day is come upon many; and it lingers not,
but will come quickly as a thief upon you, who have taken away the key of knowledge,
and given people that which will not open: you, and them that follow you,
will be shut out together as fools, though you count yourselves wise;
your wisdom will perish, and your honour will be laid in the dust.

And you, literal professors, who have got the Scripture into your heads,
and into your carnal minds to talk of; you have taken up,
and are exalting a visible shadowy practice, and you neglect the Life,
and are making idols of those things which were but
a figure and representation in their purest time;
you, like the Pharisees, are limiting the Lord;
that if He will not appear to you in those things which
you have prescribed unto yourselves from the letter,
you cannot receive Him.
May the Lord open your understandings, that you may see yourselves; and how frothy, vain,
and light you are, one with the world in the very ground; pretending liberty in Christ,
when you may see that you are servants to corruption, and to many noisome lusts.

Again, what are all outward appearances, but as a curtain, or veil, or shadow,
in respect to Christ, God`'s righteousness within;
but you are filled so full of your apprehensions of His righteousness at a distance,
that you have forgotten all at home:
his righteousness will not be a cloak for your self-righteousness, and unrighteousness.
And if Christ be not formed in you,
and do not live in you and act in you and work his work in you,
you are in self-righteousness.
A talk of imputation will not save you, while you are not in that capacity, nature,
and faith, unto which his righteousness is imputed.
Do you not see your land grow barren, your profession dry, and your worship dead?
When will ye seek after that which endures forever?
I pity you who have had breathings after God,
and have set down at ease in that which is not eternal.
Be warned, return home, consider, see what corruption you now have power over,
which once had power over you.
Do you rest in that faith that you shall never be cleansed here?
It is rather unbelief; it is not the faith of God`'s elect, by which they are sanctified,
and overcome the wicked one in themselves, by the power of Christ;
and are redeemed from the bondage of corruption to serve Him in the Spirit of God,
in which the sons are made free from sin, from the act and guilt,
and become the temples of the Holy Ghost. Consider how far you are from this,
who are yet temples of uncleanness.
Repent, and mind that which empties you of your thoughts and conceitedness,
that you may know poverty of spirit: that the kingdom of God may come unto you,
and be yours in possession.

This is the true state of many of you; own it and repent;
that if it be possible you may find a door of mercy opened unto you;
and that you may enter in thereat.
For it is not setting up and conforming to a visible practice without, that will justify;
while that which is in the transgression,
and has disobeyed the Light in the conscience is a head in you:
that will not recommend you to God; neither can you have any access to God,
or acceptance with Him in that state:
you must come to the Rock before you know any thing that will endure;
"`which Rock is Christ.`"
This you must all come to before you can know God`'s salvation,
or redemption in yourselves, or have the witness of God`'s Holy Spirit;
without which there is neither true zeal, nor evidence,
nor assurance of the love of God enjoyed.

The time of restoration is come, and many are restored again into God`'s covenant;
and are delivered out of the jaws of death; and feel Him who is the healer of breaches,
to be the restorer of desolate places.
But all must come to see the place made desolate, wherein the wild nature lodges,
before they come to have a share in the restoration.
Come then off these barren mountains where you are feeding, to Christ the Life of men,
who hath enlightened you, that you may feel His mind in yourselves;
or you will still err for lack of knowledge, and perish for want of understanding,
and so lay down your heads in sorrow.

[.old-style]
=== Section XIII. / The Kingdom of God And Christ Declared.

The Lord hath prepared his throne in the heavens; and his kingdom ruleth over all.
His dominion, is an everlasting dominion; He is a spirit; his kingdom is spiritual:
He is immortal; his kingdom is so: He is Light; his dwelling-place is so:
therein is no uncleanness, nor ever shall be: it is eternally glorious;
a quiet habitation: it is unsearchable and undeclarable;
in it all who believe come to enjoy Him, who is the fulness of all things;
whether visible or invisible; who is, eternally, blessedness itself;
who makes all that believe in Him to partake of his kingdom, grace, power, dignity,
dominion, and celestial glory.
But these things are hid from the world; from them that are not redeemed from the earth.

When Christ taught them that followed Him,
He exhorted them to "`Seek first the kingdom of God
and his righteousness,`" Matt. 6:33. even,
whilst they were in the body; and He said to the Pharisees:
"`The kingdom of God is within you.`"
Some may say, Need we seek that which is in us?
Yea, It is like treasure hid in a field:
it is like a grain of mustard seed among many great seeds, which is not easily found:
it is like a piece of silver lost in the house among much rubbish;
till that be swept away it will not be found: all must dig deep, search narrowly,
and sweep clean before they find it: for although Christ said to the Pharisees:
"`The kingdom of God is within you,`" He did not say that they were possessors of it:
but to the disciples whom He taught to pray in faith, "`Thy kingdom come,`" He said:
"`Blessed be ye poor for yours is the kingdom of God.`" Luke 6:22.
They had seen it and were possessors of it.
And He also said unto them: "`There be some of them that stand here,
which shall not taste of death, till they have seen the kingdom of God come with power.`" Mark 9:1.
And his words were fulfilled; and they declared what they had felt, and said:
"`The kingdom of God is not in word but in power.`"
And Paul, writing to the Romans, who were made partakers of the same power and kingdom,
said: "`The kingdom of God is not meat and drink, but righteousness, and peace, and joy,
in the Holy Ghost.`" Rom. 16:17.
And to the Colossians, who had waited for and believed in it, he said:
"`The Father hath made us meet to be partakers of the inheritance of the saints in Light,
who hath delivered us from the power of darkness,
and hath translated us into the kingdom of his dear Son.`"
And to the Hebrews He saith: "`We who have believed do enter into rest.`"
And these things were witnessed whilst in the body, and felt within by the seed immortal,
by them that witnessed the birth immortal to live in them.
And all that ever come to see the kingdom of God, which is spiritual,
must wait in the Spirit, that so God and his kingdom, and the things of his kingdom,
may be felt, and seen, and enjoyed, which is glorious.

The saints looked not after any other glory, but that which stood in eternal life.
And the city they sought after, was that which God is the maker and builder of;
and they looked for and waited to receive of his power,
in which the kingdom standeth in this life;
and to know and enjoy his eternal dominion and authority:
I do not say the full weight of glory,
which is that which all his saints in measure witness,
and in due time come to enjoy through faith.
For by faith they come to see Him who is invisible;
and the things of his kingdom which is invisible, spiritual, and eternal.

The kingdom of God is come nigh unto many, and his power;
and the salvation of Christ is seen by many.
Honour and praise unto Him everlastingly, who is the only potentate;
that puts all authority under his feet, that God may be all in all!
But every one must come to feel the kingdom first in Himself, which is as a little grain;
and believe in it before he can know wherein it consists.
And after it is in some measure known;
this is still far short of the eternal weight of glory:
yet he that believes is entered into rest, and made partaker of the heavenly gift, power,
and grace, which is glorious, and witnesses a heavenly place in Christ Jesus;
but there nevertheless remain many enemies to be subdued,
and much of the heavenly habitation, which they see not, to be revealed;
as there is an abiding in the power of God, in which the kingdom stands.
For Israel, the true type, after they had passed over Jordan,
and had taken Jericho and Ai, and had made an entrance into the land,
had many enemies remaining to be subdued;
and there was much of the land that they were not made possessors of for long after:
even so, after there is an entrance made into the true rest,
and some possession of it enjoyed, there are yet many enemies to be subdued;
and much more of the heavenly inheritance to be enjoyed by them that stand in the Power,
which gives dominion over sin and the devil, hell and the grave;
and these come to be made partakers of God, and receive, in due time, the crown immortal.

And so to conclude, I say unto all who are longing after God,
and waiting to feel his power:
Keep in your minds to the pure measure of God`'s Holy Spirit,
and therein wait to see his kingdom, and his dominion and to be made partakers of it,
and of Him, who is glorified with the Father, in his kingdom,
with the glory He had with the Father before the world began:
for whosoever comes to enjoy the kingdom of glory, which fades not away,
is eternally happy.
