== Chapter XIV.

[.blurb]
Extracts from Francis Howgill`'s Epistles

[.old-style]
=== Section I. / An Epistle To Friends In Ireland.

Unto all you who believed the report, and who received the testimony,
and unto whom the word of the Lord came in power, to the turning of you, in any measure,
from darkness to light,
our souls wish and desire the multiplying and abounding
of the grace and love of God in you,
and among you; that thereby you may grow in union and favour with God,
and into the fellowship with all the Children of Light;
and may be nourished as new born babes, by the milk of that Word which endureth forever.
And verily, though we are now separated from you in the body,
yet are we present with you in spirit, not ceasing in prayer to God for you;
but with heart breathings to Him,
our souls are poured out at the Throne of Grace on your behalf,
that your faith may not be made void, knowing your state and condition;
being fully sensible of your weakness to resist the temptations of the enemy,
being but young and tender in the experience of the way, and operation of God;
and unacquainted with the cunning wiles of Satan,
who will not cease seeking whom he may devour,
and whom he may lead aside in the by-paths of iniquity,
from the obedience and faith in Christ Jesus;
that shipwreck may be made of those good desires now begotten in you,
through the ministry of Christ sent unto you; by whom a good work is begun in you,
which will bring forth the redemption and salvation of your souls,
if you abide in the patience, enduring the cross and sufferings unto the end.

And dear friends, this charge, in the Name of the Lord, we lay upon you;
that in the fear of the Lord, you meet together, waiting in the patient hope,
in the Light which leads out of the night, and out of all the works of darkness,
unto the day, glory, and rising of the Sun of Righteousness;
that all clouds and veils may be removed,
and the night of darkness and stumbling may be wholly finished;
that as Children of the Light, and of the day, you may walk,
bringing forth fruits of righteousness, unto the glory of God; being judged in the flesh,
and condemned as men in the flesh, and changed,
from its nature of transgression and disobedience,
into the Divine nature of God and into the likeness of the Father; that henceforth,
as a people redeemed by Him, and saved of Him, you may serve Him in newness of life,
by the Spirit of bis Son; who dwells in you, as you dwell in the Light.

And hereunto, the Lord God Almighty preserve you,
to the finishing of your course with joy, in the way of the Lord;
that you may know as you are known; and victory may be given you over death, hell,
and the grave; and that through the war you may partake of the crown immortal,
which fades not away.
Therefore be faithful in obedience to the will of God, made manifest in the Light,
which condemneth the evil, and chooseth the good.
And daily become subject to the cross of Christ, taking up his yoke and burden,
which killeth and crucifieth the fleshly man, with his affections, desires, and lusts;
that being slain to all mortal, you may reign in immortality over all your enemies,
inward and outward; against which you are to war,
even against spiritual wickedness in high places,
and against exalting thoughts and imaginations.
Therefore put on the strength of the Lord Jesus Christ,
and gird yourselves with his power; and be low in heart,
and subject to the Father in all things; and be not high-minded, but fear;
and stand in awe, and sin not; neither fly the cross of Christ,
but let it be your rejoicing; and let love abound among you,
even the love wherewith you are loved of the Father; being of one heart,
and like-minded one with another, forbearing one another, and forgiving one another,
and humbly reproving one another, if any be overtaken with a fault.

And wait for discerning, to have salt in yourselves,
to know and savour one another in the spirit, and operation, and working of it;
that being sensible, and feeling of one another`'s conditions in the spirit,
you may speak to the informing of one another,
unto the building up of one another in the precious faith; but be slow to speak,
and swift to hear; and feed not one another`'s sensual wisdom,
which is the serpent`'s seat: for words without knowledge darken counsel,
and betray simplicity.
But take heed to the measure of the Light of Christ) and be watchful in it;
having the loins of your minds girded up, as obedient servants,
waiting for the will of God;
to be doers thereof from the simplicity and sincerity of the heart;
being watchful lest the tempter by imaginations present himself in a way and voice,
like unto the way and voice of the True Shepherd; and thereby the simplicity be ensnared,
and your way and savour be lost, and darkness and clouds come over you;
and so deceit strengthen itself, and take an offence in Christ Jesus.
The last end of such will be worse than the beginning:
and the way of truth will be blasphemed;
and the grace of God will be turned into wantonness;
and the door of Life will be shut against them.
But be upright-hearted, and single-minded unto the end;
for he that overcometh shall eat of the hidden manna.

And strive not one with another, neither judge one another,
in that which you do not see in the Light; but keep at home in your own conditions,
waiting till judgment be perfected in victory, and your redemption brought forth.
And though you have trouble in the world, and suffering and reproaches from it;
yet in Christ shall you have peace, and joy in the Holy Ghost:
for your present troubles and sufferings,
are not worthy to be compared with the glory that shall be revealed in you.
And coming through the same entrance of tribulations with us,
you shall be made partakers of the same life, and glory, and inheritance, to rejoice,
and sing the song of the Lamb forevermore, over the beast, and over his mark,
and over the number of his name.

And all of you, whether masters or servants, parents or children,
of what calling or condition soever, walk as becomes the gospel of Christ Jesus,
in all holiness, and purity, and humility in your conversation;
and be examples of righteousness one to another,
that in your several places you may honour Him who hath called you,
by works of faith and righteousness;
that thereby the mouth of such as wait for your halting may be stopped;
and by your good works God may be glorified in the sight of your enemies.
For the gospel preached unto you was not to lead into words only,
but into life and power; and with such as are in the life and power our unity stands;
and we shall never be ashamed to call them brethren and sisters.

Therefore dear children, be diligent in the Lord`'s work,
and steadfast in watching over your own hearts in particular;
and watch over one another in general for good, and not evil;
that you may grow up into one body, members of one head,
joined by the Spirit unto Christ Jesus, who is the Light of the world;
upon whom you have believed to your salvation, if you continue in the faith.
And your rock of defence and salvation, is become the stumbling stone,
and rock of offence to the princes and to the rulers.
And truly beloved, our bowels are troubled for you,
being not ignorant of the very purpose of Satan; who hath now stirred up his agents,
thinking to make void your faith and belief,
and even to slay the child whilst he is young:
but our confidence in the Lord herein is strong, that He will preserve you to his praise,
and the little seed shall never be forgotten of Him; but though it was sown in weakness,
it shall arise, and spring, and be raised in power,
to the torment of all the Lord`'s enemies.

And you whose hearts God hath touched, and who are entered in to the way,
look not back at any glory left behind; but freely give up all,
and press on in the straight way, through the death of the enmity upon the cross;
and as you deny yourselves for Christ, so will your reward be from Him manifold.
Dwell in the judgment till the ground of unrighteousness be removed;
and so eternal peace be manifested unto the seed of immortality.
And look not back at hardships, nor at the multitudes of temptations; but mind the Light,
which is the whole armour of God,
whereby you will receive strength to overcome all your enemies;
and the Covenant of God will be established with you,
in which you will receive the blessing in all things,
and will know how to use all things to the glory of God;
seeing his pure presence in all his blessings.
Stand always in the cross to the carnal,
and so your understandings will be kept open and clear,
to receive the pure teachings of the Father; and his wisdom from above will grow in you;
and the wisdom of the earthly will die.
And if you abide in the Light, which is from the beginning, you need no man to teach you;
but by the anointing which you will receive,
you will be taught all things in the way of God perfectly;
and so stand witnesses for the Lord, and against all the world and its deceits.

Beware of the love of the world; and of the bad ground; and of the envious man,
lest he sow tares among the good seed, and so you become corrupted,
and the just principle in you be betrayed;
and so Satan exalt himself above the measure of God`'s Spirit revealed in you;
and so you perish in the gainsaying.
But our hearts hope better things of you, even your growth into the heirship with Christ;
to reign with Him over the world, in the incorruptible inheritance;
that we may reign together in one heart and mind, one with another.
And truly herein will our joy be increased, in the midst of our troubles and sufferings,
to hear and understand of your faithfulness and obedience,
in the faith of the gospel declared unto you.

To the Grace of God, upon whom you have believed, we do commit you,
in the bowels of everlasting love and pity, with tenderness of soul and spirit,
to be kept by the power of God unto the day of salvation.
The eternal presence of the Lord God, the Everlasting Father, be with you all.
Amen, Amen.

We are yours in the Lord; and are fellow-prisoners for the testimony of Jesus,
which we hold: known to you, and not to the world.

[.signed-section-context-close]
From the house of the Sergeant at Arms in Dublin, the 24th. of the 12th. month 1655.

[.signed-section-signature]
Francis Howgill.

[.signed-section-signature]
Edward Burrough.

[.old-style]
=== Section II. / An Epistle To Friends In London.

A servant of Jesus Christ, unto all chosen, obedient, and faithful friends and brethren,
in and about London, wisheth an increase of righteousness, faith, obedience, patience,
and love, that you may know and feel an increase in the increase of God; that your joy,
rest, and peace may be full in Him, who is eternal life itself: who hath brought,
and is bringing immortality to light through the Gospel, unto all,
and in all who receive it, and believe in it; which is the power of God unto salvation,
unto all that believe.
And by it alone is the remission and forgiveness of sins witnessed;
and in no other name but his, who is the mighty power of God, is eternal life witnessed,
or victory and dominion over sin, the world, and the devil, even by Christ Jesus,
the Word of God, the Power of God;
by which power alone is strength and victory witnessed over death and the grave,
by all that believe in Him, and receive Him;
and to them He gives power to become the sons of God,
and to receive an inheritance with the saints in light, among them that are sanctified.
Therefore, dearly beloved in the Lord,
fulfill our joy who have laboured and travailed amongst you;
and have declared unto you the Gospel,
which is preached unto every creature under heaven;
and the common salvation which was delivered to the saints, who are at rest in the Lord;
and is now again delivered and declared unto us, in this his own day of mercy, love,
and grace; and the revelation of his righteousness;
that they without us might not be made perfect: for all make up but one body,
and if a member be wanting, the body is not perfect.

And you yourselves are our witnesses, that we preached unto you Christ the Lord,
whom we were made partakers of; and ourselves only your servants, for his sake.
And the Lord is our witness, and his Spirit in you all is our witness,
that we followed not devised fables;
neither through enticing words of the wisdom of man declared we unto you;
nor handled we the word of truth deceitfully, but in much fear, and soberness,
and tenderness unto all in whom there was any ear to hear,
or any desire in their hearts after the Lord.
Neither did we seek to exercise dominion over you;
but rejoiced when any had dominion in the Lord over deceit;
and when they reigned we reigned also: but they who reigned without us,
and not in the Lord,
and would have entered through deceit and craft any way into the vineyard of the Lord,
and have spoiled the plants, and would have subverted from the faith,
we gave no place unto, no not for a moment.
The righteous indignation of the Lord,
will fall on them who have made the offence of the cross to cease,
and gloried in the flesh, and would have brought all thither again,
and have made havoc of the flock of Christ for whom He died;
and would have had them to have lived and reigned, who put Him to death;
and counted that which cleansed from sin, a vain and a low thing.

Dearly beloved of the Lord, who are obedient unto the word of his grace,
these things are come as a trial, that none may henceforth glory in man,
nor in any thing but in the Lord, the Life itself, and in them who are in the life;
and every one may keep to his own singly; and so will not be easily moved.
And you whom the Lord hath kept in the hour of trial and temptation,
so that you joined not with the error of the wicked, prize his love, and keep low;
stand in awe of the pure presence of the Lord,
else you will know his wrath to be kindled against you again; but the fear, awe,
and dread of the Lord keeps you clean, clear, and pure in his sight.
All mind the first love, and that which keeps your hearts open and tender to the Lord,
and one to another.
Put away all strife and contention; watch not for one another`'s halting:
for that which would rejoice therein is in the transgression itself.
Dwell in love and peace one with another.
Take heed of security, and carelessness, and ease in the flesh;
for that will bring poverty, dryness, and barrenness among you.

But all feel the life and the power of God; and let your faith stand in it alone;
and they that trust in it shall never be moved;
for there you will be preserved out of the changeableness and changeable things,
which adulterate the mind from God, who never changeth.

He who hath the key of David, opens the door of the treasure house of eternal wisdom;
and unto every one He gives a measure according to the good pleasure of his will:
to those who wait upon Him, and are faithful, He gives of his wisdom and knowledge,
which are past finding out by the children of disobedience, whose wisdom is corrupt;
but in all that believe He pours out a measure of his Spirit of Life, of purity, and power;
and in the measure all that wait have unity with Him, who is the fulness of all things;
and of his fulness receive grace for grace: and his righteousness, love, wisdom, mercy,
and fulness are revealed from faith to faith: and as you believe, so are you near to Him,
whose ways cannot be measured; and as you grow in the faith of Him, and in Him,
who hath enlightened you, and shined in your Hearts, you will see more of his love,
of his purity, holiness, wisdom, and glory, and feel and understand of Him, and from Him,
who is invisible and eternal; blessed forever and ever.
Amen!

So friends, all press on towards the mark; that you may know completeness in Him,
who is all fair, and altogether lovely; and you who know his love, and the beloved,
hold Him fast forever, and let Him not go.
Nothing can separate but an unchaste heart.
But if you join unto any strange flesh or idols, or other lovers,
and so draw your love from Him, be sure of this, He will hide his countenance from you;
and then sorrow will fill your hearts.
So look not to Egypt again, nor to what you have parted with,
lest you be turned into a pillar of salt.
"`Remember Lot`'s wife.`"
There are many of the same nature with her, who are as examples;
that you may forever beware,
lest the same root of bitterness spring up as hath done among many,
upon whom nothing is to be expected, but a daily,
fearful looking for of the just judgments of God, for their ungodly deeds,
and hard speeches against the Truth, and the servants of it.

All abide in the cross,
that the nature out of which the lusts and the war arise against the Lord,
and against your souls, may wither, die, and be worn out;
and so you will see more rest and peace in and with the Lord;
and He that hath begun will finish.
All power is committed to Him, both in heaven and earth.
He will work righteousness in the earth, and preserve all in peace in Himself forever,
who believe in his power.

And so friends, this I must needs say: If you be straitened it is in your own bowels;
as sometimes I have said when I was present with you even the same I write now:
Destruction is of self; and barrenness is of self;
and deadness and disobedience are of self; but as you believe in Him who is near,
and in his grace, self is judged and bruised under;
and you will feel Him who is the first and the last to enlarge your borders,
and make your mountain strong, and your heritage goodly,
and your ground fair and pleasant,
where the pleasant fruit of righteousness is brought forth;
which grows in the valleys of righteousness, where the beds are green, and the garden is,
which gives a sweet smell; and where all that dwell, live, and abide, are fresh,
beautiful, and lovely in the sight of the Lord,
and in the sight of all the children of Light forever.

Friends, above all things keep low; and none judge of yourselves,
nor think of yourselves above what is meet: take heed of conceitedness, and pride,
and exaltation, and presumption, and of gainsaying,
and resisting them who have laboured amongst you in word and doctrine;
whose example you have daily as a pattern before you.
Let there be no boasting, nor contentions, nor strife, nor emulation, nor surmising;
but in singleness of heart, all bear and forbear one another;
and let the same mind be in you as was in Christ Jesus;
and so peace will be in your dwellings, and rest and prosperity in your habitations;
and plenty,
and riches from above of the heavenly wisdom will be multiplied in your meetings;
and the pure presence of God and his power will compass you about,
who are of an upright heart to the Lord.
That so you may be as examples and patterns of holiness and righteousness in your generation;
that your enemies may confess God is among you of a truth.
And so the power of the Lord Jesus Christ rest and abide amongst you all,
that you may continue to the end;
which is the desire of Him that shall rejoice in
nothing more than in the prosperity of you all,
in the everlasting truth of the Son of God, heir of all things, blessed forever,
and ever, world without end.

[.signed-section-closing]
A servant to the least, for the Truth`'s sake.

[.signed-section-signature]
Francis Howgill

[.old-style]
=== Section III. / A General Epistle to the Seed of God.

Dear friends everywhere, who have believed in our Lord Jesus Christ,
and are called with a holy calling to the great salvation of God,
which is manifest in this the day of his power, keep your first love,
and let not the threats of men, neither the frowns of the world,
affright you from that which you have prized more than all the world.
Now the sun is up, and a time of scorching is come,
and that which hath not root will wither; now every ground will be tried;
and blessed is the good ground that brings forth the Seed which must inherit the promise.
O! let not the cares of this present life choke that which God hath begotten; and,
seeing the Lord hath so marvellously wrought for us hitherto,
in the midst of great opposition, let not your faith fail, nor your confidence in God;
who delivered Jacob of old out of his adversity, and Israel out of all his troubles;
whose care is over his people now.

And having seen the emptiness of the world, and its ways and worship,
let nothing blind your eyes again; and let not the things present, nor things to come,
separate you from the love of God in Christ Jesus;
and mind not them that draw back to perdition, but let it teach you all more diligence,
to be as those that press after glory, immortality, and everlasting life.
The way of God was ever hated by the world, and the powers thereof.
Never heed the rough spirits, for their bound is set, and their limit known,
but mind the Seed which hath dominion over all;
and forsake not the assembling of yourselves together, in which you have found God,
and his promise and power amongst you, and your understanding opened.
O! rather suffer all things than let that go which you have believed; for whosoever do,
will lose the evidence of God`'s Spirit in them; and their peace and joy will be lost.
The Lord God preserve you all unto the end faithful.

[.signed-section-closing]
Your dear brother, for the testimony of Jesus,

[.signed-section-signature]
Francis Howgill

[.signed-section-context-close]
Appleby Jail, the 10th of 3rd. month, 1664.

[.old-style]
=== Section IV / A Visitation of Love, Peace, and Goodwill to the Whole Flock of God; Now in This Their Day of Trial, and Hour of Temptation

Dear friends and brethren,
who have been called to believe by the holy calling of the Lord,
unto sanctification and holiness, that ye might inherit the promises of God;
and that your souls might live, and partake of his goodness; that you might admire Him,
and praise his Name forever, seeing the Lord, out of his rich love and mercy,
hath visited you, who sometime sat in the region and shadow of death,
and were cast out of his presence, in the time of unbelief;
and seeing He hath caused his miraculous Light to shine upon you in his gracious visitation,
and hath given you to believe in his Name, prize his love unto you;
and let not his gracious benefits slip out of your minds;
lest your hearts be filled with other things, that will corrupt your hearts,
and make you an unmeet habitation for the Lord to dwell in and among.

Dear friends! hear my brotherly admonition and exhortation;
for the Lord moved in my heart to write unto you;
and in the bowels of his kind and tender love, and motion of his heavenly Spirit,
to stir up your pure minds and consciences,
unto steadfastness in the faith of our Lord Jesus Christ; and so much the more,
that you all be watchful, seeing the times are perilous;
for now the adversary goes about roaring and ravening, on the right hand and on the left,
to destroy and devour that which God hath brought forth in you:
that so He might regain you too, under his power and government;
and that he might revolt from the kingdom of our Lord Jesus Christ,
which stands in power and righteousness, and which is come,
and hath been of a truth manifested in great glory.

This is an hour the power of darkness is let loose in,
to try the faith of them that dwell upon the earth; and he is let loose for a season.
Blessed are they that hide themselves under the shadow of the Almighty,
and under the wings of Christ Jesus, who is given for a Redeemer, a Saviour,
and a Preserver of men, that the wicked one touch them not: and now the devil rages,
because a stronger then he that rules in the world is come,
and hath begun to dispossess the strong man, and bind him, and cast him out;
and now he rages and stirs up all the temptations, within and without,
and all his instruments to join with him, to make war for him;
in order that Christ may not rule; who is the heir of all things, and given for a Leader,
and to be the head of the body his Church, in which He alone hath a right to rule;
because the Lord of the whole earth, yea of heaven and earth,
hath put all power into his hands, to bind and to loose; to bring out of captivity,
and to lead captivity captive;
that life and immortality may again inhabit in the sons of men;
that truth and righteousness may sway; that mercy and love may sit on the throne;
that salvation may take hold on the ends of the earth,
and this power be made known from sea to sea; that all who wait for Him,
and love his appearance now when He is made manifest, may rejoice in goodness and life,
and may be made glad as Zebulun and Naphtali beyond Jordan, in the days of old,
upon whom sprung up a marvellous light;
that the whole earth may be filled with his praise and glory,
which hath been filled with darkness, violence, and cruelty,
in the time of the devil and antichrist`'s reign,
which hath been long and great in the earth;
so that the hearts of the sons of men have been corrupted,
and they are gone backward from the Lord;
and have been degenerated into a strange nature;
and have brought forth evil and corrupt fruit like that of Sodom:
and they that do evil are not at all ashamed, neither do they blush;
but are become impudent through long custom of evil, and hard and impenetrable;
upon whom the hammer of the Lord must come, and his indignation be poured forth.

But you whom God hath called out of this estate, into a state of redemption and purity,
by his Son, the Light of the world, who hath illuminated the eyes of your minds,
consciences, and understandings, that you may bear witness unto Him that is true,
and a testimony against the world that lies in wickedness, and pleads for it,
and lives in it, as though it were the way to felicity, hold fast your liberty;
hold fast your faith; hold fast your hope; hold fast your testimony:
let none take your crown; and so much the more as you are compassed with temptations,
and the times are perilous; so much the more you had all need to keep near the Lord.

Dearly beloved,
let not the Philistines stop up your wells for then you might perish in the drought,
for lack of moisture.
The Lord will perform his promise,
and keep covenant with them that keep covenant with Him;
but if you forsake Him in your hearts in what is made manifest, then He will forsake you;
and then you are left to the mercy of your adversary, which will be cruel.
Therefore heed not the pride of Moab nor the reviling of the children of Ammon;
for they are unhallowed in heart, and the moth shall eat them up as a garment.

Oh! if any draw back from following the Lamb through suffering, they will be smitten;
and the Lord will have no pleasure in them.
And what will Amalek say, when Israel turn their backs in the day of battle, but,
"`Where is their God, in whom they trusted?`"
And, "`He that brought them forth was not able to deliver them to the end!`"
Oh! that such things might never be spoken of now in Gath or Ashkelon;
as in the days of old! lest the sons of the Philistines triumph,
and the daughters thereof rejoice in their wickedness;
for this would make the hearts of the Israel of God to mourn.

This is the day of the Lamb`'s war indeed in our age; and a day of battle,
though his weapons are not carnal, but spiritual.
And there is none that goeth to war, and doth entangle himself,
that hath a purpose to hold out, and is resolved to continue with Him in suffering;
but will shake off these things that encumber, lest he should not obtain the victory,
promise, or crown, which all that endure hardship to the end shall receive.
O dear friends! look above all visible things; and stand out of them all,
and loose from them, that the enemy do not ensnare you.
What! is not the earth the Lord`'s, and the fulness thereof?
And hath not He given the utmost part of the earth for a possession to his Son?
What! was not Abraham our father blessed, when he was faithful,
and obeyed the voice of the Lord; and went out of his own country, he knew not whither?
Was not the Lord with him whithersoever he went; and his blessing upon him,
when he sojourned in a strange land?
Did not God entreat him kindly in Mesopotamia, and among the Hittites?
and was not he loved and feared among his enemies?

Was not John, the beloved and faithful disciple of Christ,
banished into Patmos for the testimony he held?
Were not Shadrach, Mcshach, and Abed-nego, children of the captivity,
cast into the furnace?
and Daniel too among the lions,
for the testimony they held against the common worship of nations commanded by a law?

Did not Christ endure the death of the cross, and the contradiction of sinners?
and was He not condemned by most?
Did not the believing Hebrews, who were banished, wander in sheep skins and goat skins,
into dens and caves of the earth, for the hope they held and the country they looked for?
Did not Moses through faith forsake Pharaoh`'s court,
and become companion of poor brick-makers in captivity?

A cloud of witnesses might be brought, even of them who died in the faith,
and yet were not made partakers of the promises,
who many of them saw not what you have seen; nor heard those things that you have heard;
nor enjoyed that which God hath made many partakers of:
and have we not a great cloud of witnesses in this our own age?
some who have not loved their lives unto death, for the testimony they received,
believed, and held fast unto the end, unto death?
Have not many died in prison with hard usage?
have not some been hanged, and died a shameful death,
and finished their course with joy and peace?
have not many endured great, hard, and long imprisonments for years?
and are they yet weary?
nay, have not many suffered great spoil of their goods;
and have not they a reward sevenfold into their bosoms?

O! let the consideration of these things dwell upon your hearts,
and provoke you unto suffering with joyfulness; that in the midst of all tribulation,
as it abounds, you may feel according to the promise of God, your joy much more abound,
to carry you above it: indeed now is the time come;
and he that will manifest himself to be on the Lord`'s side must suffer;
and he that will not, but turns back into the broad way,
and runs with the herd of swine into the sea of common pollution, must perish there:
and indeed there is no place for halting.
If God be God, follow Him; if Baal be he, go after him.
And therefore let none draw you aside from that which you are persuaded of in your conscience,
by the Spirit of the Lord; neither join with that you know He disallows;
and in the obedience you will have peace and joy.
Look not at them that draw back, for they go to perdition,
but rather after them that continue faithful, that shall receive honour, glory,
immortality and everlasting life.

In the fresh, heavenly power of God, meet together and worship Him, as at other times;
though the decree be gone forth; and the more because you have been therein refreshed,
comforted, and edified; and let none persuade you from that innocent duly,
in worshiping God in his Spirit, and assembling yourselves together,
for the strengthening of one another: for this is the will of God,
and acceptable in his sight; as many of you well know.
Watch and pray, lest you fall into temptation, and into the snare of the wicked one.
The God of heaven and earth establish all your hearts,
that you may glorify Him in your generation,
and be a sweet smell unto Him in bonds or liberty, in life or death,
is the prayer of him who hath besought the Lord,
and is determined so to do on all your behalf, till the Lord by his power,
tread Satan under your feet, that you may triumph over all, rejoicing and praising God,
and the Lamb, that lives forever, and forevermore, Amen.

Your dear brother in the patience and sufferings of Christ,
who abounds in perfect love to all the faithful flock of Christ everywhere,

[.signed-section-signature]
Francis Howgill

[.signed-section-context-close]
From Appleby Jail, the place of my rest, where my days and hours are pleasant unto me,
the 4th. of the 5th. month, 1664.

[.old-style]
=== Section V. / A General Epistle to All Who Have Believed in the Light of the Lord Jesus, and Are Called of God to Follow the Lamb through Great Tribulation.

Dear friends, who are called out of the world and the vanities of it,
to serve the Living God in newness of life,
and to be worshipers of Him in spirit and in truth,
and to be followers of Christ in the regeneration,
and to be baptized with Him into his suffering and death;
that so you may be partakers of his resurrection and life,
and manifest unto all that you are risen with Him, out of the grave of sin, wickedness,
and death, by having your hearts renewed,
and your affections and minds set to seek those things which are above,
which are not transitory and visible, but everlasting and immortal;
by which the souls of all the righteous and obedient children are refreshed,
and nourished up unto eternal Life; through the eternal power of the Son of God,
which hath been and is manifest among them that believe in the measure of his Spirit,
and keep their first love and integrity unto the Lord.
All his are preserved out of the temptation of the adversary within and without,
who seeks to root out that which God hath planted,
and to nip the blossom and the bud which God hath caused to spring forth,
through his lender love in your hearts, so that you might die to the good,
and be spoiled in that wherein all your happiness lieth now and forever.

O! therefore, all watch and be circumspect, so much the more against temptations;
lest you be ensnared, and your faith fail,
and you fall short of the promise of God in not continuing faithful to the end.
Friends, a care, and a tender love, and a godly jealousy is in my heart to you,
and over you all that have believed; that none of you may be lost,
and scattered again in the deserts and mountains, and dry and parched places,
where you have sometimes been in the time of unbelief;
where the goats that are rough can feed,
that must go to the left hand and have the curse.

The zeal of the Lord and his truth, who so gloriously hath been manifest among you,
above all the people and families of the earth in our generation,
constrains me thus to write unto you;
and to stir you up unto faithfulness in this day of trial:
for now Satan desires to winnow you within, and to sift you without.
Therefore all watch and pray, that your faith fail not, which now will be tried,
and also your hope, and your love, and your zeal to the Lord and his truth;
proving whether you will confess Him before men, his way, worship, laws, and statutes,
which He hath revealed in your hearts, which fallen men oppose, and contradict,
and gainsay; and would not have Him to rule, nor his servants to obey.
So let it be manifest to all, that you fear God rather than men, and love Him,
and obey Him above the precepts of men which are against Him;
and whether you love the things that are above, beyond the things that are earthly;
and whether you will own Him, his cross, reproach, and suffering,
or deny Him and have the liberty of the world, which is bondage,
and free from righteousness.

It is no time of reserves, concealing, hovering, or halting:
for there is an utter discord betwixt Christ and Belial: and as Christ, his power,
and kingdom, are brought forth; so much the more are the hatred, envy,
and wrath of the Devil kindled, who hath deceived the nations, blinded their eyes,
and manifested himself in his subjects who oppose the Lamb of God,
and tread under foot the blood of the Covenant.
Therefore all children of the day, put on the armour of Light; and have your feet shod,
now when we walk through thorny places, and be not fearful or doubtful,
but of believing hearts;
stand not aloof and idle when others are engaged in the spiritual war;
pull not your necks out of the yoke when others draw;
shelter not yourselves when you see others in jeopardy;
love not the world when you see others have thrown it off;
be not entangled in cumbersome things when you see others throw off all weights;
turn not your backs in the day of controversy; but follow the Lamb.

This is the day of tribulation in which we have to follow Him in our age,
like as all the martyrs and prophets had in their age;
whose garments were made white in the blood of the Lamb:
so all that continue and are not fainthearted, shall receive the crown, the honour,
the reward; and they shall reign with Christ, who now suffer with Him.
Therefore all dear children of God, and followers of Christ Jesus,
let the loins of your minds be girded up; be now ready when the Lord calls:
"`Who is on my side?
who will take part with Me? who will own my reproach?
who will engage with Me? who will gather to my standard of salvation lifted up,
and to my ensign of righteousness, held forth in the world to redeem it?`"
May all say in their hearts: "`Here am I, ready to do thy will,
ready to obey Thee and follow Thee,
and to suffer for Thee;`" for whoso draws back the Lord hath no pleasure in him.

He that will save his life shall lose it;
and he that will save his liberty shall lose it in the Spirit;
and he that will save his earthly possession,
and for it will deny that which God hath persuaded him, that he ought to be faithful in,
he will lose his inheritance in the heavenly kingdom.

In a word, whosoever fail in holding forth the testimony, which they know God requires,
and that it is their duty to render unto Him, will lose the testimony of his Spirit,
which they have sometimes felt in themselves, and will decay;
and their love will wear out.
Therefore, whosoever are resigned and given up unto the Lord, will be approved,
and manifested to be on the Lord`'s part, by obedience to these things mentioned.

Friends, do you not believe it a duty that every Christian ought to be exercised in,
to meet together to wait upon God, to worship Him, and to admonish, exhort,
and strengthen one another; to pray together in the Holy Ghost, and one for another;
and to edify and comfort one another?
And do you not believe that "`God dwells not in temples
made with hands,`" neither hath any fellowship with idols;
but is worshiped anywhere, and in every place where the saints meet in his Name?
Again, have you not been comforted, edified, and strengthened in meeting;
and have you not found the presence of the Lord and his face;
and have you not felt his great power working in your hearts,
when you were assembled together in his Name;
working in you to the opening of your hearts,
and quickening and enlivening your souls unto God, and judging down the evil?
And have you not felt his loving mercies shed abroad in you,
and the spring of Life opened, and the holy Seed refreshed,
and God`'s witness reached in all,
and many convinced and converted unto God in your assemblies;
so that all have gone away comforted and refreshed,
and resolved to continue in the grace of God.

The consideration of these things dwelling in your hearts,
and the sense of your own present condition,
should stir you up and provoke you unto steadfastness,
in the faith and practice you have received and walked in,
from the beginning of the manifestation of God`'s love unto you;
so that there should need little exhortation.
God`'s enemies are resolved to do wickedly; be ye also resolved to do your duty.
They seek by any means to make any fall from their principles and steadfastness:
do you seek to escape their snares, and to be kept clear in your consciences before God.
Be valiant for the Truth; sell it not, but sell all for it, that it may be your all;
and then you shall see your lot is fallen in a good place,
and that your possession is pleasant.

The Lord calls now to suffering; put now your necks into the yoke;
"`bear one another`'s burdens,
and so fulfill the law of Christ:`" and take heed
you give not ear to that voice that speaks:
"`Save thy liberty; save thy estate; possess thy own, and provide for thyself;
and spare thyself;`" that is the voice of the enemy of your souls:
so keep over the world and its spirit; let no slackness appear,
for that makes sufferings long;
and that gives ground to your adversaries to hope that they shall prevail;
and that weakens the hands of others and strengthens not.
This confirms our enemies in their belief that we are but as other men and people,
who have professed God in summer and fair weather;
but will make shipwreck of all in a Storm, and in suffering:
and any turning aside from the holy commandment of God,
openeth the mouth of God`'s enemies.
Seek not every one your own profit, ease, life, and liberty only;
but every one another`'s good; and mind not only one member but the whole body.
Heed not them that draw back: they are no precedent for you to follow;
but those that press forward, and are not offended in the time of hardship,
are your precedent.
Heed not them that will tell you they can keep their hearts upright to God,
and retain their love to truth and friends,
and yet will not afford their presence in your assemblies, but escape suffering,
and deny the cross, and neglect their present duty; for that is deceit;
and their own hearts will deceive them.

Put not off till tomorrow; defer not the time till you can see some more ease,
and some greater calm.
Beware of that; for then coldness, fearfulness, and slavishness will enter in;
and you will lose your strength.
Moreover, if any have begun well,
and are persuaded of the truth of what they have believed, and continue not unto the end,
and do not finish; such will be reckoned foolish builders, that could not finish;
and all will mock them; and our adversaries will glory over them.

Again, when any suffer or are brought into bonds for Christ and the Gospel`'s sake,
let them not seek to get out by any indirect means,
neither make any covenant with the adversary, who would sell both them,
and all faith and hope for money; for that encourages deceit;
and that spirit would buy itself out of the service of God, and grow weary.
Give no place to that; be content every one with your present condition,
till God arise and plead our cause,
and make our innocency and righteousness appear as noon day,
and make his adversaries his footstool; which undoubtedly He will do,
and make all know that the Most High ought to rule, and will rule in the kingdoms of men;
and not give his glory to another, neither suffer another to take it.

Be conformable to none that go about under pretence of love,
to persuade or counsel you from your duty to God;
neither submit to them that would betray you of your peace.
Heed not the frowns of corrupt men, nor the counsel of them who mind their own pleasure,
ease, profit, and earthly things; let not natural affections and love, either to lands,
wife or children, blind your eyes; but love them, and receive them in the Lord,
and enjoy them as though they hindered not.
Stand loose from all things, and out of entanglements; and cast your care upon the Lord,
who careth for the fatherless and the widow, and them that have no helper in the earth.
Give no occasion or advantage to any that would turn
your hearts aside from following the Lord;
lest their love betray you.
Give up all you have and enjoy, to the Lord and his service; and your souls, bodies,
and spirits, as a sacrifice unto the Lord, that He may accept you,
and pour forth and continue his blessing amongst you.
Never heed the threats of them that are as the oaks of Bashan,
nor of the men of the earth, that mind their pleasure and lusts;
who shut you up in prison, and hale you before judgment-seats for the worship of God,
and falsely accuse you, and condemn you when God justifies you.

Friends! dwell above all these things, and the devil and his rage.
The earth is the Lord`'s and the fulness of it;
we cannot be banished from God`'s presence,
neither shall they ever be able to root out that testimony which is among us.
The God of power strengthen you all; that you may quit yourselves like men of God,
like children of the Most High, whose inheritance is not here in the world,
but in the kingdom that fades not away.

The Lord God of power be with you, make you consider what I say,
and cause you to receive this my true love unto you all, for the Lord`'s sake;
who partakes with all the suffering members of Christ in their bonds; and shall,
and can rejoice in your comfort and joy.
The peace of God dwell in your hearts,
and his heavenly Light shine upon all your tabernacles;
that you may be as beautiful in the eyes of the Lord, as the roses of Sharon;
and blossom as the lillies of the valley;
and yield your fruit as the fig-tree that casteth not her fruit.
The Lord takes our part; let none doubt of that;--and pleads our cause;
let all consider that;--our enemies shall see it, and be troubled at this;
and time shall manifest it; therefore be of believing hearts, and trust in the Lord;
so shall you never be confounded, neither be ashamed;
but be as Mount Zion that cannot be removed:
and as the mountains are round about Jerusalem,
so shall the mercies of the Lord compass you about,
from this time forth and forevermore.

Friends, faith is sealed in my heart, and love in my veins, and gladness in my soul,
and peace in my conscience; so that none doth or can hinder my rejoicing.
Praise be to the Lord forever and ever.
Amen.

The Lord`'s servant, and yours in all true, unfeigned, pure love.

[.signed-section-signature]
Francis Howgill
