== Chapter I.

A Short Sketch of Francis Howgill`'s Life;
with an Extract from His Own Account of His Early Religious Experience.

Francis Howgill was born about the year 1618; and his residence was at Todthorne,
near Grayrigg, in Westmoreland.
He received a University education, and became a minister in the Episcopalian church;
but afterwards left it,
being dissatisfied with the superstition which he saw remaining in it,
and joined himself to some Independents, among whom he became a teacher.
Not, however, meeting with that spiritual comfort which his soul thirsted after,
he went among the Anabaptists,
apprehending that they walked more in accordance with the Gospel of Christ.
Still he remained destitute of that peace of mind which he so earnestly longed for;
and at length, about the thirty-fourth year of his age,
he joined the persecuted society called Quakers; among whom he became a zealous member:
and he died in communion with them,
after having been about sixteen years eminent among them, as a minister,
and on account of his writings and sufferings.

He has left a particular account of his early religious experience, in a work entitled,
"`The Inheritance of Jacob discovered after his return out of Egypt;`"
from which the reader is here presented with a copious extract.

"`From twelve years old I set my heart to know that God whom the world professed,
and whom I read of in the Scriptures; whom Abraham, Noah, Moses, the Prophets,
and the rest of the Fathers worshiped:
and I fell into the strictest worship that was in that part wherein I lived;
and often I desired to be alone, and attended much to reading and meditation.
And as I was sober and serious, I began to see that all the sports and pastimes,
and such as youth delight in naturally are vanity, and that they last but for a moment:
and while I was in folly and wantonness, doing them,
the nature which was run into transgression had pleasure in them;
but as soon as I was come from among them, I was judged in myself for what I had done;
and it often made me weep.
Then I resolved in my will that I would never do so again;
and for some time refrained from the common practice
of those things that I had walked in;
but as soon as I came among them I acted those things again,
which before I had seen to be vanity.
But, long before that, I was checked for many things;
and so I walked often condemned in myself, and had no peace when I was serious; and then,
not knowing what to do, I was in much sorrow when I was alone.
I had a desire to be alone where I might not see or hear any folly acted,
and did not go to the former excesses, although something in me hankered after them:
but when I yielded not I was glad and had peace.
And then I began to oppose my fellows, with whom I had walked in wantonness;
and they began to revile me, and hate me, and scorn me; yet I mattered it not.

"`Then I read much, and prayed in words, often three or four times in a day,
yet knew not where God was, but imagined a God at a distance; and so went on.
Then I began to grow in knowledge without, which is sensual; and I was puffed up,
for the world admired me: but still I was condemned for vain words and actions;
and the root of iniquity grew in me.

"`Then I followed a more strict course,
often went five or six miles to hear some more excellent means, as they called it,
and so got more words; but still I was the same, no worse, for knowledge puffed me up.
Then about fifteen years of age I posted up and down after the most excellent sermons;
and so became acquainted with all those called eminent Christians,
in the region where I lived: and I was despised of my parents;
and of the world made a wonder; and great reproach came upon me;
but still I saw they knew nothing, and therefore it was no matter.
So much sorrow fell upon me for four or five years;
and when I turned within I was judged for all my former iniquities,
and my heart was still shown to me, that it was corrupt: but as I kept within,
to the Light in my conscience,
I was restrained from many actions which I had a will to do; and in the instant,
when I was doing any unrighteousness in actions or words, I was often stopped;
and when I saw that I did it not, a great joy arose in me:
but when I had done anything forwardly or rashly I was judged.
But this the teachers said was a natural conscience, that kept from sin,
and restrained it;
so I hearkened to their imaginations and slighted the Light as too low a thing,
that was but common grace, that preserved out of gross evils.
But they said the saints had a peculiar grace and faith; and so I hearkened unto them,
and was still convinced of sin.
Then they told me that the saints believed in Christ, and so sin was not imputed,
but his righteousness was accounted to them; and so I must seek him in the means,
as prayer, and receiving the sacrament, as they called it;
and they judged me a worthy communicant;
and in great fear I was lest I should eat unworthily;
and none could instruct me what the body of Christ was.

"`At one time I read all the Scriptures that spoke of Christ`'s sufferings.
The teachers said I must believe He suffered for me;
and I believed all that they called faith; yet I could not see how He died for me,
and had taken away my sin; for the witness in my conscience told me,
I was the servant of sin while I committed it:
they told me I must not omit that ordinance,
for thereby faith was confirmed and strength added.
So on the one hand they pressed it as a duty;
and on the other I saw that the Scripture said: "`He that eats unworthily,
eats damnation to himself.`"
I was in fear, though none could accuse me from without;
yet afterward a great fear fell upon me,
and I thought I had sinned against the Holy Spirit, and great trouble fell upon me.
Then they said, I had not come prepared;
and yet I had all the preparation that they had spoken of:
but they were all physicians of no value.

"`Then I fasted, and prayed, and walked mournfully in sorrow,
and thought none was like me, tempted on every hand: so I ran to this man, and the other;
and they applied promises to me; but it was only in words,
for the witness of Christ showed me that the root of iniquity stood,
and that the body of sin was whole: and, notwithstanding I was kept from gross evils,
still sorrow compassed me about, and I questioned all that ever I had had,
which they said was grace, repentance, and faith.

"`Then I told them there was guilt in me; and they said sin was taken away by Christ,
but the guilt should still remain while I lived,
and brought me the saints`' conditions who were in the warfare, to confirm it.
So I said in myself this was a miserable salvation,
that the guilt and condemnation of sin should still stand in me.

"`Thus I was tossed from mountain to hill, and heard them preach confusion;
and therefore I mattered not for them, and said,
surely this is not the ministry of Christ!
So I ceased long by fits, and did not mind them;
but kept still at Lome and in desert places, solitary, in weeping.
Everything I had done was laid before me, insomuch, that every thought was judged;
and I was tender, and my heart broken: and when I could sorrow most I had most peace;
for something spoke within me from the Lord; but I knew Him not then.
And they said,
that it was heresy to look for the word of the Lord to be spoken now in these days,
but only in the letter; so I regarded it not much;
yet often I was made to do many righteous things, by the immediate power and Word of God;
and then peace and joy sprang up in me, and promises were spoken,
that He would teach me Himself and be my God.
And often I obeyed contrary to my will, and denied my will:
but they told me this was legal to obey out of fear, and that it was slavery;
but that there was an evangelical obedience.
So I got above fear, and yet acted the former things, which they called ordinances;
and they said that was son-like obedience, and Christ had done all.

"`Then there appeared more beauty in those called Independents; and I loved them,
and so joined myself to them: and all the money I could get I purchased books with;
and I walked with and owned the Independents as more separate from the world;
and they pressed separation: but at the last I saw it was only in words,
that they would choose officers and members of themselves;
and so made an image and fell down and worshiped it.
Yet there was some tenderness in them at the first;
but the doctrine was the same with the world`'s, words without, of others conditions.

"`Then they whom they called Anabaptists appeared to have more glory,
and to walk more according to the Scripture, observing things written without:
and I went among them; and there was something I loved among them.
But afterwards, they denied all but such as came into their way,
as out of the fellowship of the saints, and doctrine of Christ.
And I saw the ground was the same; and their doctrine out of the life,
with the rest of the teachers of the world; and that they had separated themselves,
and made another likeness.
But still all said the letter was the word and rule; and Christ at a distance, without,
had done all.
Some of them holding free-will, others opposing, and all in their own will.

"`Still I loved them that walked honestly among all these.
But though I had seen and owned all that I had heard, except the figure,
which I saw was outward; and that was their greatest glory,
and I saw that they would have all fall down to it, else no communion;
yet I found no peace, nor guide.
Then some preached the doctrine of free grace, as they called it,
that all sin was done away, past, present, and to come;
that only believing in this doctrine and all is finished;
and so preached salvation to the first nature, and to the serpent that bore rule.
To this I hearkened a little, and so lost my condition within.
But still wheresoever I went, this was spoken in me:
"`His servant you are whom you obey;`" and so being overcome by sin,
I had no justification witnessed in me, but condemnation.

"`Then some preached Christ within, but they themselves were without; but yet they said,
all must be within, unto which my soul did cleave.
And they spoke of redemption and justification, and all within;
and of God appearing in man, and overcoming the power of the devil:
and the Light in my conscience, bore witness that it must be so;
and I was exceedingly pressed, to wait and find it so;
and something in me breathed after the Living God.
And I had a true love to all that walked honestly of what profession soever;
and I hated reviling one another, and that they should smite one another,
and persecute one another: and I always took part with the sufferer.
But still I saw, that though they spoke of things within, and of a power to come,
they enjoyed not what they spoke of; for the same fruits were brought forth.

"`At last I saw, that none walked as the ministers of Christ:
none that pretended to the ministry had any such gift, neither pastor, nor teacher;
nor were any of them such members as were in the apostles`' time.

"`So having passed up and down, hurried here and there,
I saw that all the teachers of the world sought themselves,
and fed poor people with dead names and deceit;
and that they were not the ministers of Christ.
I saw them all in deceit, who did not abide in Christ`'s doctrine;
and I got myself quit of most of them, for, ever as I dissented from their judgment,
they hated and persecuted me.

"`Now it was revealed in me, that the Lord would teach his people himself: so I waited,
and many things opened in me of a time at hand.
And sometimes I would have heard a priest; but when I heard him, I was moved by the Lord,
and his word in me spoke to oppose: and often as a fire it burned,
and a trembling fell upon me; yet I feared reproach, and so denied the Lord`'s motion.
And it was revealed in me to wait, and I should know his counsel.

"`And the word of the Lord was in me, that the time was at hand,
when the dead should hear the voice of the Son of God.
And it burned in me as a fire, that the day was near, when it should not be said,
"`lo here, nor there;`" but all the Lord`'s people should be taught of Him.
But still my mind ran out: and out of the fear into carelessness;
for I knew not the cross of Christ.
And yet, I say, I was wiser than the teachers that I met with in that generation.
I do not glory in it, for condemnation is passed on it all forever.
Yet still, I had ever, as my mind was turned to the Light, pure openings,
and prophecies of things to come: and a belief that I should see the day,
and bear witness to his Name.
And so when things opened so fast, the wisdom of the flesh caught them;
and I went up and down, preaching against all the ministry: and I also run out with that,
which was revealed in myself; and preached up and down the country,
of the fulness that was in the old bottle; and so was wondered after,
and admired by many, who had waded up and down as myself had:
and we fed one another with words; and healed up one another in deceit;
and all laid down in sorrow, when the day of the Lord was made manifest.
For I was overthrown, and my foundation swept away;
and all my righteousness and unrighteousness were judged, and weighed,
and found too light.

"`As soon as I heard one declare, that the Light of Christ in man, is the way to Christ,
I believed the eternal word of truth; and the light of God in my conscience sealed to it.
So not only I, but many hundreds more, who thirsted after the Lord,
but were betrayed by the wisdom of the serpent, were all seen to be off the foundation;
and all our mouths were stopped in the dust; and we all stood condemned in ourselves,
and saw our nakedness, and were ashamed;
though our glory was great in the eye of the world: but all was vanity.

"`As I turned my mind within, to the light of Jesus Christ, with which I was enlightened,
which formerly reproved me for all vanity,
and also as I owned it led me into all righteousness,
I saw it was the true and faithful witness of Christ Jesus; and then my eyes were opened;
and all things were brought to remembrance, that ever I had done;
and the dreadful day of the Lord fell upon me: sorrow and pain; fear and terror,
for the sight that I saw with my eyes.
In the morning I wished it had been evening,
and in the evening I wished it had been morning: and I had no rest,
but trouble on every side.
All that ever I had done was judged and condemned; and all things were accursed.
Then the lion suffered hunger.
My eyes were dim with crying; my flesh failed of fatness; my bones were dried,
and my sinews shrank.
I became a proverb to all; yes, to those who had been my acquaintance;
they stood afar off me: the pillars of heaven were shaken;
one woe poured out after another.
I sought death in that day, and could not find it; it fled from me.
I sought to cover myself any way, or with anything, but could not; and Babylon,
the mother of harlots, came into remembrance that day; and the sea dried up,
and all the merchants that traded with her stood afar off,
for the cup of fury was poured forth.
I would have run any where to have hid myself; but there was nothing but weeping,
and gnashing of teeth, and sorrow, and terror.
I roared out for the disquietness of my heart; and the kingdom was full of darkness.
I knew not the right hand from the left: I became a perfect fool, and knew nothing;
and as a man distracted.
All was overturned; I suffered loss of all.
All that ever I did, I saw was in the accursed nature.
Then something in me cried, "`just and true is His judgment.`"
My mouth was stopped; I dared not make mention of His name.
But as I bore the indignation of the Lord, something in me rejoiced:
the serpent`'s head began to be bruised; and as the judgment was pronounced,
something cried, "`just are you O Lord, in all your judgment!`"
And as I gave up all to the judgment, the captive came forth out of prison, and rejoiced:
my heart was filled with joy; and I came to see Him whom I had pierced:
my heart was broken.
Then I saw the cross of Christ, and stood by it; and the enmity was slain by it:
the new man was made; and so peace came to be made; and eternal life was brought in,
through death and judgment.
Then I received the perfect gift, which was given from God:
and the holy law of God was revealed unto me; and was written in my heart: and His fear,
and His word, which did kill, now made alive.

"`Thus it pleased the Father to reveal his Son in me through death;
and so I came to witness cleansing by his blood, which is eternal.
Glory unto his name tor ever!
And I have rest and peace in doing the will of God; and am entered into the true rest,
and lay down in the fold of God, with the lambs of God,
where the sons of God rejoice together, and the saints keep holy days.
Glory unto Him forever!`"
