== Chapter III.

[.chapter-synopsis]
* Francis Howgill Visits London in Company with Edward Burrough and Anthony Pearson
* Account of the First Meetings of Friends in London
* They Are Joined by John Audland, John Camm, and Richard Hubberthorne
* Francis Howgill and Edward Burrough Remain in London after Their Companions Leave That City

In the spring of 1654, Francis Howgill went to London in company with Edward Burrough,
and Anthony Pearson the justice before mentioned,
but who had now become a preacher of the truth as it is in Christ Jesus.
They are said to have been the first,
who publicly preached the doctrines of Friends in London.

A meeting was appointed at the request of Francis Howgill,
who had written by post from York on that account.
It was held on a first-day, at the house of Robert Dring,
in a close yard in Watling-street.
Before Francis Howgill and A. Pearson arrived, a great many people were assembled,
whom the former addressed.
As soon as he ceased many wild people came in, who made a great noise.
They went to Simon Dring`'s, in Moorfields in the afternoon,
where they met many people of honest, simple hearts,
to whose conditions they were much drawn forth to minister, and who received them gladly.
Edward Burrough is said to have been that day, at an assembly of a separate society.

Previously, however, to the arrival of these labourers in the Gospel,
the workings of the power of truth were felt by some
tender-hearted people in and about London;
and a few were convinced and turned to the Lord.
Two women who came out of the north, namely, Isabel Buttry and her companion,
became acquainted with Simon Dring of Moorfields,
and Amos Stodart who had been a captain in the parliament`'s army,
but having been convinced of the truth had left his military calling.
These women having in their possession,
printed copies of an Epistle addressed by George Fox,
"`to all that would know the way to the kingdom, whether they be in forms, without forms,
or got above forms,`" to direct people to turn the attention of their minds within,
where the voice of God is to be heard, dispersed them among such as would receive them;
and walking in company with Amos and Simon in the fields towards Stepney,
they were overtaken by Ruth Brown, who was then about sixteen years of age,
and who afterwards became the wife of William Crouch.
Isabel Buttry looked steadfastly on her, and gave her one of the epistles,
on reading which she was convinced of the truth,
and added to the small number who believed.
After this they, with Anne Downer, who afterwards married George Whitehead,
held private meetings at Robert Dring`'s house, in Watling-street,
and at Simon Dring`'s in Moorfields, in which Isabel Buttry sometimes spoke a few words;
but Anne Downer is said to have been the first woman of this society,
who preached publicly in London.

On the first-day week after the arrival of Francis Howgill and his companions,
they appointed another meeting in Moorfields,
for those only who appeared to be simple-hearted,
and who had been much borne down by the violence
of the people among whom they were mixed,
before the coming of these friends.
But to this meeting came many wild spirited people;
and after Anthony Pearson had said a few words,
a ranter stood up and spoke until Francis Howgill was grieved in spirit, and he,
under a sense of the power of God, stopped him: after which Anthony and he spoke again.
Then several men and women fell down on the ground, in a ranting spirit,
and confessed that their ministry was of God;
but Francis Howgill and his friends denied them and declared against them,
so that the simple-hearted ones were much comforted and strengthened.

The next first-day, they had another public meeting in Watling Street;
but before they got there a ranter spoke, and another opposed him,
and there was a great contest, so that the people were much troubled.
At length, under a sense of the power of the Lord, Francis Howgill stood up and spoke;
and all the others were silent.
The mouths of his fellow-labourers were afterwards opened in great power,
so that many owned their ministry.
In the afternoon many more came and there was strong opposition;
but Francis and his companions, after speaking to them for about two hours, withdrew,
and were followed into another room by the honest-hearted, whom they addressed;
being much concerned to get them separated from among the mixed multitude.

In a short time, John Audland, John Camm, and Richard Hubberthorne,
arrived in London and took part in the labours of the day.

Francis Howgill informs us,
that one day Edward Burrough and Richard Hubberthorne were at a place in the City,
called the Glass House, which was a great meeting place of the Baptists;
and that after Edward Burrough had spoken,
Richard Hubberthorne stood up and addressed the assembly;
but presently they shut him out and bolted the door.
Edward remained silent within, till another person had spoken,
and then he said a few words; but they stopped him,
and after a little dispute he left them.
The same day, John Camm was with a people who had been called Lockers,
whose hireling teacher had left them; and had afterwards been promoted.
Richard Hubberthorne went to him from the Baptists,
and they had liberty to speak for a good while and cleared their consciences,
Francis Howgill, with Anthony Pearson,
were the same day at a meeting of a people called Waiters, in Cheapside;
where a man was speaking when they went in, who soon ceased on seeing them.
Here the former spoke three quarters of an hour;
and one Colonel Rich then confessed that the Light was the guide,
but said that it led into innocency,
and that he looked for a greater which would lead into glory.
This was not satisfactory to them,
therefore Anthony Pearson said a few words on the subject;
after which Francis again addressed them;
and Edward Burrough coming in also spoke a few words;
after which they parted with the people in much love.

On the sixth day following, they appointed a meeting for those who were convinced:
and on first day,
Francis Howgill and Edward Burrough had a meeting at a large place called Ely-house,
the governor of which began to speak, but soon ceasing, another person, a ranter,
stood up in a pulpit and spoke a while;
so that they saw they were in danger of losing the opportunity,
Edward Burrough therefore stood up and addressed the meeting,
the people being very attentive.
After he had finished, the ranter spoke again; and Francis,
under a sense of the power of the Lord, then stood up and addressed them:
upon which the ranter and the rest of the people were silent for nearly an hour longer:
after which,
the ranter said the people could not but witness that he spoke
to their consciences as well as Francis and his companion;
but the people, with one consent, said he did not, and were very loving to them:
but the governor, perceiving that, in the eyes of the people,
his honour and that of the ranter were gone,
refused to let them have a meeting there in the afternoon;
so they appointed one in Watling Street.
The same day,
John Camm went to a great meeting of a society who were translating the Scriptures anew,
and were judging of them by their own reason.
At mid-day they all met again; and Richard Hubberthorne went to Friends`' meeting,
and Anthony Pearson and Francis Howgill to that of the Bible people,
and there they spoke a little;
but except they would dispute and be tried by the Scriptures, they would not hear them;
they therefore consented, and were furnished with wisdom,
so that they soon confounded their opponents.

Passing from them they were joined by Richard Hubberthorne,
and went to Edward Burrough who was at a steeple-house in Lombard Street,
which most of the high notionists in the City frequented.
They got to him before the priest had done; and after he had ceased,
Edward stood up on a seat and addressed the people for about an hour, with a loud voice,
and in much power; they being very still and calm.
When he had finished, Francis also addressed them;
and they cleared their consciences and went away.
The same afternoon, John Camm was at a meeting of Baptists,
where he had an opportunity of preaching the Truth to them.
In the evening they all met again; and closed the day in peace,
in their Heavenly Father`'s love.

After a short time, Anthony Pearson went into the county of Durham; and John Audland,
John Camm, and Richard Hubberthorne into Oxfordshire;
but Francis Howgill and Edward Burrough still remained in London, labouring diligently;
having three or more meetings every week,
larger than could be contained in any place they could conveniently obtain for the purpose.

One fourth-day, they had a meeting in Southwark,
in a large room where the Anabaptists met on first-days; several of whom,
with many hundreds of people attended.
The Anabaptists, after it, fell out about them: those who heard them pleaded for them,
while others who were absent were offended,
and blamed those who gave them liberty to use the room;
and one of the Anabaptist teacher`'s who had been in the north,
brought many false reports respecting Friends, which those who were at the meeting,
would not give credit to.
This occasioned many of the Anabaptist congregation to secede,
which made the others greatly afraid of Friends.

The ministerial labours of these devoted servants
of the Lord were blessed with signal success;
being attended with a convincing power, impressing awful considerations,
and awakening the consciences of the audience to a sense of their conditions,
and to earnest desires after salvation.
Being prepared for the work of the ministry,
by the previous work of inward sanctification,
and believing themselves "`called of God as was Aaron,`" to that arduous undertaking,
they were eminently qualified for the service in which they were engaged;
not only possessing a sound understanding and a sufficient share of literature,
but the superior qualification of that experience
of the quickening power of inward religion,
which they endeavoured to recommend and propagate;
a religion not amusing the head in curious speculations, but purifying the heart,
and cleansing the conscience from dead works, to serve the Lord in newness of life.
