== Chapter IV.

[.chapter-synopsis]
* Francis Howgill and Edward Burrough visit Bristol
* Are examined by the magistrates, and discharged
* After which a warrant is issued to apprehend them and others as Franciscans

In the autumn of this year, 1654,
Francis Howgill and Edward Burrough left London for Bristol,
after having a meeting with many of their friends who came to take leave of them.
In this meeting they commended their friends to the Lord, to whom they had directed them;
and charged them to meet together.
It was a time of great brokenness of heart;
the tendering power of God being witnessed among them,
so that the recollection of it often raised the hearts
of many of them in thankfulness and praise to God.

On the first-day after the arrival of Howgill and Burrough in Bristol,
they had a meeting in the castle, at which were many hundreds of people.
After it was over they went out, hoping to get away from the multitude;
but the people followed them along the streets to the house of a captain,
which was filled with them till late in the evening.
Every day in the week these friends had meetings in or about the city;
and on the first-day following, they had one in the house of one captain Bishop;
probably George Bishop who became convinced of the Truth,
and suffered imprisonment for it.
The rooms in this house were large, but not sufficiently so for the meetings;
and therefore they went in the afternoon to a place called the fort,
where about two thousand persons were assembled;
among whom were many great men and women.
All the people were very still,
though Howgill and Burrough could scarcely raise
their voices so as to be heard by the most distant;
and the people were so unwilling to leave them,
that they were obliged to go into the house of a captain,
and hide themselves in a private chamber.

These things were noised through the city,
and the priests and magistrates were soon in an uproar,
seeking to find something against these labourers in the Gospel.
Two priests went to hear them in order to entrap them, but were disappointed.
On the second-day of the week they went into the city; to the house of a merchant;
and the mayor, aldermen, justices of the peace, and priests assembled in the hall;
and sent a sergeant to desire them to come to the council, where they went freely,
many captains and great men of the city accompanying them.
When they reached the place, a great concourse of people was gathered together;
they were therefore taken into an inner chamber,
into which many persons of respectability who were kindly disposed to them went,
but were not permitted to stay; while their opposers were freely admitted.
Howgill and Burrough informed the magistrates,
that they were come there according to their request;
and the magistrates then queried of them, if they knew to whom they spoke.
They answered, that they believed they were before the magistrates or rulers of the city.
The magistrates were displeased, that they neither bowed to them, nor put off their hats;
but they informed them, that they did not omit doing so in contempt of authority,
but for conscience`' sake.

The magistrates then asked of them their names and country, which they declared to them;
telling them also, that they had been in London about a quarter of a year.
The magistrates next inquired respecting their coming to Bristol, to which they answered,
that they had the commandment and motion of the Lord, to bear witness to his Name,
and to declare the Gospel committed to them.
The priests then began to ask them questions;
but they refused to answer any persons except the magistrates,
to whom they signified their readiness to answer.
These then enquired whether their call was mediate or immediate; to which they replied,
immediate.
They were then desired if they had an immediate call to declare it;
Francis therefore told them what he had been, and what he then was,
and informed them that he, and his companion had witnessed the same call,
which Abraham had to leave his country and his habitation;
and had left their habitations at the command of God.

The magistrates hearkened to him quietly for about a quarter of an hour.
They then queried if the friends could work miracles: they answered,
that they should not boast of those things; but on being urged, they stated,
that many persons could bear witness,
that by their ministry many had been turned from darkness to Light,
and from Satan to God.
The priests then enquired whether they accused all the ministers in England;
and they told them, that there were many ministers of Christ in England,
and with them they had unity; but all hirelings,
and those who sought their gain from their quarter they denied.
The priests pleaded for hire, and said, that Francis and Edward dishonoured the Gospel;
that the Light was natural; and that every one had it not,
which was contradictory to their own declaration that it was natural.
After much striving and contending,
when they found that they could not ensnare the prisoners,
they consulted together and said, that the friends had held tumultuous meetings;
to which one of their own number answered, that there were many godly, honest people met,
and without tumult.

When the magistrates could find nothing against them,
they commanded them to depart out of the city.
To this they answered: "`We came not in the will of man, nor stand in the will of man;
but when He moves us to depart, who moved us to come here, we shall obey;
but your wills we cannot obey, for your will is no law.
If we are guilty of the transgression of any law, let us suffer by it;
but rather than we will transgress the righteous law of God, written in our hearts,
by subjecting ourselves to your wills and lusts,
we shall choose to walk in the law of God,
and to suffer under your wills what you can lay upon us.
We are free born Englishmen, and have served the Commonwealth in faithfulness,
being free in the presence of God from the transgression of any law.
To your commands we cannot be obedient; but if by violence you put us out of the city,
and have power to do it, we cannot resist.`"
Having said this they went out of the court, but tarried in the city till night;
and the next day returned and walked in the streets.

After this, they had several very large meetings;
it being supposed that there were at one of them, about three thousand persons.
They stayed about seven weeks in and about Bristol, labouring diligently;
and many received the Truth which they preached.
For the last three weeks of their stay,
they had the company and joint labours of John Audland and John Camm,
who had also been there before them,
and whom they left in this extensive field of labour.
Some time after they left Bristol,
the magistrates issued the following warrant to the constables of each ward of that city,
under pretension of an information,
the absurdity of which must appear to every unprejudiced reader,
as the parties named in it were well known to be natives of England.
But the spirit of persecution which raged in those days, seemed so blind that nothing,
however improbable or foolish,
if it could be turned to the disadvantage of this harmless, but despised people,
was thought too low to be pressed into service against them,
by many of those who ought to have been a terror to evil doers,
and a praise to them who do well.

[.embedded-content-document.legal]
--

[.signed-section-context-open]
City of Bristol.

[.salutation]
To the constables of the peace of the ward of +++_______+++, and every of them.

Forasmuch as information has been given unto us upon oath,
that certain persons of the Franciscan order in Rome,
have of late come over into England, and under the notion of Quakers,
drawn together several multitudes of people in London.
And whereas, certain strangers going under the names of John Camm, John Audland,
George Fox, James Nayler, and Edward Burrough, and others unknown,
have lately resorted to this city, and in like manner, under the same notion of Quakers,
drawn multitudes of people after them, and occasioned very great disturbances among us;
and forasmuch, as by the same information, it appears to us to be very probable,
and much to be suspected, that the said persons so lately come here,
are some of those that came from Rome, as aforesaid.--These are therefore,
in the name of his Highness the Lord Protector,
to will and require you to make diligent search throughout
your ward for the aforesaid strangers,
or any of them, and all other suspected persons,
and to apprehend or bring them before us, or some of us,
to be dealt with according to law.
Hereof fail not.
Given the 25th of January, 1654.

[.signed-section-signature]
Signed, John Gunning, Mayor, Gabriel Sherman, William Gunn, Henry Gibbs, Joseph Jackson,
George Hellier, John Lack, Gabriel Sherman, Richard Vickris.

--

While Francis Howgill and Edward Burrough were in Bristol,
twelve Baptists came out of Wiltshire to encounter them, who were put to flight;
and reported on their return home, that Friends were cursers and swearers,
and denied Christ and the Scriptures; so that in consequence, when,
on their return toward London,
Francis and Edward came to the town where they had spread the report,
the people were very fierce upon them.
However, they had a meeting in the market-place; on going to which,
they felt themselves very low and weak: but when the people were come together,
they felt the Power of the Lord so to arise, that they spoke for two hours irresistibly,
and cleared the Truth.
Two of the Baptists then spoke, and they disputed with them for four hours,
at the expiration of which they parted; the Baptists laying aside their boasting.
A justice of the peace who was present on this occasion,
declared that he never heard any who spoke like Howgill and Burrough,
and invited them to his house, to which they went the following day.
The mayor of the town went to them in the evening,
and confessed that they spoke the Truth; and that, if he should not witness to it,
his conscience would witness against him.
They had many meetings in this county;
and among those who were convinced of the Truths they taught,
were a justice of the peace and his wife, of the name of Stookes,
who desired them to go to their house, where they had a large meeting,
and stayed two days; after which, they set out for London:
the justice kindly sending his man and horses with them, fifteen miles on their journey.
