== Chapter VI.

Francis Howgill visits Kent--Returns to London--Goes to Ireland,
and joins Edward Burrough--They are banished from Ireland by Henry Cromwell

Francis Howgill spent five weeks in Kent about this time,
and had meetings every day but two.
Here he was attacked with an ague, and brought near to the grave.
"`But,`" he says, "`the Lord for his work`'s sake gave me strength,
and many great meetings I had in that county; the magistrates being moderate.`"

He returned to London again after this visit;
and so great did the desire to hear the doctrine preached by Friends become,
that they frequently had about twenty meetings in a week;
feeling that the labourers were few in proportion to the harvest.

After remaining a while in London,
Francis Howgill believed it required of him to pay a religious visit to Ireland.
Respecting his impression of duty on this occasion, it appears by a memorandum,
dated the 7th day of the 4th month,
that he believed himself commissioned to go to Dublin with Edward Burrough;
and it was strongly impressed upon his mind that a door was opened for them,
and that the living presence of the Lord would go before them,
and that his righteousness would be their reward;
that his everlasting blessing and eternal power would be with them;
and that He would open their mouths in wisdom, in utterance and understanding;
that His power would encompass them as a wall of brass;
and that many should bless them in his name, and say: "`What has God wrought!`"

By a memorandum left by Edward Burrough it appears,
that he also received a similar impression, on the 10th day of the 4th month,
to which he submitted on the 30th of the same, not knowing whether his brother,
by which it is presumed he meant Francis Howgill, should go with him or not;
and that he had the comforting assurance, that nothing should befall him,
but what should be permitted of the Lord; and that his life should be preserved,
although it was required of him to give it up freely to the keeping of Him,
who called him to the great work of declaring his Word in that nation.

They spent about three months in Dublin without being disturbed,
though they omitted no opportunity of declaring the doctrine of Truth;
and a small meeting was settled there.
After this they believed it their duty to part, and travel in different directions,
Francis going to Kilkenny, Waterford, Youghall, and Cork; at each of which places,
meetings were gathered, and all seemed as a plain before them.
After being separated five months, he wrote to Edward Burrough,
desiring him to join him in Cork, where Francis often had great liberty in public.
He had often great contests with the Baptists;
and many were raised up in the Lord`'s power, to bear witness daily against the priests,
so as to become a torment to them.
The governor was moderate toward him, and his family well disposed;
and many officers of different descriptions went to hear him.
At Bandon there was a meeting gathered, and at Kinsale also,
where the governor was kindly disposed to him; and among those who were convinced,
were some soldiers.
At this place Francis had many meetings in the garrison,
which greatly enraged the priests,
who informed against the officers that had received him,
and rode to Dublin to procure an order to examine him.
They sent him bound to Dublin in the eleventh month;
but the justices to whom the order was directed sent for him to Cork,
to which place he went;
and they seeing into the malice of the priests set him at liberty: on which,
the priests lodged an information against them also.
At Cork he was again joined by Edward Burrough;
and the priests obtained an order from Henry Cromwell, then Lord Deputy of Ireland,
to banish them out of that nation;
and a guard of soldiers was ordered to conduct them from place to place,
till they were shipped off.
The soldiers were kind to them, and suffered them to have meetings where they came;
so that several received the Truth.

