== Chapter VIII.

[.chapter-synopsis]
* Francis Howgill is summoned before the justices of the peace at Hernial, and committed to Appleby jail
* Is recommitted for refusing to take an oath
* Being allowed liberty to settle his affairs, he visits justice Duckett, and utters a prophetic denunciation against him
* Notices of the fulfilment of his prophecy

Francis Howgill did not remain at liberty long,
after the decease of his friend and fellow-labourer, Edward Burrough;
for in the latter part of the fifth month, 1663, he was sent for out of the market,
at Kendal, in Westmoreland, where he happened to be about his ordinary occasions;
being summoned by the high-constable, to appear before the justices of the peace,
then present at a tavern, who tendered to him the oath of allegiance and supremacy;
and because, for conscience`' sake, in obedience to the commands of Christ,
he could not swear, they committed him to Appleby jail, where they kept him,
in a smoky hole, from the sessions till the court session; at which he appeared,
and had the same oath tendered to him in court, by the judges;
and for not taking it he was indicted,
but had liberty to answer to the indictment the next court session.
In the mean time a jail-delivery occurring, he was, in order to ensnare him,
required to enter into bond for good behaviour, which he refusing,
the judges again tendered him the oath;
and he was recommitted to prison for persevering in his testimony against all swearing.

It is probable, that it was in the interval between the time of his being recommitted,
and the following court session, that the justices indulged him with a few days liberty,
to settle his affairs;
in the course of which time he felt himself constrained
to visit a justice of the name of Duckett,
who lived at Grayrigg-hall.
He was a great persecutor of Friends,
and also one of the magistrates concerned in committing him.
Francis Howgill was accompanied by a Friend whose initials
were J. D. according to one of the accounts of this visit,
of which the editor is in possession of three,
which he has received through different channels, all to the same import.
By these it appears that the justice was much surprised at seeing Francis,
and said to him: "`What is your will now Francis?
I thought you had been in Appleby jail.`"
Francis replied to this effect: "`No, I am not;
but I am come with a message from the Lord.--You have persecuted the Lord`'s people;
but His hand is now against you, and He will send a blast upon all that you have:
and your name shall rot out of the earth; and this your dwelling shall become desolate,
and a habitation for owls and jackdaws.`"

When Francis had delivered this message, the justice trembled, and said:
"`Francis are you in earnest?`"
Francis replied: "`Yes I am in earnest; it is the Word of the Lord to you;
and there are many now living, who will see it.`"

This prediction appears to have been remarkably fulfilled;
for according to the testimony of James Wilson,
who was an approved minister among friends, and who lived at one time at Grayrigg Foot,
in Westmoreland, and afterwards at Darlington, in the county of Durham;
this justice Duckett had several children, and all his sons died without issue,
and some of them came to poverty: James Wilson had also himself,
repeatedly given alms at his own door, to a woman who was the last of the Duckett family.

Burns, the historian of Westmoreland and Cumberland,
also speaking of this family in allusion to Anthony Duckett, Esq.
and the Grayrigg-hall estate, about the year 1670, says: "`Not long after this,
the said Anthony sold the estate to Sir John Lowther, and died without issue;
all his brothers also died without issue male; and the name and family, in Westmoreland,
is now, 1777, extinct.`"
"`Grayrigg-hall, being the ancient manor house, was a strong old building,
in a quadrangular form, adapted more for defence than convenience.
It is now, 1777, totally in ruins,
most of the lead and timber thereof having been removed to Lowther.`"

Since the time of Burns, the ruins which "`owls and jackdaws`" had long inhabited,
have been removed;
and a farm house has recently been erected upon the site of the old hall.
