== Chapter IX.

An account of Francis Howgill`'s examination, trial,
and sentence to imprisonment for life.

The account of the examination of Francis Howgill, and of his trial,
is given at the commencement of a volume containing his works, entitled,
The Dawnings of the Gospel Day from which the following is extracted.

Being at the court session, he had liberty to speak freely before the judges,
and great men of the country, and many others; indeed the Lord made him without fear,
and girded his heart with strength, and opened his mouth in wisdom,
so that he gained upon his adversaries; for which glory is given to God,
who was a present help to him in time of need.

Before the judges sat, he spoke to the clerk of the court session,
and told him he did not know whether they expected his appearance then or not.
The clerk informed him, that he had done well to come there,
and told him that he would acquaint the judge,
and he should only engage him to appear next court session,
to answer to the indictment against him, and that he should not then appear in court.
Francis bid him do what he would.
In the mean time Sir Philip Musgrave, so called, a great adversary to the Truth,
and the great and chief prosecutor of Francis, had informed the judge against him,
that he was a dangerous person, a ringleader,
and a keeper of meetings of dangerous consequence,
and destructive of the peace of the nation; so they concluded he should appear in court,
and the clerk informed him, and told him about what time he should be called.
So the court began, and judge Twisden gave the charge to the grand jury,
in which he said: '`There was a sort of people who,
under pretence of conscience and religion,
seemed to build upon the king`'s declaration from Breda,
and under colour of this hatched treasons and rebellions;`'
and gave the jury charge to enquire and present such,
that the peace of the nation might be preserved.
So they empanneled the jury, and Francis was called to the bar;
and the judge speaking calmly to him, said:
the face of things was much altered since the last court session;
and he then made a speech to him and the country, telling him that all sects,
under pretence of conscience, did violate the laws, and hatched rebellions; not, says he,
that I have anything to charge you with;
but seeing the oath of allegiance was tendered to you the last court session,
and you refused to take it,
it was looked upon that such persons were enemies to the king and government.
He also said: "`I will not trouble you now to answer to your indictment,
but I must do that the next court session;
in the mean time you must enter into recognizance for good behaviour.`"
To which Francis answered:
"`I desire liberty to speak;`" which he had without interruption, and said as follows:--

Francis Howgill.--Judge Twisden, you very well know upon how slender an account or none,
I was brought before you the last court session,
where you were pleased to tender me the oath of allegiance, though I believe both you,
and the rest of the court did know,
it was a received principle among us not to swear at all: many reasons I gave you then;
many more I have to add if I may have audience; for it may appear to you an absurd thing,
and obstinacy in me to refuse it, if I should not render a reason.
I am none of those that make religion a cloak of maliciousness,
nor conscience a cloak to carry on plots or conspiracies:
the Lord has redeemed me and many more out of such things;
and seeing I am engaged to appear at the next court session,
I desire no further thing may be required of me.

Judge.--You must enter into bond this dangerous time, and therefore consider of it,
and tell me now, or before the court session has ended.

The second day of the court sessions he was called again.

Francis Howgill.--Seeing you are pleased to let me answer to my indictment,
which I am willing to do: I have been of good behaviour, and shall so continue;
but it seems a hard thing to me and full of severity,
seeing I am obliged to appear to answer an indictment of so high a nature,
if prosecuted against me, which, tends to the loss of my liberty for life,
and my estate forever.
I hope the court will not envy my liberty for five months.

Judge Turner.--We do not desire your imprisonment if you will be of good behaviour.

Francis pressed further that they would not put him upon giving bond for good behaviour,
knowing himself to be so bound by the Truth that he could not misbehave himself.
Daniel Fleming, another persecuting justice,
had framed another indictment against him for meeting, and stood up,
fearing the snare of giving bond would not hold, and said as follows:

Daniel Flemming.--My lord, he is a great speaker;
it may be the Quakers cannot do without him.

This kind of phrase, not uncommon in the north of England,
implies that the persons referred to, can not do without the person spoken of.

Judge.--Let him be what he will, if he will enter bond.

Francis said, that he had nothing to accuse himself of,
for his conscience bore him witness that he loved peace, and sought it with all men.

Both Judges.--"`What do you tell of conscience, we meddle not with it;
but you contemn the laws, and keep great meetings, and go not to church.

Francis Howgill.--We are fallen in a sad age, if meeting together peaceably without arms,
or force, or intention of hurt to any man; but only to worship God in spirit,
and exhort one another to righteousness;
and to pray together in the Holy Spirit as the primitive Christians of old,
should be reckoned a breach of peace and misbehaviour.

Judge Twisden.--Do you compare these times with them; they were heathens that persecuted;
but we are Christian magistrates.

Francis Howgill.--It is a doctrine always held by us,
and as received a principle as anything we believe,
that Christ`'s kingdom could not be set up with carnal weapons,
nor the Gospel propagated by force of arms, nor the Church of God built with violence;
but the Prince of Peace was manifested among us, that we should learn war no more,
but should love enemies, and forgive them that do evil to us.

Philip Musgrave stood up and said: My lord, we have been remiss towards this people,
and have striven with them, and put them in prison again and again, and fined them;
and as soon as they are out they meet again.

Then stood up John Lowther, called a justice and said: My lord, they grow insolent;
notwithstanding all laws and the execution of them, yet they grow upon us;
and their meetings are dangerous.

Philip Musgrave then stood up again, seconded by Justice Flemming, so called,
and produced a paper, in great capital letters, which be gave to the judge; and told him:
"`That it happened some Quakers were sent to prison, and one of them died at Lancaster;
and they carried his corpse through the country, and set that paper upon the coffin:
'`This is the body of such a one, who was persecuted by Daniel Flemming till death.`"

Judge.--We have spent much time with you; I will discourse no more.

Francis Howgill.--I acknowledge your moderation towards me, allowing me liberty to speak;
I shall not trouble you much longer:
I shall be willing to appear to answer to the indictment at the court sessions; and,
in the mean time, to live peaceably and quietly as I have done, if that will satisfy.

Judge.--You must enter into bond, to come at no more meetings.

Francis Howgill.--I cannot do that: If I should, I were treacherous to God,
and my own conscience; and the people and you, would but judge me a hypocrite.

They were reluctant to commit him, yet at last they did.
Francis turning about to the country people, said: "`The fear of God be among you all.`"
The hearts of people were tender towards him,
and some were very loving and affectionate to him.

Being thus committed on the 23rd of 1st month, 1664,
he was detained a prisoner about five months;
and a great part of the time of this imprisonment kept very strictly,
a charge being giving by the justices several times,
that none should be suffered to speak with him; and the jailer being a cruel man,
was ready to execute their orders to the utmost,
and kept him so close that none were suffered to come to him or speak with him,
but those who got secretly to him, without the jailer`'s knowledge:
all which he bore patiently; and never opened his mouth to complain of.
And when the time of the court sessions came,
he got liberty to speak with the clerk of the sessions, who told him,
that he must prepare himself to come to trial.
He said, he was prepared, but thought that all he could say would avail little;
believing they purposed to prosecute him with all severity, which proved to be the case;
for the country justices who began to prosecute him, had incensed the judges against him.
However, he endeavoured all he could to convince them of his innocency;
and to that end drew up the substance of the oath into several heads,
which he could subscribe to, though he could not swear, and delivered it to the court.

He drew up another paper, addressed to judge Turner,
showing him and the court the cause of his first commitment,
and the former proceedings against him; and how unequal it was,
that they waved the other statutes lately made against nonconformists,
and prosecuted him upon a statute formerly made against popish recusants.
In the same paper he also signified, that he was a man of a tender spirit,
and feared the Lord from a child; and had never taken any oath of allegiance;
and was not in any evil intent to the king`'s person or government, either in thought,
word, or deed; but that merely upon a spiritual and conscientious account,
he could not swear, being otherwise persuaded of the Lord.
That he could not swear, seeing it was against the command of Christ,
and the apostles`' doctrine.
He also declared,
that he was able to make it evident to be against the example of the primitive Christians,
for several hundred years and so no new opinion;
and that he did neither in willfulness nor obstinacy refuse it,
being sensible of the damage that would come thereby,
if they prosecuted him upon that statute; he having a wife and children,
and some small estate, which, he knew lay at stake in the matter: but he said,
if it were his life also he could not revolt from,
or deny that which he had most certainly believed in; but if any could convince him,
that he was in error, either by Scripture or reason, he had an ear to hear;
and therefore, all these things considered,
he desired he might be dismissed from those his strait bonds,
and from their persecution of him upon that account.
Both these papers his wife delivered to the clerk, and he to the judge;
and they were given to the justices, and read before Francis was called into the court.
In these papers he had come as near to what they desired, as he could in the Truth,
in order that he might leave them the more without excuse;
but all he could do would not prevail with them,
for they were determined to do their utmost against him.

At the court sessions, held at Appleby the 22nd and 23rd of 6th month, 1661.
Francis Howgill being called to the bar, the judge spoke moderately, and said:
here is an indictment against you for refusing to take the oath of allegiance:
so you must plead to it either guilty or not guilty.

Francis Howgill, with a heart girded up with strength and courage, said: '`Judge Turner,
may I have liberty to speak and make my defence,
for I have none to plead my cause but the Lord.`'

Judge.--You may.

Francis Howgill.--I will lay the true state of my case,
and of the proceedings against me from the first, before you,
seeing judge Twisden is not here, who had knowledge of all the proceedings hitherto.
I am a countryman, born and brought up in this county; my carriage and conduct are known,
how I have walked peaceably towards all men, as I hope my countrymen can testify.
About a year ago, being at my neighbouring market town,
about my reasonable and lawful occasions,
I was sent for by a high constable out of the market, to the justice of peace,
before whom I went; and when I came there, they had nothing to lay to my charge,
but fell to ask me questions about our meetings to ensnare me;
and when they could find no occasion, they seemed to tender the oath of allegiance to me,
though they never read it to me, neither did I positively deny it;
yet they committed me to prison: and so I was brought here to this court session;
and then the court order by which I was committed was called for, and the judge, read it,
and said to the justices it was insufficient; nevertheless,
Judge Twisden tendered the oath of obedience to me.
Many things I did allege then, and many more I have to say now, if time will permit:
from that time I was under an engagement to appear at the next court sessions,
and so was called, and did appear at the last jail delivery;
and a further obligation was required of me for good behaviour,
which I could not give lest I should be brought into a further snare;
and since that time, I have been committed prisoner these five months;
some of which time, I have been kept under great restraint,
my friends not permitted to speak to me.
Thus briefly I have given you an account hitherto,
and as to the path the substance thereof, with the representation of my case,
is presented unto the court already, unto which I have set my hand;
and also shall in these words testify the same in open court, if required;
and seeing it is the very substance the law does require, I desire it may be accepted,
and I cleared from my imprisonment.

Judge.--I am come to execute the law; and the law requires an oath, and I cannot alter it.
Do you think the law must be changed for you, or only for a few?
if this be suffered the administration of justice is hindered; no action can be tried,
nor evidence given for the king, nor any other particular case can be tried;
and your principles are altogether inconsistent with the law and government.
I pray you show me which way we shall proceed; show me some reason,
and give me some ground?

Francis Howgill--I shall.
In the mouth of two or three witnesses every truth is confirmed;
and we never deny to give,
and still are ready to give evidence for the king wherein we are concerned;
and in any other matter for the ending of strife between man and man,
in truth and righteousness; and this answers the substance of the law.

Judge.--Is this a good answer think you, whether to be given with or without oath?
The law requires an oath.

Francis Howgill--Still evidence is,
and may be given in truth according to the substance of the law,
so that no detriment comes unto any party,
seeing that true testimony may be borne without an oath;
and I did not speak of changing the law;
yet seeing we never refused giving testimony which
answers the intent and substance of the law,
I judged it was reasonable to receive our testimony,
and not to expose us unto such sufferings,
seeing we scrupled an oath only upon a conscientious account,
in tenderness of our consciences,
for fear of breaking the command of Christ the Saviour of the world; which, if we do,
there is none of you able to plead our cause for us with Him.

Judge.--But why do you not go to church but meet in houses and private conventicles,
which the law forbids?

Francis Howgill.--We meet only for the worship of the true God, in spirit and truth,
having the primitive Christians for our example;
and to no other end but that we may be edified, and God glorified;
and when two or three are met together in the name of Christ,
and He in the midst of them, there is a Church.

Judge.--That is true; but how long is it since you have been at church,
or will you go to the church the law does allow?
give me some reasons why you do not go.

Francis Howgill.--I have many to give you if you have patience to hear me: first,
God dwells not in temples made with men`'s hands: second,
the parish house has been a temple for idols, that is, for the mass and the rood;
and I dare have no fellowship with idols, nor worship in idols temples:
for what have we to do with idols, their temples and worship.

Judge.--Were there not houses called the houses of God, and temples?

Francis Howgill.--Yes, under the law;
but the Christians who believed in Christ separated from these;
and the temple was made and left desolate; and from the gentiles`' temples too,
and met together in houses, and broke bread from house to house;
and the Church was not confined then to one particular place, neither is it now.
Many more things I have to say.

The judge interrupted.

Judge.--Will you answer to your indictment?

Francis Howgill.--I know not what it is.
I never heard it, though I have often desired a copy.

Judge.--Clerk, read it.
So he read it: That Francis Howgill had willfully, obstinately,
and contemptuously denied to swear when the oath was tendered.

Francis Howgill.--I deny it.

Judge.--What do you deny?

Francis Howgill.--The indictment.

Judge.--Did not you deny to swear; and the indictment convicts you that you did not swear?

Francis Howgill.--First, I gave unto the court the substance of the oath, as you all know.
Secondly, I told you I did not deny it out of obstinacy or willfulness,
neither in contempt of the king`'s law or government;
for my will would rather choose my liberty than bonds;
and I am sensible it is likely to be a great damage to me.
I have a wife and children, and some estate, which we might subsist upon,
and do good to others; and I know all this lays at stake; but if it were my life also,
I dared not do but as I do, lest I should incur the displeasure of God.
And do you judge I would lose my liberty willfully, and suffer the spoiling of my estate,
and the ruining of my wife and children, in obstinacy and willfulness?
Surely no.

Judge.--Jury, you see that he denies the oath, and he will not plead to the indictment,
only excepts against it because of the form of words; but you see he will not swear,
and yet he says he denies the indictment, and you see upon what ground.

Then they called the jailer to witness and swear,
that the last court session he did refuse, etc. and the jury without going from the bar,
gave in the verdict, guilty; and then the court broke up.
The next day, towards evening, when they had tried all the prisoners,
Francis was brought to the bar to receive his sentence.

The judge stood up, and said:--Come, the indictment is proved against you,
what have you to say why sentence shall not be given?

Francis Howgill.--I have many things to say, if you will hear them.
First, As I have said, I denied not out of obstinacy or willfulness,
but was willing to testify the truth in this matter of obedience,
or any other matter wherein I was concerned; Second,
Because swearing is directly against the command of Christ.
Third, Against the doctrine of the apostles.
Fourth, Even some of your principal pillars of the Church of England, as Bishop Usher,
sometime Primate of Ireland, said in his works,
the Waldenses did deny all swearing in their age,
from the command of Christ and the apostle James, and it was a sufficient ground;
and Doctor Gauden, late Bishop of Exeter, in a book of his.
I lately read, cited very many ancient fathers,
to show that for the first three hundred years Christians did not swear;
so that it is no new doctrine; to which the court seemed to give a little ear,
and talked one to another, and Francis stood silent.

Then the judge said:--Sure you mistake?

Francis Howgill.--I have not the book here.

Judge.--Will you say upon your honest word they denied all swearing?

Francis Howgill.--What I have said is true.

Judge.--Why do you not come to church and hear service, and be subject to the law,
and to every ordinance of man for the Lord`'s sake?

Francis Howgill.--We are subject, and for that cause we do pay taxes, tribute,
and custom; and give unto Caesar the things that are his, namely, honour and obedience:
and if you mean the parish assembly, I tell you faithfully, I am persuaded,
and upon good ground, their teachers are not the ministers of Christ,
neither their worship the worship of God.

Judge.--Why it may be for some small things in the service you reject it all?

Francis Howgill.--First, it is manifest they are time servers;
one while preaching up that for Divine service to people,
which another while they cry down as popish, superstitious, and idolatrous;
and that which they have preached up twenty years together,
make shipwreck of all in a day; and now again call it Divine,
and would have all compelled to that themselves once made void.

Judge.--Why never since the king came in.

Francis Howgill.--Yes, the same men that preached it down once, now cry it up;
so they are so unstable and wavering that we cannot
believe they are the ministers of Christ.
2ndly.
They teach for hire, and live by forced maintenance, and would force a faith upon men,
contrary to Christ and the apostle`'s rule,
who would have every one persuaded in his own mind, and said:
'`whatsoever is not of faith is sin;`' and yet they say, faith is the gift of God,
and we have no such faith given; but yet they would force theirs upon us;
and because we cannot receive it,
they cry '`you are not subject to authority and the laws;`' and nothing but confiscations,
imprisonment, and banishment are threatened; and this is their greatest plea.
I could mention more particulars.

Then the judge interrupted.

Judge.--Well, I see you will not swear, nor conform, nor be subject,
and you think we deal severely with you; but if you would be subject we should not need.

Francis Howgill.--I do so judge indeed,
that you deal severely with us for obedience to the commands Of Christ; I pray you,
can you show me how any of those people for whom the act was made,
have been proceeded against by the statute?
though I envy no man`'s liberty.

Judge.--O yes!
I can instance you many tip and down the country that are premunired.
I have done it myself, pronounced sentence against several.

Francis Howgill.--What, against Papists?

Judge.--No.

Francis Howgill.--What, against Quakers?
so I have heard indeed:
so then that statute which was made against Papists you let them alone,
and execute it against the Quakers.

Judge.--Well, you will meet in great numbers, and do increase;
but there is a new statute which will make you fewer.

Francis Howgill.--Well, if we must suffer, it is for Christ`'s sake, and for well doing.

Francis then being silent, the judge pronounced the sentence, but spoke so low,
that the prisoner, though near to him, could scarcely hear it.
The sentence was: "`You are put out of the king`'s protection,
and the benefit of the law; your lands are confiscated to the king during your life,
and your goods and chattels forever; and you to be a prisoner during your life.

Francis Howgill.--"`A hard sentence for my obedience to the commands of Christ.
The Lord forgive you all.`"

So he turned from the bar; but the judge speaking he turned again,
and many more words passed to the same purport as before.

At last the judge rose up, and said:--Well, if you will yet be subject to the laws,
the king will show you mercy.

Francis Howgill.--The Lord has showed mercy unto me;
and I have done nothing against the king, nor government, nor any man,
blessed be the Lord, and therein stands my peace; for it is for Christ`'s sake I suffer,
and not for evil doing.

And so the court broke up.
The people were generally moderate, and many were sorry to see what was done against him;
but Francis signified how content and glad he was,
that he had anything to lose for the Lord`'s precious Truth,
of which he had publicly borne testimony,
and that he was now counted worthy to suffer for it.

That part of the sentence consigning him to imprisonment during life,
was not supported by the act of parliament,
and was afterwards clearly proved in the case of George Fox,
before judges Hales and Wile; see Richard Davie`'s Journal, sixth edition, page 102-107.
