== Chapter X.

Francis Howgill`'s imprisonment--He is engaged in writing in support of
the principles of Truth--An account of his last illness and death

Francis Howgill bore his imprisonment with great patience, and evinced so much meekness,
resignation, and love,
as greatly to gain the love and esteem of the jailer`'s whole family,
and of many others in the town of Appleby;
and such was the confidence the people placed in him, that while in prison,
they frequently referred their differences to him for settlement.

We find he continued diligently engaged in promoting the cause of Truth and righteousness,
while a prisoner,
by writing epistles to those to whom he was joined in religious fellowship,
replying to the works of some who falsely represented the principles of Friends,
and to those of others, who endeavoured to defend a hireling ministry,
and lifeless forms of worship,
incompatible with the spirituality of the Gospel dispensation;
and in refuting a work attempting to prove swearing lawful among Christians,
thereby endeavouring to make void the exhortation of Christ: "`Swear not at all.`"
He also wrote several doctrinal pieces; selections from which, and his epistles,
form the second part of this volume.

The peace of mind with which he was blessed,
in patiently submitting to the loss of his liberty,
for faithfully maintaining those testimonies,
which he firmly believed the Lord required him to espouse and defend,
not being afraid "`of them that kill the body,
and after that have no more that they can do,`" is
strikingly set forth in the following words,
subjoined to one of his epistles: "`From Appleby jail, the place of my rest,
where my days and hours are pleasant unto me.`"

When any one noticed the great length of time he had been a prisoner, he would say:
"`The will of the Lord be done.`"
He was taken ill the 11th of the 11th month, 1668; some time before which,
he disposed of his estate, and set his house in order,
being sensible of the decay of his "`outward man.`"
His love to his brethren and fellow-labourers was very great; and in testimony of it,
he left something to several of them, by way of remembrance;
he was also mindful of the Church,
and left a legacy to be distributed among all the poor of the household of faith,
in the parts where he lived.
And though the time of his departure drew nigh, and his sickness increased,
yet his faculties were preserved clear, and he was often very fervent in prayer,
and uttered many comfortable expressions,
to the great refreshment of those who were with him.
About two days before his departure, being attended by his dear wife and several friends,
he said to them: "`Friends, as to matter of words, you must not expect much more from me,
neither is there any great need of it,
as to speak of matters of faith to you who are satisfied;
only that you remember my dear love to all friends who inquire of me,
for I ever loved Friends well, or any in whom the Truth appeared:
and truly God will own His people, as He has ever hitherto done,
and as we have daily witnessed;
for no sooner had they made the act against us for banishment,
to the great suffering of many good Friends,
but the Lord stirred up enemies against them, even to three great nations,
whereby the violence of their hands was taken off.^
footnote:[From history it appears, that soon after the passing of the act of banishment,
the English nation was permitted to involve itself in war with Holland, France,
and Denmark.
And in a work entitled Posthuma Christiana, by William Crouch, he says,
in reference to this act, and the subsequent proceedings upon it:
"`It was not long before the Lord was pleased to manifest His displeasure,
and to put a stop to these unnatural, unrighteous, and inhuman actions,
by those severe strokes of His hand upon the nation, in the years 1665 and 1666.
First, the great plague, which swept away great numbers of the inhabitants,
and that followed by that dreadful fire,
which reduced to ashes so great a part of the city of Loudon;
and also the wars with the Dutch at that time.
And although they, like the Egyptians of old, did pursue the Lord`'s chosen Israel,
yet God took off their chariot wheels, and they drove heavily;
for the work prospered not in their hands.`"]

"`I say again, God will own His people, even all those that are faithful; and as for me,
I am well, and content to die: I am not at all afraid of death:
and truly one thing was of late in my heart,
and that I intended to have written to George Fox and others;
even that which I have observed, which thing is, that this generation passes fast away:
we see many good and precious friends, within these few years, have been taken from us;
and therefore Friends had need to watch, and be very faithful,
so that we may leave a good, and not a bad savour to the succeeding generation;
for you see that it is but a little time that any of us have to stay here.`"

Often in the course of his sickness, he said he was content to die; that he was ready,
and praised God for the sweet enjoyments and refreshments he had received on that,
his prison-house bed, whereon he lay,
freely forgiving all who had a hand in his restraint.
He said: "`This was the place of my first imprisonment for the Truth, here at this town,
and if it be the place of my laying down the body, I am content.`"
Several persons of note, inhabitants of Appleby, as the mayor and others,
went to visit him; some of whom praying that God might speak peace to his soul,
he sweetly replied: "`He has done it.`"

A few hours before his departure, some friends, who lived several miles from that place,
went to visit him; he inquired of all their welfare, and prayed fervently,
with many heavenly expressions, that the Lord, by his mighty power,
might preserve them out of all such things as would spot and defile.
And a little after, he was saying something concerning weeks, or a time,
after which persecution would be ended, but his weakness was so great,
and his voice so low, that it was not fully heard.
A while after, recovering a little strength, he said:
"`I have sought the way of the Lord from a child, and lived innocently as among men;
and if any enquire concerning my latter end,
let them know that I die in the faith which I lived in, and suffered for.`"

After these words, he spoke some other in prayer to God,
and sweetly finished his course in much peace, on the 20th of 11th month, 1668,
in the fiftieth year of his age; after being a Prisoner for the testimony of Jesus,
from the later part of the 5th month, 1663.
His solicitude as a Christian parent,
is remarkably exemplified in the following address to his daughter.

