== Chapter XI.

Francis Howgill`'s advice to his daughter.

The Unchangeable Testament, and Will, and Counsel of Francis Howgill,
Left to His Daughter Abigail Howgill.

Daughter Abigail,--This is for you to observe, and keep,
and take heed unto all the clays of your life,
for the regulating of your life and conduct in this world; that your life may be happy,
and your end blessed, and God glorified by you in your generation.
These things I bequeath unto you, and counsel you ever to observe,
being the chief things alone I have to bestow upon you;
which I prize more than outward riches.
You do so also, and observe and keep my sayings; and I charge you before God,
and by the coming of our Lord Jesus Christ, that you observe what I say;
the which I am moved of the Lord to leave behind for you,
and in tender love and affection unto you, my daughter,
that the Lord may give his blessing unto you, and make your ways prosperous,
and your latter end peace.

First of all, know this: I was never born to great possessions,
nor did inherit great matters in this world;
but the Lord has always endowed me with sufficiency and enough,
and has been as a tender Father unto me; because my heart trusted in Him,
and did love the way of righteousness from a child.
I have no great portion to bestow upon you, of the things of this world;
yet of that little which I have, and God has blessed me with, something I shall give you,
which I shall not mention here; but you will know at my decease;
but your dear mother I rather commend you unto, who, I trust,
will provide sufficiently for you; unto whom my heart has been upright before the Lord:
she had a sufficient portion and dowry when I married her,
the which I shall be sorry much to lessen or impair; and whatever was hers,
if it please the Lord I decease before her, I freely leave unto her,
as was ever my intention and purpose, which has not, neither shall alter,
through the strength of God, as God only knows, and bears me record;
and it shall be manifest unto all in due time, as it is unto the Lord,
who has been with me in the midst of many troubles, trials, and sufferings,
and has lifted up my head above my adversaries, because I trusted only in his Name;
which at all times I found as a refuge, and a present help in time of need;
and so it will be unto you, if you fear his Name, and trust in Him, forever.

And now, dear child, hearken unto the words of my mouth, and listen unto my counsel;
ponder these things I leave behind me, unto you to observe,
that your days may be long upon the earth, and blessed and comfortable unto you,
and an honour to God in your generation.
The time when you were born and came into the world,
was a time of deep exercise and trouble with me, not from the Lord,
who always spoke peace unto me, and did sustain me;
but by reason of the adversary of mankind, who always seeks to devour the good in all,
and is the sower of discord and mischief in the hearts of them who fear not the Lord,
neither abide in his counsel; in whom he enters,
as any place is given unto his temptations, and corrupts the mind:
but though it was a great trial that came upon me,
the Lord kept my heart in uprightness unto Him and gave me much patience;
so that though the earth had been removed into the sea,
and all outward things had run into confusion, and nature had changed its course,
the Lord gave me a resolution and strength not to be troubled, neither offended;
because He did support me.

At that time were you born; and therefore I called your name Abigail; which signifies,
the father`'s joy or delight; for in you I was comforted;
and my present trouble mitigated.

My counsel unto you is, that you remember your Creator in the days of your youth,
and fear the Lord in your youth; and learn to know Him, and serve Him all your days.
First, seek the kingdom of God, and the righteousness thereof; it is not far from you;
it is within you; it consists in life and power; and it stands in righteousness, truth,
equity, justice, mercy, long-suffering, patience, love, light, and holiness:
this is the being and centre thereof.
Therefore seek not lo here or lo there without you, in this or that outward observation;
for many seek there and never find it; but seek, and you shall find; wait,
and you shall receive.

If you inquire in what must I seek, and what must I wait in, and how must I seek;
I inform you, you must silence all your own thoughts;
and you must turn your mind to that which is pure, holy, and good, within yourself;
and seek and wait in that, in the Light of Jesus Christ, wherewith you are enlightened;
which shows you when you do evil, and checks and reproves.
Take heed unto that, and it will show the evil motions and thoughts; and as you love it,
it will subdue them, and preserve you for the time to come, out of evil:
for though you be born into the world a reasonable creature, yet you must be born again,
and be made a new creature;
or else you can not enter into God`'s kingdom.--You
must know the seed of the kingdom in yourself,
of which you must be born, and formed again into God`'s image.
I have told you that God has sown it in you, a grain of it, a measure of it,
a portion of it, a measure of Light and Truth, of righteousness and holiness.
Keep in your mind to that, and love it,
and you will feel the Heavenly Father working in you, and creating you to life,
through Jesus Christ, who has enlightened you;
and you will feel the power of the Lord strengthening you in your little,
and making you to grow in the immortal seed of his kingdom, and to out grow,
and over grow all evil; so that you will daily die to that, and have no pleasure in it;
but in the Lord, and in his goodness and virtue shed abroad in your heart;
which you will taste and feel within, and have joy and comfort therein.

Love the Lord with your heart and soul, even Him that made you,
and gave you and all things in heaven and earth a being;
still wait for the knowledge of Him in yourself: He is not far from you;
but near unto you, and unto all that call upon Him in an upright heart.
And if you inquire of your dear mother, she will inform you; she knows Him,
and the way to life and peace; and hearken unto her instruction.

God is a Spirit, a pure Spirit of light, life, and power.
He it is that searches the heart, and shows you when you do evil, or think evil,
or speak evil; and shows unto men and women their thoughts.
That which shows the evil is good, and that which shows a lie is Truth.
This is within; take heed to it.
This is called God`'s Spirit in the Scriptures; believe in it, love it,
and it will quicken your heart to good, and it will subject the evil.
Here is your teacher near you; love it.
If you act contrary to it, it will condemn you;
therefore take heed unto this Spirit of Truth, and it will enlighten and enliven you;
and it will open your understanding,`' and give you to know what God is,
and to do that which is good and acceptable in his sight.
This Spirit never errs, but leads out of all error into all truth.

O Abigail, believe my words! they are the words of God, and Truth.
Be not wanton, but sober-minded in your youth, and wait on the Lord within:
hearken unto Him.
God is Light immortal, Life immortal, Truth immortal; an everlasting, eternal Spirit.
He speaks spiritually and invisibly within the hearts and consciences of men and women;
hear what He speaks, and obey his voice, and your soul shall live: fear to offend Him,
or sin against Him; for the wages of sin is death.
Therefore prize his love in your young and tender years;
and read the Scriptures and Friends`' books, and take heed unto what you read to obey it,
as far as you understand; and pray often unto the Lord,
that He will give you his knowledge,
and open your understanding in the things of his kingdom.
Search your heart often with the Light of Christ in you; manifest,
and bring your deeds to it, that they may be tried;
and examine yourself how the case stands between the Lord and you;
and if you see yourself wrong, humble yourself and be sorry, and turn unto Him,
and He will show you mercy; and take heed for the time to come,
that you run not into the same evil again.
Keep your heart clean; watch against the evil in yourself, in that which shows it;
therein there is power, and thereby you have power to overcome all evil.

And dear child, mind not the pleasures of sin which are but for a moment,
and the end is misery; but keep under, and cross your will and affection;
so your mind will have no pleasure in the evil, but in good;
and you will feel the immortal Seed springing up in you,
which God`'s peace and love is to.

O Abigail! these are great and weighty things, not to be slighted!
Accompany yourself always with them that fear the Lord,
and fear and worship Him in spirit and truth,
and lead a holy and a blameless life and conduct; deny not them, but love them,
and suffer with them.
Take heed that you follow not the hireling teachers, who preach for gain and profit,
and abide not in Christ`'s doctrine; believe them not, heed them not,
they do people no good; but you will see them yourself:
they have an outside show of Godliness sometimes, but deny the power of God,
and true holiness.
Remember I have told you, who have had perfect knowledge of them;
but be sure that you let nothing separate your love from God and his people:
those are his people that keep his law, and obey Christ`'s voice, and lead a holy life;
and they were ever hated, and belied, and persecuted; and evil spoken of,
always by bad and evil loose people: these are God`'s people, and his love, and peace,
and blessing is with them.
Grow up as a natural branch among them, of the living Vine;
and continue all your days in obedience unto God`'s will;
and you will feel joy and love in your heart, which above all things covet after,
and you shall attain to and obtain everlasting peace; which the Lord grant unto you,
according to the riches of his mercy and love; which endure forever and ever, Amen.

And now Abigail, concerning your well-being in this life,
this is my advice and counsel unto you: love your dear mother,
and ever obey her and honour her, and see you grieve her not; be not stubborn nor wilful,
but submit unto her, and be as an obedient child unto her,
whose love and care has been too great over you and your sisters;
which has brought too much trouble upon herself.
Learn in your youth to read and write a little, and sew and knit,
and all points of good labour that belong to a maid;
and flee idleness and sloth that nourish sin.
And as you grow up in years, labour in the affairs of the country, and beware of pride,
and riotousness, and curiosity;
but be well content with such apparel as your mother will permit you,
and as you may be a good example unto others in.
Be not wanton, nor wild, nor light; but temperate, moderate, and chaste,
and not forward in words nor speech; but swift to hear, slow to speak;
and live always with your mother, and be a help unto her, and cherish her in her old age,
and latter years; that she may be comforted in you, and her soul may bless you:
love your sisters, and be always courteous to them, and your brother Thomas;
encourage one another in good.

And Abigail, if you live to be a woman of perfect years, keep yourself unspotted,
and let not your mind out after sports and pastimes, the end of all these is sorrow;
neither of young men: if you have a desire to marry, do not seek a husband,
but let a husband seek you; and if you live in God`'s fear, and an honest life,
and virtuous, they that fear God will seek unto you;
let not your affections out unto every one that offers love, but be considerate;
and above all things choose one, if you do marry, that loves and fears the Lord:
whose conduct you know, and manner and course of life well, before you give consent.
Be discreet and wise; hide nothing from your mother, and she will advise you, no doubt,
for your good; and if she be living, marry not without her consent.
And if you join to a husband, be sure you love him in your heart,
and be obedient unto him, and honour him among all; so will his heart be more to you,
and his love increase: grieve him not; but be gentle, and easily to be entreated,
and mind your own business.
And if the Lord give you children, bring them up in God`'s fear, and in good exercise,
and keep them in subjection unto you, and be an example of virtue and holiness unto them;
that the Lord`'s blessing you may feel in youth, and in age, and all your life long.

O Abigail! remember these things;
keep in mind these things! read often this writing over; get it copied over,
and lay up my words in your heart, and do them; so will you be happy in this life,
and in the life to come.
These things I give you in charge to observe, as my Mind, and Will, and Counsel,
unalterable unto you; in witness whereof I have set my hand.

Your dear father,

Francis Howgill.

26th of the 5th month, 1666.
