== Chapter XIII.

Abridged Selections from a Work Entitled:
"`The Glory of the True Church Discovered,`" etc.

=== To the Reader.

God, in his great wisdom, has in all ages manifested his will to his servants; and,
in every generation, He has shown unto them how He would be worshiped:
and they that have been obedient to that which has been made manifest, have,
in every age, found acceptance with the Lord;
and have had the peace of God in their hearts.
After man had transgressed against the will of God, and broken his covenant,
blindness came upon him; and he lusted after earthly things; and the image of God,
in which he was created was lost: yet such was the love of God towards man,
that He did not utterly cast him off forever; but followed him to draw him back again,
out of transgression into unity with Himself.
And when man was gone into darkness,
the Lord stooped so low as to come near him and to the state he was in:
and He made a covenant with him when his heart was outward, upon outward things;
and gave him outward commands, statutes, and ordinances, that he might worship therein;
which were shadows and types of some better things to come.

These were the ordinances of the first Covenant, which was to be changed;
but they typified more heavenly things, which were to be revealed in due time;
and when Christ, the Seed came, who restores all that believe unto God,
they had an end and passed away; for God did more clearly manifest Himself in the earth,
through his Son, who had the will of the Father, and declared it;
who put an end to the shadows, and blotted out the handwriting of ordinances,
consisting in types and figures, and offered Himself on the cross,
a propitiation for the sins of the whole world.
And those who believed in Christ and received Him, came to be the sons of God,
and declared the mind of God as it was revealed to them,
and the Spirit gave them utterance.
And they became of one heart and mind, and worshiped God with one accord,
in the Spirit and power of the Father; and separated from the Jewish worship,
and the form thereof, and met together in the power of God, and glorified Him,
and spoke of the things of his kingdom freely, to all that waited for it.
But soon after the mystery of godliness was revealed,
the mystery of iniquity began to work, and opposed the work of the Lord;
yet transformed itself into the similitude, outward appearance,
and form of righteousness, and lived in the flesh;
and there began to be an apostacy and deviation from that glory and power which once was;
and antichrist wrought with signs and lying wonders, and got the words of the righteous,
but hated the life and power of godliness, and them that appeared in it.
Then they that were under the government of antichrist hated the reign of Christ,
and said in their hearts:
"`we will not have Him to rule over us,`" though in words they confessed Him.
And they persecuted the true Church, and drove it into the wilderness;
and set up imitations, inventions, traditions, and vain customs,
which they called apostolical and holy institutions;
but which are contrary to the primitive institutions and ordinances of Christianity.

I have thus led you briefly through several ages and times,
to single out the origin and beginning of those things,
which are now accounted as holy institutions;
and to show who were the first ordainers of them,
between the days of the apostles and the present day.
You may see, in the following treatise,
the state and glory of the true Church before the apostacy,
and her state during the apostacy; how she fled into the wilderness;
and how mystery Babylon was raised, and the false church called herself visible.
Many of her doctrines and practices, which are contrary to the primitive Church,
are also here discovered,
whereby you may come to see a difference between the ordinances of the true Church,
and the traditions and inventions of the false church;
which are too much contended for in this day,
by those who say they are come to the true reformation, according to the primitive times;
but whose practices, as you compare them with those of the primitive times,
you will see to be quite contrary, and to be but as the smoke,
and that which darkened the air, and clouded people`'s understandings,
and led them into ignorance and darkness,
and prevented their discovering the way of Truth.
But the Lord is arisen;
and that which has got up in the apostacy is seen and laid open to the view of all,
that they may depart out of the things which are
but the inventions and traditions of men;
and in which Eternal Life is not to be had.
139

Read with meekness, and in that which is spiritual in yourself,
through which the things of God are made manifest; for with that I have unity: and,
as you live and walk in it, I bid you farewell.

Francis Howgill.

=== Section I.

The State of the True Church, from the Manifestation of Christ in the Flesh,
to the End of the Apostle`'s Days, Briefly Discovered

God, according to his determinate will and everlasting counsel, in the fulness of time,
sent his only begotten Son into the world, to be the Light of the world,
a Leader to the people, and a propitiation for the sins of the whole world.
He obeyed the will of the Father in all things,
according as it was testified of Him by Moses and the prophets,
and as it was said by David concerning Him:
"`In the volume of the book it is written of Me, I come to do your will,
O God I`" Ps. 40:7. He fulfilled all righteousness, and ended all the types, figures,
shadows, and worship of the first covenant, as the apostle testifies of Him, Heb. 7:21.
The law and the priesthood were changed,
which were but figures and shadows of good things to come, and were faulty,
and did not make the comers thereunto perfect as pertaining to the conscience;
but the bringing in of a better hope and covenant did, namely,
the covenant of life and peace; which the prophets, by the spirit, had testified of,
from Moses to Samuel, and till John;
and John likewise bore testimony of Him who is "`the
Lamb of God`" and "`takes away the sins of the world.`" John 1:29,36.

And now He being come who was not made "`after the law of a carnal commandment,`"
as were Aaron and the rest of the priests under the law,
but after "`the power of an endless life,`" and "`having offered up Himself
once for all,`" for the perfecting of them that are sanctified,
He put an end to all the offerings of the first covenant. Heb. 10:14.
He fulfilled all things which the prophets foretold of Him;
and his works testified that He was the Son of God.
He preached the word of the Kingdom,
and declared against and reproved them who stuck behind in the figures, types,
and shadows; and said:
"`You will not come unto Me that you may have life,`" "`I am the bread of life.`"
He came to fulfill the law and all righteousness, and to publish the word of faith,
which did not make void, but established the Law.

He said: "`While you have the Light, believe in the Light;
that you may become children of the Light.`"
This He spoke to the Pharisees, who had the law and the prophets,
and were acting in the types and figures, which are shadows of the thing itself,
but not the very thing; but He preached the very thing, the word of the kingdom,
of power, and of life; and many who heard his voice,
who could not be made alive by exercising themselves in the ordinances,
were quickened by it in their hearts and minds, and so came to live;
and He chose unto Himself disciples, and sent them to preach repentance;
and charged them to begin at Jerusalem.
Afterwards He also sent out his disciples and gave
them a commandment to preach unto all nations,
and disciple or make converts of all in the Name of the Father, Son, and Holy Spirit.
He gave power unto them to cast out devils, and work miracles.

These, after a season, prophesied the word of the kingdom,
and received gifts from the Holy Spirit for the work of the ministry.
They preached not up the ordinances of the first covenant,
but Christ the everlasting Covenant, the power of God, and the wisdom of God,
for the remission of sins;
and they declared the Word of faith in the mouth and in the heart,
to bring people to believe in Him who is the Light of the world,
and enlightens every man that comes into the world;
and many both of the Jews and gentiles believed; and they met together at certain places.
And the several congregations were all one body, whereof Christ, the life, was the head;
of whose power they had tasted.
And when they met together, they exhorted and admonished one another;
and did and might administer to the edification, building up,
and comforting one of another in the most holy faith, which gave them victory over sin;
which faith was wrought in them by hearing the Word that was nigh them,
in the mouth and in the heart, which was the Word of consolation that,
was in the beginning.

They that believed the Gospel,
grew up into great enjoyments and attainments in the righteous life of Christ;
and though they first knew the ministration of condemnation, and sentence of death,
yet afterwards they came to know the ministration of the Spirit,
bearing witness that they were the sons of God:
they were made heirs according to the promise, and joint-heirs with Christ,
in the kingdom which is immortal.

They that were sent out, who had received freely of the Father, of Christ,
and of the Spirit, ministered freely,
without making any covenants or enquiries after worldly revenues,
but went from city to city preaching the Gospel.
So that we read of no compulsion, or forcing maintenance from any of the cities,
whether they believed or not.
The Father took care of such harvestmen; and what they received was given freely,
and there was no complaint;
but their care was not to make the Gospel of Christ burdensome or chargeable,
but rather that their hands should minister unto their necessities. Acts 18:3.

=== Section II.

Of the Entering in of the Apostacy, and Declensions from Purity of Doctrine, Worship,
and Practice, from That Time to the Present Time.

Christ said: "`Beware of false prophets which come to you in sheep`'s clothing;
but inwardly they are ravening wolves:
you shall know them by their fruits;`" Matt. 7:15-16; and,
"`many false prophets shall arise and deceive many.`"
This was fulfilled in the age of the disciples.
John testified: "`Little children, it is the last time;
and as you have heard that antichrist should come, even now are there many antichrists,
whereby we know that it is the last time;
they went out from us but they were not of us.`" 1 John 2:18-19.
And Peter said: "`False teachers should arise,
who should bring in damnable heresies.`" 2 Pet. 2:1.
And Paul wrote to Timothy: "`That the Spirit spoke expressly, that,
in the latter times, some should depart from the faith,
giving heed to seducing spirits and doctrines of devils; speaking lies in hypocrisy;
forbidding to marry, and commanding to abstain from foods;`" 1 Tim. 4:1-2;
who were enemies to the cross of Christ.
These went out into the world; and this is upwards of 1400 years ago.
Then the mystery of iniquity began to work: they went out and preached Christ in words,
but denied the cross, and spoke things they ought not for filthy profit`'s sake.
Then was the beginning of the hirelings that cared not for the flock: they held the form,
but denied the power,
for they were out of the power and out of that which mortifies the deeds of the flesh;
and they spread themselves over nations, kindreds, tongues, and people,
which have now got the name of a church; and John said:
"`these were the waters upon which he saw mystery Babylon sit;
and she and all her children turned against the free woman, the Lamb`'s wife,
and made her flee into the wilderness for a time, times, and half a time;
and mystery Babylon reached forth her golden cup full of abominations,
and claimed Christ to be her husband, and sat as a queen,
and the kings of the earth drank of her cup, and were bewitched by her sorceries.
Then all nations becoming as waters, and unstable,
being drunk with the abominations of this cup, staggered up and down,
being out of the power of Christ which should have stablished them.
Then a great beast arose out of these waters, with seven heads and ten horns;
and these apostatised ministers, who preached for filthy profit,
and those that believed them, took shelter under the beast, and cried:
"`who is able to make war with the beast?`"
And the kings of the earth gave their strength to him; and the false church got upon him,
and rides upon him, and has done so these many years;
and she has travelled in the greatness of his strength;
calling herself by the free woman`'s name, and putting on her outward attire,
she says I am she; and thus has deceived the nations.
Then began laws to be made about religion;
then began compelling in matters of conscience,
which were contrary to the practice of the true Church.

Now Rome look to your beginning and view your antiquity.
If nations, kindreds, tongues,
and people have drunk of the cup of mystery Babylon since John`'s days,
then what cause have you to boast of antiquity and universality?
that sooner proves you to be the harlot than the true Church; for if nations, kindreds,
tongues, and people, universally, be the waters that she sits upon,
and the beast rose out of the waters;
read yourself and clear yourself of the apostacy if you can.
Seeing John saw the true Church, the woman clothed with the Sun,
who brought forth the man child, flee into the wilderness,
what cause have you to boast of visibility or universality?
When were you in the wilderness?
if your church has not been there,
then it demonstrates that your church is not the woman clothed with the sun;
for she did fly into the wilderness as with the wings of an eagle.

If the beast made war with all that bore not his image, then we have you as in a press,
between us and the apostles time; for no such compelling was in the true Church.
Instance any such thing if you can, from their writings;
where were men and women killed by the sword, or by lingering torments, in their time?
Such practices have been no where found in any other church but in you, and in those who,
at the best, are but in your suburbs.
And it is known that your church has been upheld,
more by force and cruelty than by sound doctrine; though you may say, "`I am clear,
I persecute none to death, I have a beast to ride upon, who will make war for my city,
and compel to my worship and institutions.
I will cry him up for the higher power and say, whosoever resists this,
resists the ordinance of God; and he will compel and destroy for me,
and call me the holy church; so I shall be clear?`"

Thus it is clear that the church of Rome is in the apostacy;
and this is also evident by her practices for

First.
Her ministers are not in accordance with the ministers of Christ, in the primitive times;
their call is not such, neither their practice.
The ministers of Christ were made ministers by the Holy Spirit;
but hers are made by human ordination and study, etc.

Secondly.
The ministers of Christ preached the Gospel freely;
but she has brought in tithes from Judaism for the maintenance of her priests;
and has also invented oblations, obventions, and mortuaries to maintain her ministers by.

Thirdly.
The ministers of Christ did not compel any by force to maintain them,
whether they received their doctrine or not; but she compels all wherever she has power,
making what she calls the Gospel chargeable.

Fourthly.
Her unbloody sacrifice of the mass is of no benefit at all;
for where no shedding of blood is, there is no remission.
Heb. 9:22; therefore her sacrifice is abominable, and an idol.^
footnote:[That the sacrifice of the mass is entirely useless,
must be obvious to all who receive the doctrine of the apostles:
"`By One Offering Christ has perfected forever all them that are sanctified.`" Heb. 10:14.
"`Christ is the propitiation for our sins, and not for ours only,
but for the sins of the whole world.`" 1 John 2:2.
"`There remains no more sacrifice for sins.`" Heb. 10:26.
From these doctrines the inefficacy of penances is also obvious;
and it is evident that a dependance upon them and masses for expiation from sin,
and for acceptance with God is idolatrous;
because those who trust in them look to other objects for
propitiation for their sins and acceptance with God,
than the One which God has set forth, which is Christ: Rom. 3:25.
by whom alone we have access to the Father. John 14:6.]

Fifthly.
Her liturgy and prayers in a tongue unknown to the
congregations is an unprofitable and vain worship,
and contrary to the words of the Apostle Paul who said: "`I thank my God,
I speak with tongues more than you all;
yet in the Church I had rather speak five words with my understanding,
that by my voice I might teach others also,
than ten thousand words in an unknown tongue, 1 Cor. 14:18-19.

Sixthly.
Her doctrine of a purgatory to cleanse from sin is an invented and imaginary thing,
and contrary to the primitive doctrine,
that "`the blood of Christ cleanses from all sin;`" 1 John 1:7.
And her distinction of mortal and venial sin,
tends only to blind people; for "`the wages of sin is death.`" Rom. 6:23.

Seventhly.
The worshiping and invocation of angels and saints, as mediators between us and God,
is contrary to the primitive doctrine: "`There is one mediator between God and man,
the man Christ Jesus,`" 1 Tim. 2:5;
and He alone makes intercession for all them that believe.
The angel reproved John when he would have worshiped him, saying: "`See you do it not;
for I am your fellow servant,`" etc. Rev. 22:8.

Eighthly.
Her relics and images are contrary to what the Lord commanded by the prophets:
"`You shall make you no idols nor graven image, neither rear you up a standing image;
neither shall you set up any image of stone in your land, to bow down to it.`" Lev. 26:1.
Duet. 5:8-9. Ezek. 6. And in Rom. 1:23,
they were condemned that changed the glory of the incorruptible God,
into an image made like to corruptible man, etc.
Thus the church of Rome may see, that image worship is forbidden in the law,
the prophets, and the new Testament.
And as for her relic worship,
there is neither command nor example for it by Christ or his apostles.^
footnote:[The exhortation of John: "`Little children,
keep yourselves from idols,`" 1 John 5:81. is quite
opposed to the practice of venerating relics,
by imagining them to possess any supernatural virtue, and of bowing down to them.]

Ninthly.
The practices of commanding to abstain from foods on certain days,
and of forbidding any to marry,
are enumerated among the "`doctrines of devils "`by the apostle Paul, 1 Tim. 4:1,3.

There are also many other things which might be enumerated,
which are found in the church of Rome, and which are proofs of her apostacy;
such as her doctrine of the real presence of Christ`'s body and blood,
in the bread and wine after the consecration by the priests;
her observation of particular days dedicated to particular saints,
the sale of pardons and indulgences, etc. etc.

=== Section III.

=== On Separation from the Church of Rome.

Now Christ being the Head of the true Church,
who ought to rule by his spiritual sceptre in the hearts and consciences of people,
unto whom all power in heaven and earth is committed by the Father,
who will not that any other should have that glory--the
separation of the Protestant churches,
which have denied the Pope to be the head, is upon good ground:
yet the Reformation is very imperfect;
for many of the doctrines and practices of these
are not according to primitive doctrine and practice:
such as setting up an outward ordination,
and a form of laying on of hands without the Holy Spirit;
and ordaining such as have some skill in languages and oratory for ministers,
confining these to parishes, preaching for hire, exacting tithes,
etc. and in using instrumental music in religious services,
which pertained to the Jewish worship; in counting some particular days holy;
in limiting to the use of certain portions of Scripture on certain days,
and using certain forms of prayer on certain days, and in many other things;
a brief history of the introduction of some of which,
among those who profess to be Christians, here follows.

=== On Fasts, Feasts, and Holy-day.

The Jews, in the first covenant, had many fasts, feasts, and holy days; as the sabbath,
passover, pentecost, feasts of the new moons, of unleavened bread, of tabernacles,
and of dedication, which are largely shown in the books of Moses; all which things,
as the apostle says to the Hebrews, were but shadows of things to come,
and not the things themselves; which only continued till the time of reformation,
and till the bringing in of a better hope, Which stood upon better promises.

In the primitive churches, they came to see the end of these things;
and were brought to Him who was the substance, in whom all figures and shadows end.
The apostle therefore says: "`Let no man therefore judge you in food, or in drink,
or in respect of a holy-day, which are a shadow of things to come;
but the body is of Christ,`" Col. 2:16-17. Now afterward,
when people minded the form more than the Power, they ran out into these things again,
with many additions; some borrowed from the heathen and some of their own invention,
and then pressed them upon Christians as apostolic ordinances.
And these things stand in force with many to this day,
even among those who are called reformed!
The keeping of days was invented to commemorate anything
remarkable which related to Christ,
the apostles, etc. and without any Divine authority; and for remarkable events,
as the nativity, circumcision of Christ, and purification of Mary, called Candlemas.
Easter and pentecost were kept by the Jews.
And it was decreed and ratified at a Council at Lyons in France,
that such days as either the holy saints departed this life upon,
or did any notable deed, should be kept holy for the increase of their religion.

Silvester assigned the day of Advincula Sancti Petri, commonly called Lammas,
in memory of Peter`'s pains and persecutions.
Felix the first, in order to magnify the commendation of martyrs,
made a statute that a yearly oblation should be had in memorial of them;
and Gregory would that mass should be said over their graves and tombs.
He also ordained, that neither flesh nor anything that had affinity with it, as cheese,
milk, butter, and eggs, should be eaten, on such days as were fasts.

Boniface the fourth instituted the feast of St. Stephen and Innocents, John the Baptist,
Lady day, Lawrence, Michael, Martin, etc.

That which is called Corpus Christi day, was made a holy-day,
and dedicated by Urbanus the fourth.

Soul-mass day was begun by Odilo, provost or provincial of Cluniacensis order,
because he heard that great cryings, lamentations, and weepings were heard about Aetna,
the burning mountain in Sicily, which he supposed to be the weepings of evil spirits,
that bewailed because the souls of dead men were taken from them,
by the petitions and sacrifices of well-disposed Christians; he therefore appointed,
in his convent, a general oblation for all souls, the day after the feast of All-saints;
this was about the year 1002.

Telesphorus appointed that Lent should be kept before Easter,
and added another week to it, which is called Quinquegesima;
and in this week he commanded the priests to fast more than the laity.

=== Of Those Called Parish Churches, and Church Yards

Parish churches,
which stand to this day both in the church of Rome and in those called reformed churches,
were ordained, built, and dedicated to saints in the apostacy.
The apostles and ministers of Christ, who published the Word of Reconciliation,
and Christ the substance of all figures,
gathered those who believed of the Jews from the temple and temple worship,
and of the gentiles from their temples and idols, to worship God in spirit;
and they met together in houses and sometimes by the sea side.
There are no parish churches dedicated to saints mentioned in the Scriptures.
The first church or temple that we read of, that was consecrated, was by Pius,
bishop of Rome, about the middle of the second century,
in honour of the virgin Pudentiana.
Afterwards,
Calistus is said to have made a temple to the Virgin Mary in a place beyond Tibris,
and instituted a burial-place and called it after his own name.
About the year 226, cemeteries were ordered to be hallowed,
by Urbanus the sixteenth bishop of Rome.
Dionysius, in the year 267, allotted to the several presbyters, in the city of Rome,
the churches and cemeteries;
and to others in other places distributed their respective parishes and dioceses,
that so every one might be confined within his own bounds and limits.

These were the beginnings of parish churches, church-yards, and consecrated grounds;
but we read of no consecrated ground in the time of the apostles:
they knew that the earth was the Lord`'s, and the fulness thereof, and that it was clean,
and good, and blessed, to them that believed.

Now Protestants, who have denied the church of Rome,
look about you and see how you are sticking in Babylon,
and yet buying the merchandise thereof.
As for your holy-ground, called church-yards,
which only you judge fit to bury the dead in, and would compel all to come there,
is it not because there are so many officers in and about it, who are greedy of rewards;
so that they would not miss anything that might be commodious to them;
and so would compel all to come there for their gain?

=== On Ecclesiastical Titles and Tithes.

Since the apostacy entered in, and the power of godliness began to be denied,
there have a number of names crept into the Church
which were not heard of before that time,
from men seeking offices, great titles, great benefits, and great revenues,
instead of serving the Lord freely and willingly and not for gifts and rewards.
Of these titles are such as, The Pope, His Holiness, Christ`'s Vicar, Universal Bishop,
Metropolitan Bishop, Lord Cardinals, Archbishops, Lord Bishops, Arch Deacons, Deans,
Prebends, Doctors of Divinity, Bachelors of Divinity, Vicars, Curates,
etc. as well as various orders of monks and nuns which, if compared with Scripture,
will scarcely meet any parallel either as to office, work, or doctrine.

There are literal ministers enough while the maintenance lasts;
but the ministration of the Spirit, few are acquainted with.

At the giving forth of the Law, after Israel came out of Egypt,
God chose Aaron and his sons for the office of the Priesthood;
and the rest of the tribe of Levi for the service of the Tabernacle,
and gave unto the Levites by commandment, for their service,
all the tenth in Israel for an inheritance.
And the Levites, out of their tithes, were to offer up to the Lord a tenth part,
and give it unto Aaron for himself and his sons;
so that the Levitical priests had no other portion but the tenth of the tenth;
as for the rest they were for the Levites that served at the tabernacle,
and for the strangers, fatherless, and widows.
The priests had also, above the tenth of the tithes, the first ripe fruits of the ground;
of corn, wine, and oil, and the first fleece.
But how comes it to pass that they who pretend to another priesthood than this,
even to be priests in the Christian Church, should receive the tenth of all,
even of unclean beasts, as pigs, and foals?
Surely they cannot distinguish the time nor the ministration,
or they would be ashamed to claim a title to the Tithes of Aaron and the Levites,
who had no portion in the land among their brethren, but these bishops,
priests etc. have a great part of some countries for their revenue.
Is this any other than the Pope`'s yoke?
Must this be received as Apostolical doctrine?
Let it never be mentioned among those who call themselves ministers of Christ,
or of any who profess themselves Christians.

The apostle ordained in the primitive churches that
a weekly offering should be made by the saints;
that every one might freely offer of that with which God had blessed him,
which was put into the hands of the Deacons,
and out of it the poor and necessary services were supplied.

In the next age monthly offerings were made, not exacted, but freely given.
Tertullian says: "`Whatsoever we have in the treasury of our churches,
is not raised by taxation, as though we put men to ransom their religion, but every man,
once a month or when he himself pleases, gives what he thinks good;
for no man is compelled, but left to his own discretion;
and it is not bestowed in vanity, but in relieving the poor,
and for the maintenance of poor children destitute of parents, and of aged people,
and such as are cast into prisons for professing the Christian faith.`"
This mode of contribution continued till about the year 304, according to Eusebius,
Tertullian, Origen, Cyprian and others.

Origen says: It is not lawful for any minister to possess lands given to the Church,
for his own use.

The Council at Antioch, anno 340, finding that much fault had been among the Deacons,
to whom it properly belonged to distribute the offerings of free gifts,
where there was need, and which they had detained for their own covetous ends,
ordained that the Bishops might distribute the goods;
but required that they should take no part thereof to themselves,
or to the use of the priests; using the exhortation of the apostle:
"`Having food and raiment be therewith content.`"

Chrysostom, who lived about the year 400,
pressed the people much to bountiful contributions for holy uses, and says:
"`I speak not these things as commanding, or forbidding they should give more,
yet as thinking it fit they should not give less than the tenth part.`"
Ambrose bishop of Milan, about the same period,
preached up tenths to be offered for holy uses, as the phrase then was:
but he produced his authority wholly from the writings of Moses.
Augustin bishop of Hippo, joined with Ambrose,
and threatened those who did not give their tenths,
with great penalties and heavy judgments from God; who, they said,
had reserved them for the use of the poor.

Hitherto, +++[+++for four hundred years,]
it was not laid down as a positive doctrine to pay them as the Jews did;
but the Jews were brought for an example, that Christians should not give less.
Leo, about the year 440,
was very earnest in stirring up men`'s devotion to offer to the Church;
but speaks not a word as to quantity.
Gregory not only advised the payment of Tithes from the Law of Moses;
but also the observing of Lent, which he reckoned as the tenth part of the year, saying:
"`We are commanded in the Law to give the tenth of all things to God.`"

About the year 600, pope Gregory the first, sent Augustin the monk into England,
by whom Ethelbert king of Kent was converted, as they call it; but it was only to Popery.
Augustin and his clergy for a long time followed the example of former ages,
living in common upon the offerings of their converts; but afterwards,
having brought a great part of the nation to their faith, they began to preach up,
that Tithes ought to be paid;
and having taught the people that the pardon of sin was merited by good works,
and the torments of hell avoided by charity,
it was no hard matter to persuade them to give not only their tenths,
but their lands and other riches; so that, in process of time,
the clergy got about a third part of the land into their hands.
Though by the law of Moses, they were to have no possessions in land,
except the very limited suburbs of the Levites. Num. 35:5.

Offa king of Mercia and Ethelwolf king of Northumberland,
who also were converted to Popery, made decrees that the two kingdoms should pay tithes.

Notwithstanding the threats of some great bishops, it was not till about the year 800,
that the doctrine that tithes ought to be paid, was generally received;
and then they were received into a common treasury and were disposed of thus:
one fourth to the priests, out of which every one had his portion;
one fourth to the relief of the poor, the sick, and strangers;
a fourth to the building and repairing of places of public worship;
and a fourth to the bishop,
who generally lived in some monastery and his clergy with him;
from which he sent them to preach in the countries,
where they received such offerings as were made, and brought them to the treasury.

None of the first eight general councils ever mention the name of tithes; but the ninth,
held at Lateran, under pope Calixtus the second, anno 1119,
speaks of such as had been given to the Church by special consecration; for at that time,
people believing that tithes ought to be given to the Poor,
gave them to the heads and rulers of religious houses, who disposed of them;
keeping open house for the poor and strangers,
and were esteemed holy and good treasurers for the poor, as is testified by Cassion.
But the council held under pope Alexander the third, anno 1180,
seeing much given to the poor and little to the priests,
made a decree to restrain people`'s freedom.

There was no law, canon, or constitution of any general council that commanded Tithes,
or expressly supposed them a duty, before that of Lateran, anno 1215,
under pope Innocent the third; at which time the Pope`'s power was grown great.
And then the people had greater mind to give them to the poor than to the priests;
which made Innocent cry out against those who gave
their Tithes and first fruits to the poor,
and not to the priests, as heinous offenders.

At a council held at Lyons, under pope Gregory the tenth, anno 1274, it was constituted,
that it should not thenceforth be lawful for men to give their tithes at their own pleasure,
as they had before done, but that they should pay all to the mother church.

The great decree which speaks most plainly of them was made at the council of Trent,
under pope Pius the fourth, anno 1560:
it commanded Tithes to be paid under penalties of excommunication.

By what has been stated,
it may be seen that Tithes were not even reckoned
as due for many hundred years after Christ;
and that indeed they were never due in the Second Covenant,
Christ having put an end to the first priesthood,
with all its shadows and carnal ordinances.

=== On Psalms, Matins, Litany, and Mass.

The Jews had many officers which belonged to the temple worship,
among which were singers, as the Ezrahites, and the sons of Korab, and Asaph, etc.
This was under the first covenant,
and belonged to that priesthood which could not continue because of the faultiness thereof.
But the Christians in the primitive times, who had received the Holy Spirit,
did joy in it; and they who sung, sung with the Spirit and with understanding,
from the feeling of God`'s presence and assurance, which they had in their hearts.
And they that overcame were redeemed from the earth, they that had followed the Lamb,
who had given them the victory over sin, death, and the grave, sung a new song,
which none could learn but those whose names were written in the Lamb`'s book of Life.
These were the songs of the redeemed,
whom God had delivered out of the hands of their enemies;
and those who sung them were witnesses of his wondrous works,
and praised Him in the Spirit and with understanding; they did not get a form of words.

They also prayed in the Spirit, and with understanding,
as they were moved by the Holy Spirit; and were not limited as to the length of time,
or to hours, or set times, but only to when the Spirit of God gave utterance;
and then their prayers were accepted, and were as sweet incense.

But since the entering in of the apostacy, the Spirit and power having been lost by many,
they have set up imitations.

Hierome appointed Matins at set times, as Polydore Virgil says; and Pelagius the second,
was the first who commanded priests to say them daily, saying:
"`As the just man falls seven times, so by instant prayers and matins,
he may as often rise and amend.`"

Pontianus, the seventeenth Bishop of Rome,
ordained that Psalms and Matins should be sung in the Church night and day,
to drive away evil spirits.

Damasus, bishop of Rome,
gave commandment that Matins should be said or sung in all churches;
and added "`Gloria Patri,`" to the end of every Psalm.
He also instituted that Psalms should be said or sung by course.

Urbanus the second ordained those called the Lady`'s Matins to be said daily,
and confirmed them in a council which he held at Mount Clare in France.

At length matins and prayers were so numerous in the church of Rome,
that they were glad to get beads to tell them by.

Concerning Mass and Litany,
there have been so many authors patching them up that they are almost past numbering.
Celestinus ordained some prayers to be said by the Priest when revesting himself to Mass,
beginning "`Judica me Domine.`"
Damasus instituted the confession at the beginning of the mass;
and Gorgius caused confession to be said nine times over in the Latin church.
Telesphorus ordained the Gospels and Epistles to be read;
and Damasus divided them as they are read at this
day in some of the churches professing to be reformed.
Anastatius ordained that people should stand at the reading of the Gospel;
Marcus ordained the first part of the Creed to be read,
after it was made by the council of Nice.
The second part, and Spiritum Sanctum was composed by the council at Constantinople.
Eutichianus instituted the offertory to be sung while
the people offered some thing to the poor.
Gelasius made some of the prefaces; Leo the third, ordained the burning of incense,
which pertained to Aaron in the first Covenant; Privity of Mass, called common,
was made by various persons; Gelatius made, "`Te igitur;`" and Alexander added,
"`Qui pridie;`" Leo,
made the addition of "`Hanc igitur;`" and Gregory added three petitions in the same.
"`Dies qui nostras, etc.`"
Innocentius instituted that priests in the upper part of the choir should kiss one another,
and that pax should be borne to the people.
Serjius ordained "`Agnus Dei`" to be sung by the clergy at the time of communion,
seven hundred years after Christ`'s ascension;
the priest often turning to the altar and wheeling about when he says:
"`Dominus vobiscum,`" or "`Oratis Fratres.`"

Foelix decreed that Mass should be said only in consecrated places;
and none were to meddle with the mysteries of consecration but the priest.
Anacletus ordained that no Mass should be said unless
in the presence of at least two persons,
lest the priest should say in vain to bare walls,
"`Oominus vobiscum,`" "`The Lord be with you,`" when no persons were present.
Thus one piece has been added to another,
by which people`'s minds have been drawn from attending on the Spirit of God,
to hearken to these foolish ceremonies and invented charms,
and so they have been led into ignorance and the shadow of death,
where many have taken up their habitations;
and Babylon`'s merchants have traded these many hundreds of years,
with such like merchandise, under the name of apostolic ordinances and holy institutions.

=== On Swearing.^
footnote:[Some of the observations under this head
are extracted from a work of Francis Howgill`'s,
entitled, Oaths No Gospel Ordinance.]^
footnote:[Some of the observations under this head
are extracted from a work of Francis Howgill`'s,
entitled, Oaths No Gospel Ordinance.]

In the first Covenant, the Jews were commanded to swear by the Lord,
and oaths were observed by them.
But the doctrine of Christ who came to end that Covenant,
and to establish the everlasting Covenant, was:
"`Swear not at all,`" neither by the head nor by any other thing;
and that yes should be yes, and no no in all things.
And James, an apostle of Christ Jesus, who knew the new Covenant which is everlasting,
and saw over the ordinances of the first Covenant, said: "`Above all things, my brethren,
swear not; neither by heaven, neither by the earth, neither by any other oath;
but let your yes be yes, and your no, no; lest you fall into condemnation.`" James 5:12.
And this was apostolic and catholic doctrine in the primitive Churches.
But afterwards people began to set up oaths again; imitating the Jews,
who were under the first Covenant, and bringing the commands to them as their ground.
Justinian the emperor of Rome, appointed first that men should swear by the gospel,
or book called the gospel, and lay their hands thereon and kiss it, saying:
"`So help me God.`"

Many persons rather than swear, and bring condemnation upon themselves,
have denied their estates and liberties, which laid at stake upon refusing to swear;
and happy will they be who have had no hand in provoking the upright,
and endeavouring to turn them aside out of Christ`'s way;
for woe will undoubtedly come upon such as have had a hand therein.

In order that it may be seen that refusing to swear is no new thing,
a few examples are here produced of the faithful, who suffered as martyrs in ages past;
and it would be easy to bring a cloud of witnesses from ecclesiastical histories,
of those who denied all swearing in various ages;
a few testimonies of such are here produced.
Basilides, who suffered martyrdom, being required to swear,
affirmed plainly that it was not lawful for him to swear, for he was a Christian:
so that it seems to have been the mark of a Christian not to swear.

Walter Brute, a martyr, a teacher among the people of God called Lollards,
bore this testimony: "`As concerning oaths,
I believe and obey the doctrine of Almighty God, and my Master Christ Jesus,
which teaches that Christian men, in affirmation of a truth,
should pass the righteousness of the Scribes and Pharisees of the Old Testament,
or else He excludes them from the kingdom of heaven.
And as concerning oaths He says: '`It has been said of old time,
You shall not forswear yourself, but shall perform those things unto the Lord you know;
but I say unto you, you shall not swear at all, neither by heaven, nor by earth,
etc. but let your communication be yes, yes, no, no;
for whatsoever is more than this comes of evil;
'`therefore as the perfection of ancient men of the
Old Testament was not to forswear themselves,
so the perfection of Christian men is not to swear at all,
because they are so commanded of Christ, whose commandment in no case must be broken.`"

The Waldenses or Leonists who were ancient and true protestants,
professed it to be in no way lawful for a Christian to swear;
whose cause Archbishop Usher, primate of Ireland, pleaded in this very thing,
stating that command of Christ:
"`Swear not at all,`" Matt. 5:34 to be a sufficient plea for them.

It is one of the articles of John Wickliff,
whose works were as much esteemed by the protestants of England,
as despised by the papists,
"`That Oaths which be made for any contract or civil
bargain between man and man be unlawful.`"

"`The Plowman`'s complaint,`" in the prayers, says:
"`Lord you give us a commandment of Truth, in bidding us say yes, yes, and no, no,
and swear for nothing; You give us a commandment of meekness, and another of poorness;
but, Lord, be that calls himself your vicar on earth, has broken both these commandments,
for he makes a law to compel men to swear.`"
Acts and Mon.
fol. vol.
1 p. 459. 9th. Edit.

Chrysostom, bishop of Constantinople,
blames greatly those who bring a book to swear upon;
charging clerks that they in no way constrain any body to swear,
whether they think a man swear true or false, saying: "`It is a sin to swear well.`"

=== On the Extent of the Power of Kings and Magistrates in Matters of Conscience

When the Lord brought Israel out of the land of Egypt,
by a strong hand and an outstretched arm, He made a Covenant with them,
and gave forth a Law, and statutes, and ordinances at Mount Sinai, by the hand of Moses,
the Judge of Israel.
The laws and statutes which were then given forth for Israel to walk in,
were concerning moral and civil things, and also concerning the worship of the true God.
See Exodus, Numbers, and Deuteronomy.
And those who did not worship the true God according to the command given in that Covenant,
were to have judgment executed upon them according to the Law;
and Moses and the rest of the judges over Israel,
were to see the laws and statutes executed upon the transgressors;
if any were idolaters and worshiped a false god, or blasphemers,
or sabbath breakers they were to be stoned to death;
and their blood was to be upon their own heads.
This was according to the Law of God.

And when Israel lusted after a king, God gave them one; and they had many kings,
who were anointed of God, by his appointment,
who were to rule in the same manner as Moses, Joshua,
and the rest of the judges had done: this was before Christ was manifested in the flesh;
this was the old way, these were the old paths that Israel were to walk in;
but this Covenant was faulty, as the apostle says,
and the ministers of it could not continue by reason of death: the Law, Priesthood,
Ordinances, and Worship were changed, when Christ, the end of the Law for righteousness,
was manifested.

Now as Aaron and the rest of the high-priests under the law,
were but types and figures of the Everlasting High-priest,
so the judges and kings of Israel were types and figures of Christ, the King of Kings,
the King of Saints, the Lawgiver and the Judge;
and their outward power in compelling to the true worship,
or restraining from idolatry under that covenant
did but continue until the time of reformation,
and was but a type of Christ`'s spiritual power, weapons,
and execution of judgment upon his enemies.
who are not subject to his government and power.

The first Covenant and its ordinances, and the power of compelling to the worship,
and punishing idolatry, belonged to the Jews only, who were under that Covenant,
and not to the gentiles; as it is written: "`He shows his word unto Jacob,
his statutes and his judgments unto Israel.
He has not dealt so with any nation.`"
Ps. 147:19-20. Wherefore they who would bring people now under this Covenant,
and the power of it, deny virtually the second and everlasting Covenant.

The ministers of antichrist have pressed it upon kings and rulers,
that God has required of them to enforce all people to a worship,
although they themselves are divided among themselves;
one while for this tiling and at another time for that.
And because the kings of Israel did so, and had power to do so,
they have concluded that princes and judges ought to do so;
and by this means have made them put their necks into a yoke,
which is too heavy for them to bear; which the Lord has not required at their hands.
By these compellings and forcings, many hypocrites have been made;
and many of the consciences of God`'s people wounded and burdened:
and because of them many kings and rulers have lost
their dominions under the judgments of the Lord.
All who have intruded upon Christ`'s prerogative and sovereignty,
are but usurpers of that power which the Father has given unto his Son,
and which He will not give to any other,
to be Judge and Lawgiver in the hearts and consciences of his people.

It may be objected,
that the apostles exhort to submission to every Ordinance of man for the Lord`'s sake;
1 Pet. 2:14-15: "`Whether it be to the king as supreme; or unto governors,
as unto them that are sent by him;`" and Rom. 13:1-2:
"`Let every soul be subject unto the higher powers.
For there is no power but of God: the powers that be are ordained of God.
Whosoever therefore resists the power, resists the ordinance of God.`"
Now from these Scriptures many bad inferences have been drawn;
such as that kings and rulers were to be obeyed in all things;
and that they had power in spiritual things,
to make laws for such a mode of worship as they preferred, and to forbid others;
and that all these ought to be obeyed: and, in the apostacy,
the ministers of antichrist have brought in many inventions, traditions,
and human institutions, for Divine worship; and have pressed rulers to make laws,
and compel all people to receive them,
although they have been repugnant to the true worship of God.
And such teachers have pressed people to obedience as a duty,
on the ground of the aforesaid Scriptures.

Now these Scriptures must be understood to speak
of submission in things which are just and equal,
which are only of a civil or moral nature,
and of ordinances for the good and wholesome government of a state;
and cannot be understood of things spiritual, or relating to the worship of God;
otherwise Peter and John were themselves transgressors, as well as the other apostles,
who when they taught boldly in the Name of Jesus,
and were commanded by the rulers to speak no more in that Name, disobeyed the command,
saying: "`Whether it be right in the sight of God,
to hearken unto you more than unto God, you judge.`"

=== On Image worship, the Decrees of Coucils, and the Infallibility of the Church of Rome

Leo, emperor of Rome, commanded that all images and pictures of saints,
should be taken out of the churches, for the avoiding of idolatry, in the year 726;
but Gregory the second withstood him; and Leo, for confirmation,
called a council of Bishops, about 300 in number; and they, in the year 730,
decreed that all images should be taken away and broken.
But Gregory the second called another council at Rome, of near a thousand Bishops,
and condemned Leo and the three hundred Bishops, for taking the images out of churches;
and decreed that they should be worshiped with all reverence.
Yet the former council and this were all of one faith,
and of that church which they say cannot err.

The Eliberine council decreed that no images should be set up in the churches,
nor worshiped; and that the walls should not be painted.
The council of Constantinople decreed,
that images were not to be suffered in the churches, or meeting-places.
But the second Nicene council determined,
that images were not only to be placed in the churches but also to be worshiped.^
footnote:[In the beginning of the 7th century,
Gregory the first blamed Serenus of Marseilles, a bishop,
for causing all the images to be pulled down, and cast out of the places of worship,
and destroyed; because the Franks, who had settled in the south of Gaul,
who had been indulged in the use of them at the time of their conversion,
had been insensibly brought back, by them, to idolatry.
Gregory says on this occasion:
"`Though images were not set up in churches to be worshiped,
yet they serve to instruct the ignorant.`"
But the council of Trent says: "`Images were set up in churches,
to have due honour and worship paid them there.`"
If therefore the doctrine of Trent was sound, Gregory`'s doctrine was heretical.
The doctrines of both are, however, contrary to the doctrine of the Holy Scriptures;
and it would be well for all who are in the practice of bowing down to images and pictures,
or of worshiping them, to consider how they will stand, in the day of judgment,
before God, who has commanded: "`You shall not make unto you any graven image,
or any likeness of anything that is in heaven above, or that is in the earth beneath,
or that is in the water under the earth: you shall not bow down yourself to them,
nor serve them; for I the LORD your God am a jealous God:`" Exodus 20:4-5.]

The latter council, under Julius the second, repealed the decrees of the Pisan council.
The Basil council determined, that a council of Bishops was above the Pope,
and that they who judged otherwise were heretics; but the Lateran council, under Leo,
decreed, that the Pope was above the council;
and that he who should think otherwise should be held for a heretic.

The council of Trent commanded that Bishops should teach the people,
and should have no more benefit for preferment, than one place;
but they have since made this decree void,
and now whole countries are too little for them; and Protestants imitate the same.

What has been the validity of these councils of men,
acting out of the life and power of God, which bring the Seed of God into bondage?
Now, Rome, look to your infallibility, universality, and unity, which you so much cry up,
one while setting up one thing, and another throwing it down again,
when it will not serve particular interests.

Thus people have been led up and down for many generations;
and there has been persecution about changeable and alterable things; and the Life,
which redeems out of the world unto God, has not been sought after.
Let all who desire to have peace, and to enjoy the testimony of God`'s blessed Spirit,
come out of this Babylon, this city of confusion, whose seat is erected upon the sand,
whose foundation is laid in the waters,
and whose faith is placed upon human institutions;
which are variable and subject to mutation.
Let them come to know "`the Rock of Ages,`" and the unalterable council of the Lord,
and the wisdom of the Most High, to rule in their hearts.
Let them wait in the immortal Light of God, which is within,
that they may see over all these mountains of darkness,
which are risen up in the apostacy; and over all the institutions, decrees, statutes,
ordinances, and inventions of men;
and come to Him who is "`the Beginning of the creation
of God,`" who is that Quickening Spirit,
by which all who believe are raised out of death, and made partakers of the Life,
which is immortal, which fades not away;
and then they will be enabled to worship the Lord in spirit and in truth.

Away with all types, figures, shadows, and veils,
with human institutions and ordinances of men,
ceremonies and vain superstitious traditions, which God has no pleasure in,
which do not profit at all; for the Life is risen; "`the veil of the covering,
which has been spread over all nations,`" is rent; the night is gone; the day is come,
and has appeared in brightness; the shadows are passed away,
and the morning of Righteousness has appeared; the Son of God,
who has given to his flock an understanding, is come, in whom life, blessedness,
and everlasting consolation reside; which He causes to rest upon his people forevermore.

=== Section IV.

=== How All May Come out of the Apostacy and Become Members of the True Church, the Lamb`'s Wife, Which is in God.

So far as God appeared, or manifested Himself to the sons of men in any age, by shadows,
figures, or other outward appearances, the evil spirit, serpent`'s seed, and evil doer,
always took up the form of the thing, when it came into reputation.

The Jews held up the types, figures, and ordinances of the first Covenant,
and opposed Christ, the Light and Everlasting Covenant, and also those who published Him.
And when the Name of Christ came to be spread abroad,
false apostles and deceitful workers, who were enemies to the Cross,
and to the Power of God, preached Christ out of contention and envy,
and for filthy profit;
and by wicked practices made the Name of Christian odious among the heathen; and,
by their ungodly deeds, caused the worthy Name by which the saints are saved,
to be blasphemed.

When the apostle gathered together many that believed,
and settled them in the order of the Gospel,
and that order and the conduct of the saints came to be of good account,
false apostles and deceitful workers got up;
and as the apostles and saints met together in houses,
the false apostles crept into houses, and held the form but denied the power;
and such were to be turned away from,
according to the exhortation of the apostle to Timothy.

Since the true Church fled into the wilderness, the false church came into visibility,
to sit as a Queen upon the waters, the nations and peoples;
other things have been brought in,
which were not institutions of Christ or of the primitive Churches;
and these the world has wandered after, in the dark night of apostacy,
in which the worship has been made up partly from that of the Jews,
partly from that of the heathen,
and partly of the inventions of those who were in the apostacy; they being corrupted,
and the Scriptures having been perverted every way, to confirm all this deceit.

Many have judged, that to relinquish the former superstitious practices,
and to take up the form and practise again in the outward,
as it was in the days of the apostles, is to come out of the apostacy.
But let all know this, that the worship and service which God now requires,
and that alone in which He will manifest Himself, is in the Spirit;
which all people are to wait for, that they may come to the end of the night of error,
and witness restoration to the Bride the Lamb`'s Wife.

Now a measure of God`'s Spirit is given to every one to profit withal, which,
as it is attended to, shows what is sin, transgression, formal worship,
and the transformations of deceit, and leads them that believe in it,
out of that which is polluted, to Christ, the Sure Foundation, and mighty Power of God;
and causes them to know the Peace of God, and good will to all men.
That which will restore all those who believe in it, must all wait for,
and witness it to be made manifest in their hearts, and receive it.
This will bring them out of the apostacy;
but without this they can neither come out of it,
nor see the end of those things which are to be abolished;
for it is the mighty Power of God alone,
which must be witnessed and received by every man
who comes to be a living stone of the holy city,
a living son of the free woman, and a true member of the Heavenly Jerusalem,
which is from above.

These sayings are faithful and true; and blessed is he that hears, believes,
and receives them.
