== Forward by the Editor

Francis Howgill (1618-1668) was a prominent early member of
the Religious Society of Friends (Quakers) in England.
The collected works of Howgill were first published in 1676, eight years after his death,
in a large volume entitled, "`The Dawnings of the Gospel Day,
and its Light and Glory Discovered.`"
A significant abridgment of this lengthy volume was published in 1832 by James Backhouse,
which contained, among other writings, an abridged version of the essay entitled,
"`Some of the Mysteries of God`'s Kingdom Declared, etc.`"
The document you have in hand is not the Backhouse version of this essay,
but a less abridged version that I transcribed from a
photocopy of the original 1676 publication.
Because the style, punctuation,
and spelling used in early modern English differs considerably from the English of today,
some editing was unavoidable in preparing a readable manuscript.
Nevertheless,
I believe this publication represents a more accurate and complete
rendering of Howgill`'s essay than any other currently available.

[.signed-section-signature]
Jason R. Henderson

[.signed-section-context-close]
July, 2015
