== To the Reader

[.salutation]
Reader,

In times past, in the night of ignorance, since the days of the apostles,
many have groped in the dark as blind men,
and out of thick darkness they have spoken darkly of the things of God,
and of His kingdom.
These have written about the things of God, and His kingdom,
and have fed the dark minds of many who are unconverted to God.
Many are therefore confused in their minds, and err in judgment,
and have lost the key of knowledge which will open their hearts,
and give an entrance into the mysteries of God's kingdom.
Therefore, in compassion to those who are thirsting after the Lord,
and for the sake of those who have no place to rest,
these things I have written as they were revealed to me, and in me, by His pure Spirit.
If you will wait in that light through which God
reveals His mind and manifests His knowledge in man,
and come out of the nature of the world, you will see these things to be truth,
though they be hidden and veiled from the world that lies in wickedness.

I have not written to please men of corrupt minds, who glory in words,
outward appearances, natural capacities and sounds, and who are erred from the Life;
but rather to the simple-hearted, and for the strengthening of the weak,
and for the understanding of the simple.
And if there be something in the following discourse which you cannot accept,
let it alone, and judge nothing before the time--in your wisdom that is earthly,
or in your own reason.
Rather, wait to judge by that which is of God in you
(in and by which I desire to be approved, and by nothing else),
and it shall be made manifest in the Day of the Lord that is dawning in the
world (which many have seen appearing in power and glory). Wait then,
in your own particular, that you may feel your own condition, and see your own state.
And then that light which lets you see your own condition will also let you see the Lord,
and you will know what I have declared of Him to be true.

[.signed-section-closing]
I am your friend in Truth, and wish good to all men,

[.signed-section-signature]
Francis Howgill

[.signed-section-context-close]
1658
