== Section I.

[.chapter-subtitle--blurb]
Some of the mysteries of God`'s Kingdom declared.

The Lord God of the whole earth, who lives forever, even the God of Abraham,
Isaac, and Jacob, whose throne is established in righteousness,
and who rides on the heavens and shines forth in His
eternal excellence from the firmament of His power,
is manifesting Himself as in the days of old.
He is now revealing His righteousness as in the years past,
and is pouring out His Spirit on His sons and daughters, according to His promise,
and His blessing "`of the precious things of the everlasting hills.`"^
footnote:[Deuteronomy 33:15]
The Lord, who appeared at Sinai in the burning bush unto Moses His servant,
who rose up from Mount Seir, and shined forth in His brightness from Mount Paran,
and comes in ten thousands of His saints; even He from whose right hand went a fiery law,
so that the people could not behold His glory,
this One has now appeared in this the Day of His power, and is yet appearing.
His glory shall dazzle the eyes of the world,
and His brightness shall make dim all the world`'s glory, and stain the world`'s wisdom,
shutting it up in utter darkness, so that it will seem to have no existence or being.
The shadow of death will flee away,
and all the haughty and lofty princes of this world shall be horribly afraid.
The beasts shall go into their dens when the Day appears,
and the lambs of the everlasting fold shall come forth, and be fed in the fat valleys,
where the springs of life compass about all the banks,
and the lambs shall rejoice in their Shepherd, and say: "`The Lord is my Shepherd.`"
 For who has seen His wonders and noble acts from the days of old,
of which the fathers (who are fallen asleep and are at rest in the Lord) have told
us? But now God is bringing many to see what they witnessed to be true,
and to have the same thing fulfilled in themselves.
Honor and praise to Him who is the stay and strength of all His people forever.

The Day of the Lord has dawned,
and the light has appeared that manifests all things which are reprovable.
The Day Star is arisen in the hearts of many,
and they have come to see that fulfilled in their
hearts which Peter exhorted them to wait for.^
footnote:[2 Pet. 1:19  "`And so we have the prophetic word confirmed,
which you do well to heed as a light that shines in a dark place,
until the day dawns and the morning star rises in your hearts.`"]
These have taken heed unto the more sure word of Prophecy,
until the Day appeared and did dawn in their hearts.
And this Day (when it appears, and to whom it appears) discovers all things,
and makes all things manifest,
as is declared by the Spirit of Truth in the Scriptures
of Truth--"`and every man`'s work shall be tried,
of what sort it is, of what nature it is.`"^
footnote:[1 Corinthians 3:13]
Praises be unto the Lord, for this Day has appeared to many who have waited for it,
and now they see everything according to its source and increase,
and every tree and fruit is seen according to its kind, whether good or bad.
For every man`'s work is obvious to those who are in the Day,
and upon whom the morning of righteousness has
appeared and the sun of righteousness has shined.
Thus it can be seen by all (in the Light which is truly called Day,
and by the Lord who causes it to spring from on high) what is reprovable and condemnable,
and also what is justifiable and unreprovable.
All is seen by the Day of the Lord appearing in the heart.
