== Section II.

[.chapter-subtitle--blurb]
What the Day of the Lord is, how it is seen, and to whom it has appeared.

God is a spirit, His Day is spiritual, and is seen with a spiritual eye.
It is pure light, pure brightness,
the pure shining forth of the Lord in His glorious excellence.
It is the shining forth of eternity.
It is life manifesting itself in brightness.
It is holiness shedding itself abroad in its glory and purity,
spreading itself in its immeasurable excellency,
and it can only be seen as it is by the children of light that are born of it.

There is a natural day and there is a spiritual Day.
The natural day receives its brightness from the sun;
the spiritual Day receives its brightness from the Sun
of Righteousness (who is the Fountain of Life),
by whom it is brought forth, and without whom nothing is made or brought forth.
The natural day receives its clearness from the natural sun,
and is discerned by the natural eye of the natural man,
and all things natural are seen and discovered by and in the natural day,
and are clear and obvious to him that has natural sight.
Even so, the Day of God receives its brightness from the Sun of Righteousness,
the Lord of glory, light, and purity.
It issues out from Him by the rays of His brightness and is discerned and seen only
by the spiritual eye of the spiritual man who is of the image of the Father,
brought forth in His life and in His own nature and quality.
This is the birth which is from above (from God the Father of life,
by Jesus the life of men and the light of the world).
Only he who is of the nature of the Father and the Son,
and of their Day, comes to behold this Day,
and to discern all things of the Father`'s kingdom by it.
Such can discern all the hidden things of dishonesty,
and the works of darkness which are brought forth by the prince of
darkness--who is shut up in eternal and utter darkness,
which is his residence and dwelling place forever,
and will be the eternal residence of all workers of iniquity that bear his image.

[.discourse-part]
Objection: But some may be ready to say, "`But all things are not yet made manifest,
nor has that Day come, nor has it appeared to any in this age!`"

[.discourse-part]
Answer: What if a man that is naturally blind says there
is no light in the natural day or in the sun,
simply because he sees none.
Is there therefore no light in the day or in the
sun? And what if all things seem alike unto him,
both day and night,
because he can distinguish nothing? Does this therefore make void the seeing,
or hinder the discerning,
of those who indeed see with the natural eye both the sun and the day? Likewise,
what if they who are spiritually blind, and are children of the night,
say they can see nothing of the Day of the Lord, nor discover the things of God,
or His glorious appearance,
which many others do witness? Does this therefore make void the spiritual sight of
those who have seen into the things of God`'s kingdom? May God forbid that the
unbelief of some make void the faith of those that do believe.
