== Section III.

[.chapter-subtitle--blurb]
What the Day of the Lord is, and what it will be to the wicked.

The Day of the Lord is pure light and brightness in itself,
and does not mix with the night, which is of a contrary nature.
The Lord separated these two in the beginning, setting their bounds and habitations,
and establishing it as a decree that will last unto all eternity.
But though the Day of the Lord is pure, and keeps its purity, property, and nature,
(being consistent in itself, for nothing can alter its purity), even so,
it is a Day of blackness and gloominess,
and a terrible Day unto the wicked who hate its appearance and its light.
For unto the children of falsehood and deceit, whose deeds are evil,
the Day makes manifest both them and their deeds,
and it is unto them just as it is written,
"`For the morning is to them even as the shadow of death.`"^
footnote:[Job 24:17]
The appearance of the Lord frightens them, and they seek to run from it.
For they are like a thief who digs through a wall and breaks
into a house in the night when deep sleep is upon men.
But when the day appears, it discovers his actions,
and he is afraid because he can then be seen.

Now, unto all that live shamelessly upon the earth,
whose hearts are set to seek after wickedness as for hidden treasure,
the Day of the Lord will come upon such as a thief.
And because they are children of the night,
and bring forth the fruits of darkness (which are contrary to the light),
they will have their portion in utter darkness,
and eternal vengeance will surround them as a wall,
and with fury the fire will devour them like fuel.
So shall the ungodly perish, and have their portion with hypocrites.

Consider then and repent,
all you who revile and rail against the light and the appearance of God!
For the wild donkey who is accustomed to the wilderness follows her desires,
and those who seek her will not weary themselves in searching;
yet her time surely comes when she will be easily found and taken.^
footnote:[Jeremiah 2:24]
Even so, all the ungodly, though they may run like the wild donkey,
and pursue their way as the swift camel, yet the time comes, the Day comes,
when they will be overtaken in the midst of security, and they will not escape.
And though the children of this world, teachers of this world,
and professors of Christianity (who profess the Scriptures),
have prayed for the Day of the Lord, nevertheless, when it comes,
it will be as a hot burning fire, a devouring fire, and they will fall as stubble,
and as a burning mountain before it.
They will not be able to abide, for whatever is reprovable is manifest by the Day,
by the light which is eternal, in which God appears.
And this Day shall appear even to the wicked and ungodly,
and they shall be made manifest (for that which is made manifest is no longer hidden,
but is seen and brought to light and beheld).

Therefore, all you hirelings who preach for hire,
and you people that love to have it so, you will not be hidden.
All who oppose the truth, you will be found out,
and will be convinced of your ungodly deeds and hard words,
and that which makes you manifest will be the Day, and indeed it will convince you.
For even the wicked shall see its appearance, though unto condemnation, shame,
and contempt.
"`They shall see Him whom they have pierced.`"^
footnote:[Zechariah 12:10; John 19:37]
For even in the wicked God has a witness which is pure, which checks them often,
though they do not regard it, because the god of the world has blinded their eyes.
Yet when Christ the life appears,
He will make that eye to see which the wicked have put out,
and which the god of the world has blinded.
By His power, the Lord will open even the eyes of the wicked,
and they shall see Him and His coming in dread,
and His pure appearance will make them horribly afraid,
and His Day and appearance will be to their sorrow.
Though they would not see, they will be made to see,
and to hear that which they refused to hear,
when God sounds His trumpet and gives notice to all,
that the dead (both small and great) must arise, "`some unto everlasting life,
and some unto shame and everlasting contempt.`"^
footnote:[Daniel 12:2]

Therefore, put this warning not far from you, all deceitful workers,
adulterers and idolaters, who worship your own imaginations,
and all careless people who live in carelessness and pleasure, who are man-pleasers,
vain talkers,
foolish jesters and despisers of those who have
come out of the pollution that you wallow in.
Indeed, the Lord`'s appearance will be to their great joy,
but to you it will be shame and eternal misery, except you speedily repent.
