== Section IV.

[.chapter-subtitle--blurb]
What the Day of the Lord is to the righteous, and how He appears to them,
and whether any are to look for it while still in the body.

The appearance of God (who is eternal life) in His Day,
in His immeasurable light, is a great joy and a source of rejoicing to the righteous.
For He is, to His people who behold Him, an everlasting light,
and in His light they come to see light.
And in His Day He reveals the secret mysteries of His kingdom within them, that is,
in those who see the Day appear in their hearts.

This Day makes all things manifest,
even the secrets of the Lord and His hidden treasures, which never rot nor rust,
but are always fresh, and keep their pure image and impression, and are always the same.
By this light, all the righteous who have waited for God's appearance, come to see Him,
even as it is written, "`This is He we have waited for,
let us rejoice and be exceedingly glad.`"^
footnote:[Isaiah 25:9]
What? Has the One you have waited for indeed come? Yes, He has come,
"`and His reward is with Him.`"^
footnote:[Isaiah 40:10; Isaiah 62:11]
They that see Him find contentment in Him, and in His reward.
And what is the reward? It is joy, gladness, peace of conscience,
assurance of God's love sealed in the heart by the pure Spirit of the Lord.
It is the streams of life flowing forth continually from the great deep which
refresh and keep cool in the greatest extremity of heat and temptation.
This is enjoyed by those who have waited, and who do wait for it,
even now in the body--these can bear witness of Him and His coming.

For what was the witness of the disciples? Was it not, "`The Son of God is come,
and has given us an understanding.`"^
footnote:[1 John 5:20]
An understanding of what? Of God, of His Day, of His appearance, of His power,
of His wisdom, of His kingdom, of hope, faith, assurance, peace, joy, comfort,
and consolation.
What, in this life? Yes, in this life!
A cloud of witnesses I might bring from former ages,
and a cloud of witnesses I might also bring from this age, blessed be the Lord!
But my witness (He who gives me assurance) is nearer to
me and is surer to me than all these witnesses,
although they all be true.

Abraham, the father of the faithful and the righteous,
who believed God and was accepted, he "`saw Christ's Day and was glad.`"^
footnote:[John 8:56]
Professors^
footnote:[By professors he means those who profess faith in Christ.
Here the word has nothing to do with teachers or scholars.]
object--"`But that was by faith!`"
Yes indeed, by what else? By faith Abraham saw, and by faith all others have seen,
whosoever has indeed seen Christ, or His Day, or the Father.
"`By faith they saw Him who is invisible.`"^
footnote:[Hebrews 11:27]
"`Behold!
God is my salvation.`"^
footnote:[Isaiah 12:2]
What, do you enjoy salvation already? Yes, "`He has become my salvation.`"^
footnote:[Exodus 15:2; Psalms 118:4; Isaiah 12:2]
And Simeon, who waited for the consolation of Israel, said,
"`Now let Your servant depart in peace, for my eyes have seen Your salvation.`"^
footnote:[Luke 2:30]
And the apostle, knowing God's comfort and consolation, said this:
"`For as the sufferings of Christ abound in us,
so our consolation also abounds through Christ.`"^
footnote:[2 Corinthians 1:5]
Indeed, these were made partakers of His divine nature,
and sat together in heavenly places in Christ Jesus.
For Heaven is His throne, and they that are in Him and enjoy Him,
(who is the power and wisdom of God) know peace, and rest,
and salvation both from guilt and sin.
And the apostle, in writing to the Hebrews, said,
"`After He had purged away our sins`" (speaking of the atonement),
"`the everlasting High Priest sat down on the right hand of the majesty on high.`"^
footnote:[Hebrews 1:3]
Paul saw beyond sin, even unto Him who had purged away sin,
and this purging from sin is made manifest unto
and in those who believe by the Spirit of Jesus,
who is Christ the Lord, the Arm that brings salvation,
and the Author of eternal salvation unto all who believe.
He begins salvation in His Day, and He perfects it in His Day; for He works in the Day,
as He Himself has said, "`My Father works, and I too work,
but the night comes when none can work.`"^
footnote:[John 5:17; John 9:4]
And this is His work in man--"`to destroy the work of the devil.`"^
footnote:[1 John 3:8]
And those who have come to His Day feel and see the handiwork of God in themselves,
and His own works praise Him, for they alone can.
But those who have not come to the Day, do not know God's work in themselves.
And those who have not yet given heed to that light in
themselves (which manifests all things reprovable),
have not come to know the appearance of the glimmering of light, or of the Day,
which the saints do witness in themselves, even all those that are sanctified.
