== Section V.

[.chapter-subtitle--blurb]
Where the Day of the Lord appears, and how it comes,
and how it is to be looked for.

Those who look outward, whose eyes are abroad,
cannot see the Lord`'s appearance or His Day.
He that does not know in what this Day consists, cannot know how to look for it,
even as the Jews, who were professors of Scripture and learned men,
did not know in what the kingdom of God consisted.
In the same way, the literal professors of religion today,
whose faith is founded upon the written letter and upon that which is visible,
cannot understand what I say.

Before all else, one must know in what this Day consists:
It is eternal brightness shed abroad through all things, which pierces through, searches,
and makes manifest the most secret places, even that which is invisible.
The nature of everything comes to be seen by the Day of the Lord,
and this Day breaks forth and appears in the heart.
It is there that man must wait for the Day to dawn,
and seek the light which makes manifest all evil,
and declares against all that is contrary to its own nature.
So Christ­--the Covenant of Light, God`'s Gift,
the One sent and anointed of God to proclaim the acceptable year of the Lord
and the Day of vengeance--it is He who dawns and proclaims in the heart.
He comes not to bring peace, but a sword, and His sword is the sword of the Spirit.
It is this sword which divides and discerns the intents of the heart,
and this Day which discovers the desperate wickedness of the heart.
And in the earthly heart, where He finds no faith,
He kindles a fire and executes His vengeance.
To such as these, the Lord`'s Day is a Day of great perplexity.
Their spirits come to be wounded; their hearts are made faint; sorrow fills them,
and trouble is felt.
This is the condition of all who are unconverted,
in whom He finds no faith or hope in the heart,
and so He comes and takes away their peace.
Many have talked of the Day of the Lord, but when it comes to draw near,
they will not be able to stand it.
"`Whatsoever makes manifest is light.`"^
footnote:[Ephesians 5:13]
But when wickedness and deceit are brought to the light,
then they that have done evil cannot abide it.
They will run to anything rather than abide in the Day,
or behold the Lord of life appearing to execute vengeance upon His enemies.

They who have not yet seen this Day of the Lord`'s vengeance in themselves,
cannot see the Day of salvation.
The prophet cried out: "`Who may abide the Day of His coming,
and who shall stand when He appears?`"^
footnote:[Malachi 3:2]
But now many have already been eye witnesses of the dreadful Day of the Lord,
which has appeared, and in which all peace has been hid from their eyes.
For indeed, all who ever came to see the Day of joy and gladness,
first did face the terrible Day of the Lord in themselves.
It is for this reason the apostle said, "`We, knowing the terror of the Lord,
do persuade men.`"^
footnote:[2 Corinthians 5:11]

Now, this Day comes not with outward observation, "`Lo here,
or Lo there,`" for in this way the Pharisees expected the kingdom should come,
even when Christ told them it was within them.
So too I say, if anyone desires to behold the bright shining forth of eternal light,
you must wait for it in that which is pure from God,
through which He will manifest His Day and His power in you.
As you keep in your mind to that light which both manifests evil and shows good unto you,
you will see how it appears, "`Even as the Light shines from the east unto the west,
so is the coming of the Day of the Lord.`"^
footnote:[Matthew 24:27]
The eye which is spiritual sees it,
for the power and glory of the Lord comes to be seen in
the Day which is pure and spiritual in the heart.
Indeed, the eye which is pure does behold when it comes, where it comes, and how it comes.
But it is hid from vulturous eyes, and from eyes which are full of adultery,
and from those who cannot cease from sin.
The Day of the Lord comes not where the carnal mind may imagine,
nor according to man`'s will, or the carnal desires of the carnal heart.
To the evil eye that looks outward, the Day cannot be seen,
but it is seen in God`'s own light, according to the measure of God`'s Holy Spirit.
And as the Day of the Lord is a mystery,
so the Spirit of the Lord is the only discoverer of it,
for "`None know the things of God but by the Spirit of God.`"^
footnote:[1 Corinthians 2:11]

Truly, the Day of the Lord, and His bright shining forth in the heart of man,
is one of the glorious things of God which only the Spirit of God
(and not the mere letter of Scripture) makes known to man and in man.
For the Jews had the letter, but they had neither heard God`'s voice at any time,
or ever seen His form.
Through written words they had neither seen the Day of the Lord, or known His power,
or perceived God, or the mysteries of His kingdom.
Rather, they dreamed, imagined, thought, and conceived things in their minds,
their foolish hearts being darkened.
For the further a man draws away from the light,
his heart comes more and more to be dark,
and his understanding is closed up so that he cannot behold the Lord and His glory.
These things are revealed only by God`'s Holy Spirit, which Spirit is near to man,
though he sees it not.
