== Section VII.

[.chapter-subtitle--blurb]
How the Spirit of Truth operates in those who are convinced,
and yet have not obeyed.

Though God, who is a Spirit, has appeared by His manifestation unto all,
yet all have not received it.
He that hates the light has not received it,
for "`the morning is to him as the shadow of death.`"^
footnote:[Job 24:17]
The evil-doer does not like, heed, or receive,
that which manifests and brings all evil to light,
but rather remains without God in the world that lies in wickedness.
He remains dead in sins and trespasses without the Spirit;
he remains a sepulcher in which the Just One lies slain.
In this state God is not remembered, for there is no remembrance in the grave,
nor thanksgiving in the pit.

Light shines in darkness,
and the man who is convinced but not converted is that darkness,
though that which convinced him is the light.
Disputers argue, "`Only good men have light,
but not those who bring forth deeds of darkness.`"
But, though man is in darkness, and is darkness, the Light shines in him,
the Spirit of God shines there in the darkness, manifesting his darkness.
The Ephesians were darkness in their unconverted state, yet light shined in them.^
footnote:[Ephesians 5:8]
They were once "`without God in the world,`"^
footnote:[Ephesians 2:12]
but Light shined in their darkness, and they were turned to it,
and came to be made "`light in the Lord.`"^
footnote:[Ephesians 5:8]
For indeed, "`It is the God who commanded light to shine out of darkness,
who has shone in our hearts to give the light of the knowledge
of the glory of God in the face of Jesus Christ.`"^
footnote:[2 Corinthians 4:6]
So then, all are without excuse, "`for He has not left himself without a witness`"^
footnote:[Acts 14:17]
in any.
But to those who do not know God`'s witness within them,
that light which should bring assurance of salvation,
unto them it assures their condemnation.

Now, as every man is turned to the measure of God`'s Holy Spirit,
and keeps his mind to it, he comes to feel and see its reproof,
and as the mind is kept to it, the Spirit arises in its purity,
shining forth more brightness in the heart.
This brightness checks for disobedience, judges, and as it is heeded,
appears in strength, laying open every heart, showing how unrighteousness, imaginations,
vanity, idle thoughts, and lust abound within.
Indeed, whatever the mind may run into to take pleasure for a moment,
still the measure of God`'s Spirit is always present to condemn it,
and the strokes of the Almighty fall heavy on the back
of the one still in disobedience to the Spirit.
And though for a time the cry of the Spirit may not be heard,
and through disobedience it may seem as dead unto man, yet if ever the mind is still,
and a man is sober and calm, there it appears again.
And though a man may take up and perform something that is called religious,
and pray with words, and read and talk of the Scriptures,
and take up some carnal outward ordinances, and in this content himself for a time,
yet still the witness of God`'s Holy Spirit shows him to be a hypocrite.
He that seeks to cover and shelter himself while he
continues to live in disobedience to the Spirit,
seeking to be at ease in the flesh, this one will find that all is in vain,
and there is no peace within,
for the measure of God`'s Holy Spirit shows him that he still serves sin.
Indeed, if a man should practice all those things which
others have done in the Spirit and by the Life,
and in which they were formerly accepted of God, yet this will not do,
for God has no pleasure in this any more than if he "`slays a man, breaks a dog`'s neck,
or offers swine`'s blood.`"^
footnote:[Isa. 66:3]
All this is abomination to the Lord.
And if man sins so far against the light of Christ in his own conscience,
that the light becomes to him as though there were no such thing, yet this is no excuse.
For the Lord will thunder from His holy place, and will cause him to see and hear,
even though he has stopped up his ears and closed his eyes.
He will cause His terror to strike into the heart,
so that dread will compass him about as a wall,
and he will be afraid of what he then sees and hears.
For though the Spirit strives long with man,
yet the longsuffering of God at last comes to an end with those who disobey,
and they will have their portion forever with the
rebellious and stiff-necked in the lowest hell,
forever among the children of darkness,
who have not submitted to the leading of the Spirit.
Think on this, for it is the Lord`'s truth which I declare to you.

If you will persist after the imaginations of your own heart,
and of your own rebellious will, then you indeed quench the Spirit and His motions.
And though the Spirit is life in itself, yet it is dead unto you,
who are resisting that light through which God`'s eternal power is manifest.
Surely you will grow insensible and past feeling, and become seared in your conscious,
and be senseless as to the things of God,
and hardness of heart will come upon you like a stone that cannot be melted.
Woe unto those in whom the Spirit of the Lord ceases to strive,
having so long rebelled against its pure drawings, and grieved the Lord.
For the Lord at last gives man up to his vile affections,
to follow the imaginations of his own heart (who receive not the truth in
the love of it). To those who have despised the Spirit of grace,
His longsuffering comes to an end, and His fierce wrath is kindled,
and that which would have led them out of the world into true everlasting peace,
now becomes their tormentor.
For they are banished from His presence, and shut up in eternal misery,
where the fire is kindled by the breath of the Lord that burns
forever "`because they had pleasure in unrighteousness,
and have sold themselves to do wickedly,`"^
footnote:[2 Thessalonians 2:12]
crucifying the appearance of Christ in themselves.
And this appearance, though crucified by them,
yet lives forever to be their eternal condemnation.
