== Section VIII.

[.chapter-subtitle--blurb]
How the Spirit of the Father works in those who are turned to it,
and have taken heed to its manifestations, and are,
in some measure, partakers of His power.

"`There are diversities of gifts, but the same Spirit.
There are differences of ministries, but the same Lord.
And there are diversities of activities, but it is the same God who works all in all.`"^
footnote:[1 Corinthians 12:4-6]
Now the Spirit of Truth, which is life in itself,
operates not only to convince the one that transgresses against its appearance,
and to manifest the evil which has been committed, but also,
being turned unto and waited in,
it shows man when the motions and temptations to sin arise.
And as the creature is still, and waits in the light which makes manifest,
and keeps his mind singly to it, it sheds abroad its power,
vanquishes and subdues the lusts which arise,
and condemns the ground from which they raise.
It works secretly,
breathing forth its pure life in the one that waits in patience and stillness,
not heeding the vain thoughts and imaginations that arise in his heart,
but rather the manifestation of the Spirit,
at whose bright appearance all vain desires come to be extinguished,
and a hunger is begotten within to be made partakers of its nature and purity.

For God, through the operation of His eternal Spirit, lets forth His power,
which turns and changes the heart,
and cuts asunder and divides between a man and
the lovers unto whom he has joined himself.
The Lord makes a separation within,
and carries a man further away from those things which the Spirit reproves,
leading the soul nearer unto God.
And so, they that do believe in the measure of God`'s Spirit, and diligently wait upon it,
come to feel what repentance from dead works truly is,
for both the works and the worker are made manifest in the light.

Now, for the one who singly and quietly waits upon the Spirit,
there is nothing that passes through the mind but what can be
easily discerned by the One who gives discernment.
Yet, even after the Spirit of truth is in some measure felt,
and its living testimony is known,
it may still be long before there is a clear discerning in the understanding,
so that the Spirit`'s movings can be clearly distinguished from
all false motions and high imaginations which have risen above.
But hasty and forward minds follow their vain motions which lead them into deceit,
and then the questioner rises up,
and they question all that ever the Spirit has made manifest to them before.
A veil is then drawn over, and the enemy lodges in the darkness which has entered.
And as soon as any listen to his voice, he presents motions for them to obey,
and they are deceived by him.
Therefore, all are to keep back to the measure of the Spirit,
that they may sensibly feel the difference between the
pure motions and drawing of the Spirit,
and the vain thoughts that arise out of the earthly heart.
And when anything does arise which the light does not give witness to,
it is not to be followed or heeded, but a quiet and still waiting is to be observed,
so that all things may be made clear to the understanding.
For lack of this, many have run out, and acted things forwardly in their own will,
bringing forth Satan`'s work.
These have lost the true sense of that which should guide their minds,
and instead have followed the spirit of error,
causing the pure Spirit of the Lord to be evilly spoken of.

But as there is a keeping back, and a quiet waiting,
keeping out of willing or running and haste,
then does the Spirit arise purely and stilly in the heart,
and shines forth in brightness within,
so that it gives perfect evidence and full testimony of itself,
so that there can be no doubting or questioning of its motion.
For it will clearly show forth itself in its own transparent brightness,
with full assurance of its own will.
And then, after its motions are clearly seen, let all reasoning be kept under,
and all questioning kept out, and do not give way to temptation.
For that which moves of the Lord of Life will carry you through in
its own operation and power to accomplish the will of God.
In this way you will have peace in obedience, and your strength will be renewed.
For as any is brought to submit to the will of God when it is known,
and comes to obey by the virtue of God`'s own power,
then that which is contrary to God`'s Spirit in you loses its strength,
and begins to decay and be weakened.
But, as any disobey the pure motion of God`'s Holy Spirit after it is known,
the enemy is then strengthened, and that which is of the flesh is nourished,
and the Spirit (which gives His power when submitted to) comes to be quenched in you.
But know this: the Spirit in itself never loses its purity,
nor can it be quenched in itself.
It will bear its pure witness against you, and none shall be able to stop its reproof.

As the Spirit is listened to, obeyed, loved, and believed in,
it puts forth its pure power, which gives strength and seals peace to the obedient.
In this way the diversity of the Spirit`'s operation comes to be known.
But as it is disobeyed and resisted, it condemns, judges, reproves,
and seals condemnation to the disobedient.
Yet, though its operations vary, there is no variation in the Spirit itself;
for it is always one and the same.
In good ground it causes to bring forth fruit unto God.
And in the cursed ground, out of which arise briars and thorns,
it kindles a fire that shall not be quenched.
But as there is a submission unto the Spirit`'s pure operation,
there is a burning and destroying of all that hinders the growth of the Seed,
and a purging of the heart from all filthiness of flesh and spirit.
So the Spirit works the creature into its own frame and nature,
and fashions and molds all who are in the faith into the image of the Father.
Here the love of the Father comes to be shed abroad in the heart.
And even as wrath was revealed through the spirit of condemnation,
so now the peace of God comes to be enjoyed, and His consolation is greatly shed abroad,
in which there is pure rejoicing forever.
