== Section X.

[.chapter-subtitle--blurb]
What the free grace of God is, unto whom it has appeared,
and how all are to wait to receive it.

Titus 2:11-14  For the grace of God that brings
salvation has appeared to all men, teaching us that,
denying ungodliness and worldly lusts, we should live soberly, righteously,
and godly in the present age,
looking for the blessed hope and glorious appearing of
our great God and Savior Jesus Christ,
who gave Himself for us,
that He might redeem us from every lawless deed
and purify for Himself His own special people,
zealous for good works.

The grace of God is a pure, perfect, and free gift of God.
It is the appearance of Christ, the beam of righteousness shining forth,
a measure of God's strength and power issuing out from Himself.
It is a portion of His treasure, virtue,
and sufficiency which is shed abroad in all who believe in it.
It is that through which God makes known His will, teaches,
and reveals His saving health to those who are taught by it, believe in it,
are built up in the truth, and become a habitation of God.
No man does anything to purchase it.
None need say,
"`Where may I get it?`" or "`How may I know its teaching?`" It is near you; it is in you;
it "`has appeared to all men,`" showing ungodliness in
the heart of man by its own brightness.
Yes, to all men it shows the motions unto sin.
And whatever is not like God in its motions, words, or actions,
it draws the heart of man away from as with a chord.
It shows the lusts of the heart and mind, "`the lust of the eye, and the pride of life.`"^
footnote:[1 John 2:16]
It never joins to sin.
Nothing can alter its purity or property, for in itself it is always one and the same.
It is perfect, and will always be so.
It stands off at a distance from that which is corruptible and imperfect,
and yet it beholds it.
And although some that have turned to it have again turned from it,
and have turned it (as in themselves) into wantonness, still it keeps its purity,
and reproves all wantonness, and will lay it before you,
showing you how you have abused the appearance of Christ.

Many have been talkers of the grace of God in this professing age,
but have not known of what they spoke,
nor made known to men where it was to be waited for, how it might be known,
or what was its operation in man.
Instead, they have applauded their own imaginations saying,
"`We are justified by His free grace from all sins past, present,
and to come,`" and in this conceit thousands have been led into the pit of darkness.
In this darkness they cry out,
"`We are justified by the free grace of Christ,`" but the free grace of God
(had they known it) would have taught them that they never heeded it at all,
but rather rose up into conceitedness, carelessness, and presumption,
without the fear of God.
Claiming justification, they are themselves still servants of sin,
and bondslaves to corruption,
and this is the state of thousands at this day who have
been preachers and publishers of free grace.
And now, when grace has come to be witnessed by some, and declared (as to what it is,
and where it is),
these blind guides and ignorant shepherds seek to kill
those who are fed and taught by the true gift of God.
They deceive the sheep, scatter them from the fold, and lead them from the true Shepherd,
and from His appearance (which is His grace) and
from His voice (which is the Word of His grace),
which is able to save the soul.
Oh all you blind guides, and you that call yourselves orthodox men, and ministers,
who preach grace in words!
Now at last God has given those who have waited
upon Him an understanding to declare grace,
and yet you cry out, "`Grace is not a sufficient teacher!`"
Now let me ask you a question: Is the grace which makes manifest ungodliness,
and teaches to deny it, not a sufficient teacher? If it is not a sufficient teacher,
why did the Apostle commit them and commend them to the Word of grace which
is able to save the soul? (Acts 20:32) Answer me you wise men--is that
which reveals sin and temptation not sufficient?

Truly that which reveals sin is holy,
and that which leads from worldly lusts is pure, and that which saves from sin is grace.
"`For God so loved the world, that He sent His only Son into the world.`"
He was and is the Light of the world, and has shed abroad His grace,
and has made it appear to all.
And all who wait upon it, and come to be taught by it, feel its assurance,
so that all are left without excuse.
Therefore, wait in that which has appeared in you.
Wait in that which shows the lusts, and thoughts, and motions unto sin.
This is God's gift, God's grace, and it is sufficient, though all men deny it.
All are to wait within, to hear Him who condemns sin in the flesh within,
who by His grace shows man his transgression and insufficiency in himself,
and by the Word of His grace saves out of sin, and gives dominion over sin.
This comes to be revealed in the heart of man,
and there it must be waited for in that which is pure.
There, in the heart, grace is received, and there its operation comes to be known,
and its virtue is partaken of by all that believe in it, receive it,
and are subject to it.
These see and feel God's salvation revealed through grace to their souls,
and they know where their strength lies--not in self-acting, but in the free gift of God,
the gift of righteousness, the righteous gift,
by which justification comes upon those who believe.
