== Section XI.

[.chapter-subtitle--blurb]
Whether all have received the grace of God or not,
and whether it is a sufficient teacher in itself.

This wise generation, whose wisdom is below the wisdom of God,
has confounded people's minds with false distinctions,
asserting there is a two-fold grace.
First, there is that which they call "`common grace,`" which has appeared to all men.
Second, there is that which they call "`special and saving grace,`"
which has only appeared to the saints.
By giving heed to these distinctions (in times past, many years ago),
I lost myself and my Guide,
disregarding His appearance within me and hearkening to a thing at a distance from me.
I did not heed the grace which was at home and near because it was called "`
common and insufficient,`" and in this way I suffered great loss.
So now I am moved by Him (in whose sight I have found favor and mercy and
grace) to declare the truth as the Lord has made it manifest to me and in me,
so that all who seek after the Lord may be informed and know where to wait upon the Lord.
For unto that appearance which first showed me evil and temptation I
was made to go back (even after many years of Christian profession)
before I ever found the Lord or felt His living power again.

Now, the wise of this age defend their "`common grace`" with the written letter,
where it is said,
"`He causes the sun to shine and the rain to fall upon the just and the unjust,`"^
footnote:[Matthew 5:45]
and where it is said, "`in Him we live, and move, and have our being.`"^
footnote:[Acts 17:28]
For, they say, God has given to all health, strength,
and understanding in natural things, and an ability to see grosser sins and evils.
But that which they call "`special grace`" is that by
which saints are saved and established in righteousness,
and by which man receives remission of sins.
But these have failed to see that He who causes the sun to shine, and the rain to fall,
and gives health, strength, and nourishment to the outward, visible creation,
is the same who is the Life of the soul.
The same Power that discovers the dark places of the horrible pit,
leads all who believe in it unto the land of the living.
The One who discovers the grosser sins and evils to man is the same that sanctifies,
purifies, and saves them that believe.
The same virtue and power that upholds the natural man
is that which upholds the spiritual man,
and that by which he lives unto God.
It is the same grace, but I do not say that it is the same measure.
For it is the virtue and power of God which made all visible and living things,
and which causes them to subsist in their station, covenant,
and bound where they are placed.
And indeed, it is this same grace, strength, and power, but in a higher sphere or degree,
that preserves all that believe, who have been made alive by Him,
and raised up to sit down in heavenly places.
And even among those who believe, though there be the same grace at work in all,
still there may be a greater measure of its purity shining in one than in another,
rending the veil, making the shadows to fly away, scattering the clouds,
because the heart of one is more open to receive its virtue.
Nevertheless, it is the same virtue and purity,
and the grace keeps its purity and property in itself,
and its power and sufficiency is always the same,
though it does not appear so to the creature.

So this is my testimony of the grace of God, which is the gift of God,
and which has appeared in some measure, more or less, unto all men:
It is the grace of God which convinces of gross and open evils,
and it is the same grace that leads from the least impure thought, unbelief, temptation,
and secret evils that lodge in the heart.
Indeed, this shall be witnessed to be truth by the whole
earth in the Day of the Lord's appearing,
and is now witnessed by all the children of Light who believe,
with whom I have fellowship in the pure, living, sufficient, and perfect grace of God.
Therefore, all are left without excuse,
for all that turn to His grace will see that He has long waited to be gracious,
and that all mankind might be partakers of His bounty, love, mercy, and free gift,
by which justification comes upon all that believe.
This I write for the sake of such who thirst after God and the knowledge of Him,
and not to satisfy critical men, nor those who are in philosophy and vain deceit,
who are swollen big in their fleshly understanding,
and puffed up in their earthly minds.

But now I come to speak about that which many are doubting, which is,
"`the grace of God which brings salvation,
which has appeared to all men`"--whether this be
a sufficient leader and teacher when received.
Let all first take notice that when I speak of the sufficiency of grace as a teacher,
I do not speak of grace as distinct from Christ,
or as a thing separate from the power of God,
but rather as being one with it and with Him from which it comes.
For as Christ is salvation itself, so the grace of God is of the same nature,
and by it He manifests Himself and His salvation to those that believe,
revealing His witness within them.
For wherever the appearance and presence of Christ is manifest,
there His power and strength is also manifest, either to salvation or condemnation.
And though His pure appearance and presence is one in itself,
yet it is very dreadful and terrible to those who have pierced Him,
while it is delightful, sweet, pleasant, glorious,
and admirable to those who have believed, suffered with Him, and longed for Him.
Oh that all who long after Him may wait for Him in patience,
in that light wherein He will appear!
For surely they will see Him, and His sight will be a recompense for all longing,
thirsting, desiring, and waiting.
The sense of longing and thirsting will be taken
away when He who makes the heart glad appears,
and lifts up the light of His countenance.
Therefore all wait, and do not think the time long.
Keep in your minds to His grace, which is His appearance, and you will feel and see Him,
and be satisfied.
And you will say, "`This is He whom we have waited for,
let us rejoice and be exceedingly glad; for now He is come, and His reward is with Him.`"

Now God, out of His everlasting love unto the sons of men, has followed man,
and has called him to return.
Yet there is a nature which has risen above in man,
and has transgressed against the Life, and which always resists the drawings of the Lord.
For it is not subject to the law of God,
nor to the grace of God which teaches to deny ungodliness and worldly lusts.
This nature has surrounded the creature like a thick cloud,
and makes war against the soul,
and there is none to deliver until there is a listening
to the grace which shows ungodliness and worldly lusts.
For indeed,
none have power or dominion over that nature in them which leads into transgression;
but the grace of God has power in itself.
Truly God (who is salvation itself) has reached out from Himself,
and has appeared in His pure and perfect grace unto all men,
yet all have not received this grace.
For though the Lord offers grace so that the creature might
receive it and partake of its living virtue and operation,
yet while that nature which is contrary to grace has preeminence,
it will never receive it, knowing that the grace of God will mortify it,
take its life away, and slay the enmity.
Therefore, all must be still and quiet, and wait in that which is pure from the Lord,
and feel that which receives grace rise up above all
corruptible thoughts and desires of the carnal mind.

Many who talk of free grace, put no difference between the precious and the vile,
but set people upon doing and working who are still in the enmity, in the curse,
and in death.
Thus they have brought forth dead works, notwithstanding all their performances.
For since they are dead to the life of God, another acts in them,
even he who has the power of death, which is the devil.
And not knowing what is precious in themselves,
they cannot minister unto that which is precious in others,
but are instead ministers of death.

Now, though all have not received grace,
so as to save them from the committing of sin, the fault is not in God.
For, "`Israel would have none of my counsel; they stopped their ears.`"^
footnote:[Zechariah 7:11]
Neither is the fault in the grace which has appeared to all men,
as though it were too weak or small.
Rather, the fault is that the grace is not hearkened unto, and waited in, and obeyed,
believed in, and received.
For this is eternal truth, which will forever stand:
The least measure of the grace of God has power in itself to
save man from committing the evil or sin which it shows to man.
And as it is received, the power comes more and more to be made manifest,
and all who believe come to be preserved out of evil.

[.discourse-part]
Objection: But some now say, "`There is common grace and saving grace,
and the former has appeared to all,
but the latter has appeared only to the saints and to the elect.`"

[.discourse-part]
Answer: Grace, which is God's pure and perfect gift, is but one thing.
I do not say that the fullness of grace has appeared to all,
but a measure of that fullness, which is Christ, the Head.
Nevertheless, I cannot divide the least measure from the fullness in quality or nature,
for it is one and the same.
For the same grace which leads a man from drunkenness and excess, is as pure,
and of the same kind and nature,
as the greater proportion which leads a man from all sin.
I speak what I have seen from the Father, though the dark world cannot receive it.
For people have been blinded and darkened with distinctions
which men have coined and framed in their natural reason,
and by natural giftings, which are outside of the Life.
(Though I do not condemn natural abilities,
so long as they are kept in their proper bounds and compass, that is to say,
to the management of natural things in the visible creation.
For the things of God's kingdom are of another quality and nature,
and cannot be reached by natural abilities.)

[.discourse-part]
Objection: But some will be ready to say, "`This is error,
and is contrary to Scripture and to orthodox teachers,
to suggest that the grace which is saving is near all mean,
and has appeared to all men.`"

[.discourse-part]
Answer: Though the grace which has appeared to all men is saving in itself,
and may be truly called saving grace, yet to them that do not believe in it,
nor are taught by it, to these it only convinces and shows evil,
checks and judges for sin.
Yet there is no variation or change in the grace itself,
for the variation is in how it works upon different objects.
For the word of His grace is a savor of life unto life to those who believe,
and is a savor of death unto death to those who are in the unbelief
(who indeed are dead while they live). Here is the same grace,
and yet here are different operations.
For "`The Lord kills and makes alive,`"^
footnote:[1 Samuel 2:6]
but He is the same Lord.
The same Spirit convinces and reproves for sin, and also comforts and consoles.
Here is diversity in operation, yet the same Spirit which never changes.

[.discourse-part]
Objection: But some may say, "`If a measure of saving grace has appeared to all men,
then how is it that all are not saved by it?`"

[.discourse-part]
Answer: All are not saved by it because they do not believe in it, nor are taught by it.
And though they who are careless and heedless say,
"`We feel no power or sufficiency in it to save us from sin,`" yet this does
not nullify the confidence of those who have received it and know its power.
For there is power and sufficiency in grace to do the will of God.
But what if unbelievers, who are alienated from life, say,
"`There is no beauty in Christ, neither form nor comeliness;`"^
footnote:[Isaiah 53:2]
this does not make His glory void who is the express image of the Father,
full of grace and truth.
The disciples, who were in the faith saw His glory, and bore record of Him;
but the Pharisees, who were in unbelief, said: "`He has a devil.`"^
footnote:[John 10:20]

Therefore, here is my testimony: The grace of God, the perfect gift of God,
which shows ungodliness, and leads all who are taught by it out from ungodliness,
is a sufficient teacher in itself,
for the power of Christ is made manifest through grace unto all who hearken to it.
Paul, a minister of the word of reconciliation,
who was caught up into the third heavens where he saw things unutterable,
came to be tempted and buffeted by a messenger of Satan,
and fear and doubting rose up within him.
Three times he prayed unto God, and this answer was given to him,
"`My grace is sufficient for you.`"^
footnote:[2 Corinthians 12:9]
Thus it is evident to all understandings that have been opened by the Lord,
that the very thing which showed him the temptations,
and Satan's messengers and buffetings, was also sufficient to preserve him.
So grace is sufficient for all who are singly kept to it and in it,
sufficient to reveal ungodliness because of its purity,
to lead out of worldly lusts by its power, to teach the will of God,
and to live righteously in this present world.
This testimony I bear to the grace of God,
even what I have felt and tasted and handled of its sufficiency, virtue,
and the power of its operation,
which testimony I commend to that which is from God in every man,
which will bear me witness in the Day of God.
