== Section XIII.

[.chapter-subtitle--blurb]
The kingdom of God and of His Christ declared in some measure, what it is,
where it is to be waited for,
and how it comes to be revealed to them and in them that believe.

The Lord has prepared His throne in the heavens; His kingdom rules over all,
and His dominion is an everlasting dominion.
God is a Spirit; His kingdom is spiritual; His habitation is suitable to His own nature.
He is immortal; His kingdom is so.
He is Light; His dwelling place is so--a pure habitation where there is no uncleanness,
nor ever shall be.
It consists in purity and pleasantness, in power, righteousness, joy, hope, peace, life,
quietness, and eternal virtue.
It is a quiet habitation, eternally glorious, incomprehensible, unsearchable,
and undeclarable.
Words come too short; they are but sounds, and are like veils.
All who believe in the King of eternal and immortal glory come to receive of His wisdom,
of His life, of His power, virtue, righteousness,
and to enjoy Him who is the fullness that fills all things, whether visible or invisible,
earthly or heavenly.

Oh, but these things are hidden from the world,
from those who are not redeemed from the earth,
nor even seek to be so while they are in the body.
Unto such I say,
you will never see or enjoy God's kingdom while you remain in a faith that is reprobate,
in a faith that may truly be called unbelief.
Though you imagine a glory and a kingdom in your earthly mind,
and dream of a thing to come (which corresponds
to that nature in which your glory now stands),
yet this will all fail,
and those imaginations will be confounded and dissolve into nothing.
These dreams stand outside of the truth, outside of Christ,
and so are without ground or foundation,
and are outside of that which would give you sight and knowledge of God and His kingdom.

Christ, when He taught those who followed Him,
exhorted them to "`seek first the kingdom of God,`"^
footnote:[Matthew 6:33]
even while they were in the body.
The Pharisees were gazing abroad in their earthly knowledge,
and though they had the Scriptures which declared God's kingdom, yet they knew it not.
And now this generation is the same, and are in the same nature, and the same wisdom,
which is earthly and literal.
They are imagining, as the Jews were, and saying "`lo here,
and lo there,`" the kingdom is in this observation, and in that thing.
No, Christ said, "`The kingdom of God is within you,`"^
footnote:[Luke 17:21]
and He bid them to seek it first.
"`What strange doctrine is this?`" might the Pharisees have said.
"`He says the kingdom is within us, and yet bids us to seek it!
Must we seek that which is already in us?`" Yes,
it is like a pearl or treasure hidden in a field.
It is like a grain of mustard seed among many other great seeds,
which is not easily found.
It is like a piece of silver lost in the house among much rubble,
and until the rubble be swept away you will not find it.
You must dig deep, sweep clean, search narrowly, before you find it.
And though He said to the Pharisees "`the kingdom of God is
within you,`" He did not say that they were possessors of it,
or that it was theirs.
However, to the disciples,
whom He taught to pray in faith "`Thy kingdom come,`"
these came to find what they prayed for--the pearl,
the coin, the grain of mustard seed.
And having found it, and believed in it, He said unto them,
"`Blessed are the poor in Spirit, for theirs is the kingdom of God.`"^
footnote:[Matthew 5:3]
And in Luke 6:20 "`And He lifted up His eyes upon His disciples, and said,
'Blessed are you poor, for yours is the kingdom of God.'`" They had seen it,
and were possessors of it; it was indeed theirs.
And Christ said unto His disciples,
"`There are some of you standing here that shall not taste
death until you see the kingdom of God come in power.`"^
footnote:[Matthew 16:28; Mark 9:1; Luke 9:27]
And indeed His words were fulfilled, for they declared what they had felt and seen,
and some of them said, "`The kingdom of God is not in word, but in power.`"^
footnote:[1 Corinthians 4:20]
And Paul wrote to the Romans (who were also made partakers of the same power
and kingdom) that "`the kingdom of God is not eating and drinking,
but righteousness and peace and joy in the Holy Spirit.`"^
footnote:[Romans 14:17]
And of the Colossians, who had waited for the kingdom,
and believed in that light by which it was revealed, it is said,
"`Giving thanks to the Father who has qualified us to be
partakers of the inheritance of the saints in the light.
He has delivered us from the power of darkness and
conveyed us into the kingdom of the Son of His love.`"^
footnote:[Colossians 1:12-13]
These things were seen even in the body, and witnessed in the body.
And the apostle to the Hebrews says, "`He that believes is entered into the rest.`"^
footnote:[Hebrews 4:3]
Now all these things are felt within by the immortal Seed, the immortal birth,
and by those who witness this immortal birth to live in them.
And all that ever come to see and feel the kingdom of God which is spiritual,
must wait in the Spirit, and in its manifestation.

[.discourse-part]
Objection: But some say that there is a two-fold kingdom--the one of grace here and now,
and the other of glory hereafter,
which no one comes to enjoy in this life or in the body.

[.discourse-part]
Answer: People have long been blinded and confused about names and words,
and being full of imaginary thoughts and
concepts have brought forth foolish distinctions;
and that which God has joined together, they would separate.
Grace is glorious, and glory is gracious, they are not separate.
The kingdom of God, which was once like a grain of mustard seed,
afterwards becomes a great tree.
And though the tree in its strength and glory and
height is more glorious than when it was in the seed,
yet the seed and the tree are one in nature, quality, and kind.
If the kingdom of God is in dominion, purity, power, and glory,
is there not unity here? Though there be greater measures,
yet is not the dominion still one, the power one, the glory one,
the kingdom one in which both the grace and the glory stand? Grace is indeed glorious,
"`Having predestined us unto the adoption as sons,
to the praise of the glory of His grace,
wherein He has made us accepted in the beloved.`"^
footnote:[Ephesians 1:6-7]
And it is through grace that glory comes to be revealed
in the earth--"`The earth is full of His glory.`"^
footnote:[Isaiah 6:3]
For God is revealing His power, His kingdom, His grace,
and His glory unto all who patiently wait upon Him in
that which may be as yet a grain of mustard seed.
These will come to feel His presence,
His power and glory revealed in the heart through the Spirit,
and will enjoy God in His kingdom, power, and glory,
and through faith will see the weight of glory.

[.discourse-part]
Objection: But some will cry out,
"`What? Do you look for no other glory but in this life,
nor for any other kingdom but what you enjoy in this life?`"

[.discourse-part]
Answer: The saints looked for no other glory but that which stood in eternal life,
in the immortal, incorruptible life,
and the country they sought after was that of which God was the maker and builder.
These looked and waited to receive of its power, the power in which the kingdom stands,
and they did in this life come to know and enjoy it (though I do not say the
full weight of glory). For to be made partakers of His eternal dominion and
authority is that which all the saints did witness,
and in time they came to enjoy it through faith.
For by faith they saw Him who was invisible,
and the things of His kingdom which are invisible, spiritual, and eternal.
But to speak of the carnal, corruptible life of the flesh,
and of those who are dead while they live therein, that life knows neither the kingdom,
nor the power, nor the glory.
The glory of God is not revealed to man until after the death of that life,
and the death of the one who has the power of death, which is the devil,
who rules in the hearts of the children of disobedience.
Indeed the kingdom of God is hidden from the eyes of all while they remain in that state.

But blessed is the ear that can hear,
for the kingdom of God has come near unto many,
and the salvation of God and the power of His Christ is seen by many.
Honor and praise unto Him forever, who is the only potentate,
and who puts down all authority under His feet, that God may be all and in all.
But first everyone must come to feel the kingdom of God in himself,
which begins as a little grain within.
In this, man must come to believe before he can truly know the kingdom,
or in what it consists.
And even after it is known in measure,
the measure is still far short of the glory in fullness.
For indeed, many may come to be partakers of the power in some measure,
yet the measure is far short of the eternal weight of glory.

"`He that believes has entered into the rest,`"
and is made a partaker of the heavenly gift,
the heavenly power, the heavenly grace (all of which is glorious),
and he indeed witnesses a heavenly place in Christ Jesus.
And yet there remain many enemies still to be subdued,
and there is much of the heavenly habitation which he does not yet see.
These come to be revealed as there is an abiding
in the faith which stands in the power of God.
Indeed, the mysteries of God and His kingdom come in due time to be revealed;
through death they come to be known, that is to say, through the death of death.
For in the case of Israel, the true type,
after they passed over the Jordan and had taken Jericho and Ai,
and had made an entrance into the land, yet there were still many enemies to be subdued,
and much land still to be possessed, which they did not partake of until long after.
Even so now, after there is a true rest enjoyed and possessed,
and an entrance made into the kingdom, yet there are many enemies to be subdued,
and still much heavenly inheritance to be enjoyed by those who
stand in the power which gives dominion over sin,
the devil, hell and the grave.
These are made partakers of God, and as the enmity is slain,
they enjoy God (who is eternal life). These come to receive the immortal crown,
which God gives in due time to those who wait in patience and faith,
through which the immortal inheritance comes to
be revealed to all the children of light.

And so to conclude in a few words, this I say unto all who are longing after God,
and waiting to feel His power:
Keep in your minds to the pure measure of God's Holy Spirit,
and therein wait to see His kingdom and dominion, and to be made partakers of it.
For this kingdom brings the world to an end, and will let you see to the end of it too,
and before it was,
and also the One who is now glorified with the Father in the kingdom of God
with the same glory He had with the Father before the world began.
And whoever comes to the end of the world, and to the true beginning again,
comes to see Him in His glory, and the kingdom of glory which fades not away.
Indeed all who come to enjoy this are eternally happy.
